### ISSUE TITLE
Crash when placing Framed Wall

### ISSUE THREAD

**Issue by DemonSlayer112** [XFactHD/FramedBlocks#101]
Modpack: Project Architect
Modpack Version: 1.9
Mc Version: 1.16.5
Using the Project Architect modpack, im unable to tell if another mod causes this along side but the crash was instant when the wall was placed and it was placed next to vanilla blocks.
Crash log:
[latest.log](https://github.com/XFactHD/FramedBlocks/files/8502575/latest.log)
 
Second Log:
[hs_err_pid26832.log](https://github.com/XFactHD/FramedBlocks/files/8502581/hs_err_pid26832.log)

**Comment by XFactHD** [comment]
This is the third time I am seeing this specific crash and I have no idea how it's possible. Unfortunately these specific types of crashes are extremely hard to diagnose.

If you are using performance enhancing mods such as Rubidium, Magnesium, etc., then I would suggest trying it without those.
If this doesn't help and the crash is repeatable, then the only suggestion I can give you for now is to disable the ghost block rendering in the FramedBlocks client config.

**Comment by XFactHD** [comment]
Closing due to lack of feedback.
If you decide to provide the necessary information at a later time, feel free to comment on this issue and I will reopen it if needed.

**Comment by SteaSteaStea** [comment]
I think I had the same issue - using magnesium. 

Setting "detailedCulling = false" in the config seems to have fixed the crash.

**Comment by XFactHD** [comment]
A crash in the detailed culling system has nothing to do with the crash the author of this issue had.

If you can reproduce the crash you encountered on a supported version (currently 1.18 and 1.19), then please open a new issue so I can take a look.
