### ISSUE TITLE
Framed wall rendering issues

### ISSUE THREAD

**Issue by LindaJuffermans** [XFactHD/FramedBlocks#106]
**1) Missing face**
When a framed wall connects to a wall below, the bottom face is not rendering:
![2022-04-27_13 56 19](https://user-images.githubusercontent.com/31929183/165513287-01b7dd28-c55c-4588-a326-34de57915f06.png)

Note that this is not observed when there are e.g. glass panes inside the wall:
![2022-04-27_13 56 25](https://user-images.githubusercontent.com/31929183/165513353-af9979d0-2b57-4bf2-8087-905a7ba05345.png)

**2) Not connecting**
The framed wall doesn't connect to visually full blocks, in this case Integrated Dynamics Facade blocks:
![2022-04-27_13 56 35](https://user-images.githubusercontent.com/31929183/165513447-0af023e8-20ce-4f8a-983e-e39a6b878290.png)

FramedBlocks-2.14.4.jar for Minecraft 1.16.5

**Comment by XFactHD** [comment]
> **1) Missing face** 

Nice catch, I completely missed that. The walls are a mysterium sometimes and I am always discovering new connection behaviors I didn't know existed.
I have pushed a fix for the incorrect face culling, will be released with the next update. As this is non-critical, I will not release this immediately.

> **2) Not connecting**

In terms of the connection logic, the Framed Walls are equivalent to vanilla walls, so vanilla walls will most likely not connect to those blocks as well. Have you tested what happens with those special blocks and vanilla walls?

**Comment by LindaJuffermans** [comment]
Regarding 2: You're correct, vanilla walls also don't connect. I'll report it on the ID github.

**Comment by XFactHD** [comment]
Thank you for the feedback, I'll close this as fixed.

**Comment by LindaJuffermans** [comment]
Almost the same except it's an AE2 facade that acts as a full block for vanilla cobblestone walls but not for Framed Wall:

![image](https://user-images.githubusercontent.com/31929183/167460556-8c6695cf-2d26-4b34-b326-572ad3e2b19e.png)

**Comment by XFactHD** [comment]
Weird, I'll have to look into that, that should just work the same way the cobblestone wall works.
Please make a new issue for this with the relevant version details to make it easier to keep track of.

**Comment by LindaJuffermans** [comment]
https://github.com/XFactHD/FramedBlocks/issues/111
