### ISSUE TITLE
Vertical framed slope slabs?

### ISSUE THREAD

**Issue by NoahSlocombe** [XFactHD/FramedBlocks#107]
Is there any way to achieve vertical slope slaps other than using the collapsible blocks or is this not implemented yet? If not, will it be implemented?

**Comment by XFactHD** [comment]
Vertical versions of the different Framed Slope Slab variants are currently not a thing because the amount of combinations would make placing the block really hard and akward.
That being said, I'll think about adding vertical versions as separate blocks.

**Comment by LindaJuffermans** [comment]
Similarly, Framed Elevated Sloped Slab can be placed upside down, Framed Slope Slab cannot.

![image](https://user-images.githubusercontent.com/31929183/166150415-be4ced74-5733-4be3-a0e7-fab479e9a75a.png)

(Let me know if you want this in a separate ticket)

**Comment by XFactHD** [comment]
Framed Slope Slabs can be placed upside down by holding the sneak key while placing them. I couldn't think of another way to allow the user to express the choice of upside down or not while still keeping the placement logic simple.
I completely forgot to add a comment about this on the CF page, I'll do that ASAP.

**Comment by LindaJuffermans** [comment]
Ah, unexpected... thanks :)

**Comment by NoahSlocombe** [comment]
Thank you very much!
