### ISSUE TITLE
Flipped tri

### ISSUE THREAD

**Issue by Ioncloud9** [XFactHD/FramedBlocks#11]
if I place a slope west to east (ascending) things are fine
if I place a slope east to west (descending) the texture for the south facing side is rotated 180 degrees

this is the latest version of all the mods, so if it's been fixed in a later version than that modpack has, apologies

**Comment by XFactHD** [comment]
MC version?
Forge version?
FramedBlocks version?
Do you have OptiFine and/or FerriteCore installed?
Please provide a screenshot of the blocks

**Comment by Ioncloud9** [comment]
it's 1.16, 
All the Mods 6 v1.5.7 
Framed blocks 2.4
Forge 36.1.2

And I went to get a screen and it seems fine now... very strange, must have been a client side glitch... if it happens again I'll screen it

**Comment by Ioncloud9** [comment]
got it
https://imgur.com/a/7IsMJaz

**Comment by XFactHD** [comment]
Known issue, see https://github.com/XFactHD/FramedBlocks/issues/6#issuecomment-792865827 for the solution.
When I know that FramedBlocks 2.5 is stable, I will mark it as release and hopefully ATM updates to that.
