### ISSUE TITLE
Another stair rendering x-ray

### ISSUE THREAD

**Issue by LindaJuffermans** [XFactHD/FramedBlocks#113]
Left: A horizontal stair (facing: west, half: top, shape: straight)
Right: A vertical stair (facing: west, type: vertical)
![image](https://user-images.githubusercontent.com/31929183/169057141-53f17ce9-2c09-4960-9f05-1e74a5509003.png)

When a texture is applied to the horizontal stair, part of the vertical stair becomes invisible:
![image](https://user-images.githubusercontent.com/31929183/169057342-267dcc77-4d98-4ca2-8b62-2804e87be4f4.png)
![image](https://user-images.githubusercontent.com/31929183/169057385-4290fbde-b3cd-49b7-b2b6-89bc1bae499f.png)

Same thing happens on the mirrored version btw:
![image](https://user-images.githubusercontent.com/31929183/169057464-964f4027-6121-49e5-a63f-1935b385d85a.png)

forge-1.16.5-36.2.34.jar
FramedBlocks-2.15.1.jar
No Optifine

**Comment by XFactHD** [comment]
Nice catch. Fixed in dev, next release is still some time away though.
