### ISSUE TITLE
Framed Slope Slab and Framed Elevated Slope Slab corners

### ISSUE THREAD

**Issue by DMSledge** [XFactHD/FramedBlocks#114]
Is there a ways to make corners for these blocks?

**Comment by XFactHD** [comment]
No, that's not possible at the moment.
I also don't really see how these would be useful, would you mind elaborating on that?

**Comment by DMSledge** [comment]
I have built a large four sided roof out of these before realizing that the corner blocks don't match.
![2022-06-03_14 40 52](https://user-images.githubusercontent.com/32973458/171949327-e781d885-9e5f-4d88-9865-87132b606b6b.png)

**Comment by XFactHD** [comment]
Ok, now I get what you meant and it makes so much more sense. That was a huge brainfart on my part. At first I thought you were talking about something like the Slab Corners but for Slope Slabs.

Will be added for the next release, though this will take some time.

**Comment by DMSledge** [comment]
That is awesome!

**Comment by XFactHD** [comment]
Please excuse the long waiting time, I have now finally added the first two blocks in the commit mentioned above.
Further blocks are coming.
"Next release" didn't quite work out as it should have :/

**Comment by XFactHD** [comment]
All blocks have been implemented and will be released with the next version.
