### ISSUE TITLE
Lighting Glitches on Slopes

### ISSUE THREAD

**Issue by imvaskel** [XFactHD/FramedBlocks#115]
Whenever you place blocks surrounding slopes, they get severe lighting glitches that make them relatively unusable for builds.
![image](https://user-images.githubusercontent.com/49348256/170535331-f7b76382-3ffe-4a49-968f-bb7ee3fcb5c7.png)
This occurs with optifine or without optifine.

**Comment by redgoblin88** [comment]
can confirm, in single player, when used as a diagonal wall where the "diagonal air blocks" are filled it still occurs.

comparing to macaw roofs (yes macaws adds the trim edges but its the slope and lighting were looking at) you can see one edge is "darker" than the others

versions
forge: 40.1.20
framedblocks: 5.1.1
macaw roofs: 2.1.2
(no optifine)

![2022-05-26_17 52 51](https://user-images.githubusercontent.com/13396472/170536409-be360107-cb22-4678-b6b9-d1a63529e10d.png)
![2022-05-26_17 48 07](https://user-images.githubusercontent.com/13396472/170536969-9e521e15-eae1-4ee8-9a8e-8670a753326f.png)

**Comment by imvaskel** [comment]
This does not seem to be resolved with the forge configuration option ``exprimentalForgeLightPipelineEnabled`` set to true.

**Comment by XFactHD** [comment]
I can't reproduce this issue at all with the `exprimentalForgeLightPipelineEnabled` setting enabled.
Try playing around with the Smooth Lighting setting in the video settings menu, someone who recently had an issue like this noticed that this would happen on the Minimal setting.
Also make sure to NOT use Notepad++ to edit the Forge config if you are editing the config while the game is running, there are some issues with NPP doing weird stuff when saving the file which leads to the changes being reverted.

A complete mod list would also be useful, please force a game crash by holding F3 + C for ten seconds and then upload the crash report on https://gist.github.com and post the link here.

**Comment by imvaskel** [comment]
Yep, works now. Seems to be related to Optifine (yeah i know optifine bad with modded but 1.16+ runs like shit on amd gpus lol).

**Comment by XFactHD** [comment]
Yeah, OptiFine breaks this because it forcibly disables the experimental light pipeline setting
