### ISSUE TITLE
FramedBlocks Lagging Game

### ISSUE THREAD

**Issue by TorterrasCrazyArse** [XFactHD/FramedBlocks#116]
Sometimes this mod when i have many other mods makes my game a lot more laggier than usual, could you please optimise the mod more for weak computers?

**Comment by XFactHD** [comment]
Your claim is not backed by any data whatsoever and therefore completely impossible to work with.
Apart from that, your past contributions on this platform show clear evidence of piracy, which I will not support any way, shape or form.
