### ISSUE TITLE
Issue with Optifine and Slopes causing a "Block Tesselation Error"

### ISSUE THREAD

**Issue by AntTheAntster** [XFactHD/FramedBlocks#12]
[crash-2021-04-06_18.15.16-client.txt](https://github.com/XFactHD/FramedBlocks/files/6266687/crash-2021-04-06_18.15.16-client.txt)
[crash-2021-04-06_18.24.49-client.txt](https://github.com/XFactHD/FramedBlocks/files/6266688/crash-2021-04-06_18.24.49-client.txt)

**Comment by XFactHD** [comment]
OptiFine is not supported
