### ISSUE TITLE
Unnamable containers.

### ISSUE THREAD

**Issue by DNDCrafter** [XFactHD/FramedBlocks#120]
I can name vanilla chests and place em and they have that name display at the top of the chest in GUI. But when I renamed the mods containers they didn't retain their new name.
![image](https://user-images.githubusercontent.com/65922144/173173081-afa7294a-8945-40b2-9220-2063f2cd2de7.png)

**Comment by XFactHD** [comment]
The modder's curse strikes once again, I completely forgot that you can do that :D

I'll look into adding this for the next update

**Comment by DNDCrafter** [comment]
quark adds blocks made from carrots called carrot crate and I wanted to use the barrel storage frame block and see the name on top
