### ISSUE TITLE
Create Contraption support

### ISSUE THREAD

**Issue by Tohricat** [XFactHD/FramedBlocks#122]
Thank you for fixing the Create contraption crash. Support for Create contraptions would be absolutely fantastic! At the moment, framed blocks revert back to their default texture when on a contraption.

**Comment by XFactHD** [comment]
Known issue as mentioned on the CurseForge page in the `Known Issues` section, I'm looking into it. I'll have to talk to the Create devs to see if there is anything I can do about this.

**Comment by XFactHD** [comment]
Create 0.5.0a added support for special model data and with a few minor changes on my side this will work properly with the next FramedBlocks version and Create 0.5.0a or later

**Comment by Nitwel** [comment]
Thank you for fixing this so quick! ❤️

**Comment by funAlways** [comment]
Framed doors seems to not be interactable in a create contraption, though texture works perfectly.

**Comment by XFactHD** [comment]
Will be fixed in the next version.
Next time, please open a new issue, that way the commit fixing the issue can be directly attributed to the issue.
