### ISSUE TITLE
Framed Ladders can't be climbed past trapdoors

### ISSUE THREAD

**Issue by WenXin20** [XFactHD/FramedBlocks#123]
When climbing the Framed Ladder, you are unable to climb past a trapdoor due to the hitbox size difference. 

Vanilla:

https://user-images.githubusercontent.com/12000593/174468029-6537ebb4-1d6c-48f4-b789-390b97b06b6c.mp4

Framed:

https://user-images.githubusercontent.com/12000593/174468055-ca0d7561-6a60-4d19-9668-8aec649a8706.mp4

**Comment by XFactHD** [comment]
Turns out that climbing up trapdoors above Framed Ladders is completely broken at the moment :D
It's a simple fix though.

**Comment by WenXin20** [comment]
Thanks :)
