### ISSUE TITLE
mod doesnt work for forge  41.0.64 minecraft 1.19

### ISSUE THREAD

**Issue by anonon222** [XFactHD/FramedBlocks#124]
the mod doen't load for this new version 
![obraz_2022-07-08_225339012](https://user-images.githubusercontent.com/108957089/178068793-d8bd262d-7afa-4936-90ad-32a1f50b4900.png)

**Comment by XFactHD** [comment]
41.0.64 brought a lot of sorely needed reworks of how certain client-side systems in Forge work, which broke the client-side functionality of FramedBlocks. I am working on updating FramedBlocks to 41.0.64 but it's going to take a few more days to make sure everything works as expected.

**Comment by XFactHD** [comment]
FramedBlocks 6.2.0 incorporates the breaking changes done in Forge .64 and .94 and will be available on CurseForge shortly.
