### ISSUE TITLE
Framed double slab doesn't exist (5.4.0)

### ISSUE THREAD

**Issue by funAlways** [XFactHD/FramedBlocks#127]
Playing on version 5.4.0 in a modpack and it seems framed double slab doesn't exist. Loaded an instance with just framed blocks and base forge and it still isn't there, so I'd assume it's just missing from the 1.18.2 version (5.4.0) .

**Comment by XFactHD** [comment]
The double slab is not missing, it just doesn't have a dedicated block. Instead, it's built the same way vanilla double slabs are built by combining two single slabs. Same thing applies to the double panel.

**Comment by funAlways** [comment]
Huh, it's a bit embarassing that I didn't think of that, thanks!

**Comment by anniemuse69** [comment]
@funAlways Thank you! I was struggling to make double slabs and double panels too.
