### ISSUE TITLE
Launcher error

### ISSUE THREAD

**Issue by MS9-Studios** [XFactHD/FramedBlocks#129]
Every time I go to start my game I get this error message
![image](https://user-images.githubusercontent.com/87773227/179436648-adef0161-d515-4675-aca6-b10ac48729ca.png)

This is my Crash Repor
[Crash Report.txt](https://github.com/XFactHD/FramedBlocks/files/9129379/Crash.Report.txt)
t

**Comment by XFactHD** [comment]
Update FramedBlocks to 6.2.0 for compatibility with Forge 41.0.94 and later
