### ISSUE TITLE
Question about a Panel Corner Pillar Block. 

### ISSUE THREAD

**Issue by Phalcon777** [XFactHD/FramedBlocks#132]
1. Thank you for the mod. 2. Maybe I am missing it. But is there any sort of Framed Double Vertical Stair. So like a panel and a corner pillar combined. So that you can put one block where the corner pillar would be and a different where the panel is. Of course other variants of that as well. I am building a mage tower and I am trying to make it slowly shrink in diameter. I am sure the coding and what not might be a headache as to how many variations to that there would be. 3. To save time there is a / block that you can put camos on both side of and it looks kinda like a slanted board when combined with another block I was wondering what about a pillar version of that so that it looks like the pillar centered and thinner. gives kind of a 2x4 look. Thank you for your time and hard work. <3

**Comment by XFactHD** [comment]
1. Thank you, much appreciated
2. That's unfortunately not going to happen. These kinds of shape combinations go too far into the realm of microblocks and supporting any possible combination of two or more blocks in the same block space is simply not possible with the way this mod works. My recommendation would be to look into things like Chisels & Bits for these kinds of special cases
3. The Framed Double Panel, which is built from two single Framed Panels the same way you make double slabs, exists. If that doesn't achieve the desired effect, then you need to elaborate on what you are envisioning.

**Comment by XFactHD** [comment]
Closing due to lack of feedback.
If you have any further questions regarding this, feel free to comment on this issue and I will reopen it if needed.
