### ISSUE TITLE
hmm wierd crashes for me says java failed and other stuff im using optofine with newer forge version

### ISSUE THREAD

**Issue by jackowacko14** [XFactHD/FramedBlocks#133]
how do i fix this

**Comment by jackowacko14** [comment]
btw it only crashes when i load into a world?

**Comment by XFactHD** [comment]
I can't tell you what's actually wrong since you have provided absolutely zero usable information.
However, my guess would be that it's simply caused by OptiFine being incompatible with the latest Forge version on both 1.18 and 1.19.
