### ISSUE TITLE
[Feature]: Framed Target

### ISSUE THREAD

**Issue by hahasand** [XFactHD/FramedBlocks#136]
### Describe the feature

Since the Target block is harsh and difficult to co-ordinate builds with, a framed version would be very useful. Also, you could use Carved Pumpkins as camo to create targets for a scarecrow shooting range. :D

I love this mod btw- it makes building so much more fun. Thank you for creating and maintaining it!

**Comment by XFactHD** [comment]
I really like this idea. Will be added in the next release.
