### ISSUE TITLE
[Bug]: intangibility can't be removed in 5.5.0

### ISSUE THREAD

**Issue by Rikka-Lyn** [XFactHD/FramedBlocks#137]
### Minecraft version

1.18

### Forge version

40.1.68

### FramedBlocks version

5.5.0

### Describe the bug

--Most blocks can be right-clicked with a Phantom Membrane (can be changed in the server config) to make them intangible, allowing you to move through them. To remove this, right click the block with a Framed Wrench while crouching.

In the latest version on port 1.18.2(mod version 5.5.0),use a Framed Wrench while crouching can only rotate it.I can't find anyway to remove the intangibility.

### How to reproduce the bug

Just try it.
I found this when I let the wall board intangible.

### Expected behavior

Anyway, intangibility should can be removed.

**Comment by XFactHD** [comment]
In 5.5.0 and 6.2.0, the Framed Wrench was changed to rotate the actual block and its previous features were moved to either the Framed Hammer or the new Framed Screwdriver. The removal of the intangibility was moved to the screwdriver and is now done by clicking it with that while crouching.

I completely forgot both mentioning it in the changelog as well as fixing the description. I'll fix the description on the mod page ASAP.
