### ISSUE TITLE
question on future updates

### ISSUE THREAD

**Issue by Godkiller12322222** [XFactHD/FramedBlocks#138]
### Question

HI, in the future updates will you add framed elevated corner slope slab?, i dont know how to describe the thing that im asking for so bare with me haha :P i've been using "Framed inverted double slope slab" to create a roof but when its time to place the corner, the corners that are in the mod pack doesnt fit the style, because the corner that are in the mod, are not sloped or elevated so they dont meet on the same height, so i was wondering if youll add something that works with it in the future or if there is a way to do it and i just cant come to make it hahaha,

**Comment by XFactHD** [comment]
These are already planned and will be coming in the future. See https://github.com/XFactHD/FramedBlocks/issues/114 for the relevant request.
