### ISSUE TITLE
Optifine Crash.

### ISSUE THREAD

**Issue by mbpod** [XFactHD/FramedBlocks#140]
### Question

Optifine for 1.18.2 does not work with forge versions over 40.1.57. And the latest 1.18.2 framed blocks version (5.5.0) requires forge version 40.1.68. Is there a way to still play with optifine?

**Comment by XFactHD** [comment]
Nope. If you need OptiFine at all costs, then you have to stay on 5.4.0. Another option would be to switch to Rubidium (performance) and Oculus (shaders), they should be a lot more compatible with other mods than OptiFine. If those cause a crash with FramedBlocks, then I'd be willing to try to fix those issues.

**Comment by MBP0** [comment]
> Nope. If you need OptiFine at all costs, then you have to stay on 5.4.0. Another option would be to switch to Rubidium (performance) and Oculus (shaders), they should be a lot more compatible with other mods than OptiFine. If those cause a crash with FramedBlocks, then I'd be willing to try to fix those issues.

I tried Rubidium and it caused minecraft to crash on launch.

**Comment by mbpod** [comment]
> Nope. If you need OptiFine at all costs, then you have to stay on 5.4.0. Another option would be to switch to Rubidium (performance) and Oculus (shaders), they should be a lot more compatible with other mods than OptiFine. If those cause a crash with FramedBlocks, then I'd be willing to try to fix those issues.

I tried Rubidium and it caused minecraft to crash on launch.

**Comment by XFactHD** [comment]
Without a crash report I have no way to tell you what the cause could be.

**Comment by mbpod** [comment]
I tried launching with Rubidium again, and now it did not crash. Probably it was a problem on my side.
