### ISSUE TITLE
[Feature]: Framed Big Buttons

### ISSUE THREAD

**Issue by Yizhouuu** [XFactHD/FramedBlocks#142]
### Describe the feature

![T8T3K57NF(4TEZG(AQAH{NR](https://user-images.githubusercontent.com/107225762/181407646-69119b46-6690-4e8c-94a0-1e7f80b5c0af.png)
Just looks like a pressure plate, but it can be pressed
So that players dont need to aim carefully to press the buttons :D
Also it would be a good decoration

**Comment by XFactHD** [comment]
Already planned, will be part of the next update.

**Comment by Yizhouuu** [comment]
> Already planned, will be part of the next update.

Nice!
