### ISSUE TITLE
[Bug]:  framedblock crashes the server when I place a block

### ISSUE THREAD

**Issue by Zetini** [XFactHD/FramedBlocks#143]
### Minecraft version

1.16 - UNSUPPORTED

### Forge version

mohistmc:36.2.39

### FramedBlocks version

2.16.1 

### Describe the bug

Every time I want to place a block the server closes me, I have no idea why.
Now I will send the error to see if you can help me, thanks.
[crash-2022-07-31_02.07.55-server.txt](https://github.com/XFactHD/FramedBlocks/files/9227982/crash-2022-07-31_02.07.55-server.txt)

### How to reproduce the bug

Placing a mod block

### Expected behavior

stop crashing the server

**Comment by XFactHD** [comment]
1. Duplicate of #93, #96, #103 and #117.
2. 1.16 support was dropped recently
3. Forge-Bukkit hybrid servers are impossible to support because they regularly deviate from the way the base game works, which is the cause of this crash
