### ISSUE TITLE
[Bug]: Framed sign is not considered as attached to the block it's on

### ISSUE THREAD

**Issue by Nulled-Pointer** [XFactHD/FramedBlocks#145]
### Minecraft version

1.18

### Forge version

40.1.68

### FramedBlocks version

5.5.0

### Describe the bug

Im playing with create (this may be a mod integration issue rather than a bug, im not sure) and when i try to glue a framed sign to a contraption it says that the blocks must be connected when the sign is placed _on_ the block

### How to reproduce the bug

Reproduction is simple, just play with create and framed blocks, place a framed sign on a block and try to glue them together
![image](https://user-images.githubusercontent.com/70151481/182627645-15030a91-c259-4d71-bbd6-fcd1bd6aaee9.png)

### Expected behavior

The sign should be attached to the block

**Comment by XFactHD** [comment]
Fixed in the next update.
