### ISSUE TITLE
[Feature]: Framed half door/sideways trapdoor

### ISSUE THREAD

**Issue by funAlways** [XFactHD/FramedBlocks#150]
### Describe the feature

Basically a 1 block tall door, or a trapdoor that opens sideways.

**Comment by XFactHD** [comment]
Simple addition, will be added for the next version after 5.6.0/6.3.0 respectively.
I just have to think of a good name :D

**Comment by funAlways** [comment]
Probably gate would be fine. 
And in terms of implementation, I hope it'll be versatile like trapdoor (doesn't require a block support/can float)
Thanks!

**Comment by XFactHD** [comment]
Gate sounds good, I'll go with that.
I'll make sure to keep it simple and unrestricted
