### ISSUE TITLE
[Bug]: Server Crashes whenever I right click a framed block

### ISSUE THREAD

**Issue by omartuareg** [XFactHD/FramedBlocks#151]
### Minecraft version

1.18

### Forge version

Latest

### FramedBlocks version

5.5.0

### Describe the bug

Whenever I right-click a framed block it crashes my game, for some reason its only on servers (bisect)

### How to reproduce the bug

Just right-clicking a framed block

### Expected behavior

Nothing

### Crash log

https://drive.google.com/file/d/1KbXJrnR1yDiZ3sN5BLMWF8raxCgY2o47/view?usp=sharing

**Comment by XFactHD** [comment]
Please try removing OptiFine, the version you are using is incompatible with the Forge version you are using. The only reason you are even able to play at all with that combination is that you are playing on a dedicated server and not singleplayer.

**Comment by XFactHD** [comment]
Closing due to lack of feedback.
If you decide to provide the necessary information at a later time, feel free to comment on this issue and I will reopen it if needed.
