### ISSUE TITLE
[Mod Support]: Supplementaries

### ISSUE THREAD

**Issue by Ayria** [XFactHD/FramedBlocks#154]
### The mod to integrate with

https://www.curseforge.com/minecraft/mc-mods/supplementaries

### Describe the feature

Supplementaries has an option to make any flower pot a hanging pot when placed under a chain. It doesn't work with the framed flower pot. It would be nice if it would!

Thanks!

**Comment by XFactHD** [comment]
I didn't even know that was a thing. I'll definitely look into supporting the hanging pot and hanging sign.

**Comment by XFactHD** [comment]
Turns out the hanging sign is a completely separate feature and has nothing to do with the vanilla sign, so I'll leave that alone.
The Framed Flower Pot will be hangable from ceilings, chains and ropes in the next version.
