### ISSUE TITLE
[Feature]: Vertical Double Slabs, Facades, Flower Pot Stuff

### ISSUE THREAD

**Issue by Ayria** [XFactHD/FramedBlocks#155]
### Describe the feature

_Vertical Double Slabs_: Check out the mod [Double Slabs](https://www.curseforge.com/minecraft/mc-mods/double-slabs). It allows for vertical (and facing any direction it seems) slabs. I wasn't sure you could integrate with them so instead I thought I'd post a feature request instead. This way you can have half a block outside your house be one type block and the inside be another without having two blocks thick walls!

_Facades_: Basically the floor panels but on walls. For instance, you can use them to give the appearance of a larger bookshelf wall without taking up the space for one! Or covering over create shafts, redstone stuff etc that require 1x1 spaces in your walls.

_Flower Pot Stuff_: I have NO idea if it's possible to do.. But Flower pots in Minecraft are lacking when it comes to modded minecraft. The ability to put anything that can be planted(even if it's weird and too big) in the pots would add wonderfully to being able to decorate. Seeds? Looks like the crop it grows fully into, break it? Get seeds back. Any tree, cactus, flower, etc. would be able to be viewable in a flower pot!

_Additional Flower Pot Stuff_: There use to be a mod called [modular flower pots](https://www.curseforge.com/minecraft/mc-mods/modular-flower-pots)(the mod isn't updating), and while the pots were big, they'd connect to make bigger pots! It would be cool to do this with normal pots. But not sure how possible it would be to recreate that.

I am not a mod maker, I have no idea how to do this stuff myself. I understand these are a lot of requests. I don't expect any of it. I however appreciate the ability to make such requests. Thank you.

**Comment by XFactHD** [comment]
*Vertical Double Slabs*: take a Framed Panel and combine it with a second one the same way you combine two slabs to make a double slab

*Facades*: the latest version includes the Framed Wall Board, which does exactly that.

*Flower Pot Stuff*: the Framed Flower Pot supports everything the vanilla flower pot supports. Adding new stuff to that is out of scope for this mod but if another mod adds those things, then they will be supported out of the box

*Additional Flower Pot Stuff*: adding something like that would totally be possible. It wouldn't use the normal pot though, it would be completely separate to make the implementation and usage simpler and cleaner. It would also just be a large and modular equivalent to the normal pot and wouldn't actually grow anything. Adding a modular planter could be a nice idea for a future add-on mod, though I would have to look into the feasibility of that first.

**Comment by Ayria** [comment]
Combine like in the crafting grid? And I should be able to use two different blocks on it? I.. Wait, what? Okay. I didn't even think to try it like that. I'm sorry lol

Is the latest version backported to 1.18.2 or are you only added support for newer things in 1.19? 

Thanks again for taking the time out to respond to this stuff.

**Comment by XFactHD** [comment]
I always add features to both MC versions I actively support, which are 1.18 and 1.19 at the moment. The only exception are certain cases where I am adding a new feature to an existing thing and the introduction of that feature would lead to issues for players using the existing thing.

**Comment by Ayria** [comment]
Understood! I was two versions behind apparently! Updating now. :) Thanks again!

**Comment by XFactHD** [comment]
I've decided against the modular flower pot for the time being, I already have too many plans and too little time and this is not trivial to implement properly
