### ISSUE TITLE
[Feature]: Framed Slope Panel Corner

### ISSUE THREAD

**Issue by Charismara** [XFactHD/FramedBlocks#156]
### Describe the feature

A corner would be nice :)

![image](https://user-images.githubusercontent.com/14293974/184226093-de0c4950-7df2-487d-8d3d-1cad0dd6d8b7.png)

**Comment by XFactHD** [comment]
Already planned but the corners for Slope Slabs and Slope Panels on the same plane will be coming first.
![2022-08-11_23 23 02](https://user-images.githubusercontent.com/11262040/184244810-168a43d7-64c7-4f42-8834-8f1b95a119b6.png)
