### ISSUE TITLE
Incompatible with Sodium-Forge

### ISSUE THREAD

**Issue by QPCrummer** [XFactHD/FramedBlocks#16]
I don't know what is wrong, but the people in sodium's discord said that this mod caused the issue. When I removed the mod, my modpack started working.

Here is the crash report
[crash-2021-04-23_15.54.03-client.txt](https://github.com/XFactHD/FramedBlocks/files/6367809/crash-2021-04-23_15.54.03-client.txt)

**Comment by XFactHD** [comment]
I assume you are talking about [this](https://github.com/Pannoniae/sodium-forge) Forge port of Sodium?

Can you provide screenshots of the conversation with the Sodium guys? From what I can see in the crash report, this is to blame on them for completely overwriting a method that I am injecting into which means there is basically nothing I can do.

**Comment by QPCrummer** [comment]
They didn’t really say much, just that this was the problem. All close it then.

**Comment by XFactHD** [comment]
I will look into disabling the inject when Sodium is loaded, though that will break the ghost block rendering.

**Comment by XFactHD** [comment]
I have now implemented a mitigation for this crash, though it does break the ghost block rendering as expected.
