### ISSUE TITLE
Does a Fabric port exist?[Question]: 

### ISSUE THREAD

**Issue by RoKat6** [XFactHD/FramedBlocks#164]
### Question

I've been looking for a mod like this for a little while (But for Fabric) and all the others are on older versions, so I just wanted to know if there's a Fabric version or a mod somewhat like this for Fabric?

**Comment by XFactHD** [comment]
I am not working on a Fabric port and don't plan to do so for the foreseeable future. See the [issues tagged with the "fabric" label](https://github.com/XFactHD/FramedBlocks/issues?q=is%3Aissue+is%3Aclosed+label%3Afabric) for my previous responses on this topic.
I'm also not aware of anything similar for Fabric, Google doesn't bring up anything as far as I can tell.
