### ISSUE TITLE
[Feature]: another type of double stairs block

### ISSUE THREAD

**Issue by ChocoIateRain** [XFactHD/FramedBlocks#165]
### Describe the feature

![2022-09-01_22 25 13](https://user-images.githubusercontent.com/112645677/188006325-9c04fc6d-5edb-4414-8198-230bbe591262.png)
I was hyped, when I read double stairs while looking at the block list, but I got a bit disappointed afterwards. Is it possible to add blocks like in the screenshot I shared? (I placed two blocks together to make it look like one)
Overall it's an amazing mod and I wish I discovered it sooner. xD

**Comment by XFactHD** [comment]
I have previously denied blocks like this but since a lot of people seem to want them and those blocks being fairly simple to implement, I'm going to give in and add them.
I just have to think of good names for them and get some other planned blocks done first.

**Comment by ChocoIateRain** [comment]
Thank you very much!!!

**Comment by XFactHD** [comment]
It's not done yet :)
I'll close the issue when the blocks are implemented

**Comment by ChocoIateRain** [comment]
Sorry about that.
As a suggestion, you could just call them two layered (vertical) stairs.

**Comment by XFactHD** [comment]
Not sure on that name since I want to distinguish the stairs made from a panel and a slab edge (bottom in your screenshot) from those made from a slab and a slab edge (top in your screenshot).

**Comment by ChocoIateRain** [comment]
Then maybe: slab and slab edge corner, panel and slab edge corner, panel and pillar corner 1 & 2 maybe add horizontal and vertical to it. I can't think of other names that can describe these blocks, since English is a foreign language for me.

**Comment by XFactHD** [comment]
Thank you for the suggestions. I'll have to think about the names some more, I want to keep them as short as possible but still as descriptive as possible.

**Comment by drakray** [comment]
I came here for this for a vertical need of 2 different steps
Is there an ETA, will it be available for neoforge 1.20.1?
Thank you for your good work :D

**Comment by XFactHD** [comment]
I don't provide any ETAs because they just create unnecessary pressure and expectations. I'm currently working on two other sets of blocks before I'll get to this. It will definitely be available in 1.20.1 though, that much I can guarantee.

**Comment by drakray** [comment]
no problem no pressure I understand completely
Thank you for your response :)
