### ISSUE TITLE
[Feature]: Water-logged pressure plates

### ISSUE THREAD

**Issue by AngleWyrm10** [XFactHD/FramedBlocks#169]
### Describe the feature

Here's a picture of my aquarium.

There's a door on the side, operated by a sand-colored FramedBlock pressure plate. From this angle it doesn't _look_ like it, but the pressure plate is actually an air block. When the fish get near it, they drop out of the water onto the pressure plate, opening the sliding glass door. This is harmless (the water can't get through) and kind of funny.

But walking through the tile causes unexpected water pressure against movement, and when I go up those stairs and open the door the air block can be seen as a cube of water surfaces.

![aquarium](https://user-images.githubusercontent.com/55937426/189644002-a6738a4b-375b-4300-bb8a-f0b872a79c17.png)

**Comment by XFactHD** [comment]
May be weird as it deviates from vanilla behaviour but I'll look into it.

**Comment by XFactHD** [comment]
I've decided to rework my initial solution. You will now have to manually switch the pressure plate to waterloggable by hitting it with a Framed Hammer. The main reason is that pressure plates in vanilla hold back water without breaking, which is a behaviour players may be using intentionally and I don't want to break their builds with this change.
