### ISSUE TITLE
Crashing with Optifine

### ISSUE THREAD

**Issue by wantedkeks** [XFactHD/FramedBlocks#17]
Hello,

while only having FramedBlocks-2.6.jar (and Forge) installed, Minecraft works fine.
Adding Optifine, my game crashs while placing the second framed block.

I tried it with those versions/variants:

Var 1
- Minecraft 1.16.5
- Forge 36.1.0
- FramedBlocks 2.6
- Result: OK

Var 2 (& 3)
- Minecraft 1.16.5
- Forge 36.1.0
- FramedBlocks 2.6 (or 2.5)
- Optifine HD U G7
- Result: "The game crashed whilst tesselating block model"

Var 4
- Minecraft 1.16.5
- Forge 36.1.0
- FramedBlocks 2.4
- Optifine HD U G7
- Result: OK

Is there a known issue with Optifine?

Attached: Minecraft Crash Window
![image](https://user-images.githubusercontent.com/43499536/115938567-69fce680-a49b-11eb-8c1a-82080c719ec4.png)

Attached: Minecraft Crash Report
[crash-2021-04-24_01.20.17-client.txt](https://github.com/XFactHD/FramedBlocks/files/6368500/crash-2021-04-24_01.20.17-client.txt)

If you need more information, please let me know!

**Comment by XFactHD** [comment]
OptiFine is not supported because there is no way to see what they break due to being closed source

**Comment by XFactHD** [comment]
I have implemented a mitigation for this crash, though it breaks the hiding of adjacent block faces between frames with glass or similar blocks.

**Comment by WenXin20** [comment]
Hello, I tested this on my server, but still got a crash when using v2.7-hotfix.
https://gist.githubusercontent.com/natanfudge/cb86bb458c8baaeb941b7cb27eee354d/raw/c759c57384d833afcd841c02fc5a2c90ef6c1cc3/crash.txt

**Comment by XFactHD** [comment]
Will look into it tonight

**Comment by WenXin20** [comment]
Thanks!

**Comment by S74RDU57** [comment]
> Hello, I tested this on my server, but still got a crash when using v2.7-hotfix.
> https://gist.githubusercontent.com/natanfudge/cb86bb458c8baaeb941b7cb27eee354d/raw/c759c57384d833afcd841c02fc5a2c90ef6c1cc3/crash.txt

Can confirm, also getting this crash. Optifine :)

[I also assume this is related https://github.com/XFactHD/FramedBlocks/issues/20#issuecomment-827934327]

**Comment by WenXin20** [comment]
It's already been fixed with v2.7.1
