### ISSUE TITLE
[Feature]: Half blocks able to place under/on top of other half blocks inside one block space

### ISSUE THREAD

**Issue by Ayria** [XFactHD/FramedBlocks#172]
### Describe the feature

For instance, a half pillar under a half slab to form a short T shape, allowing it to be a full block.

I bet you've added this and I haven't figured out how to do it.

**Comment by XFactHD** [comment]
Combining arbitrary blocks within a single block space will not happen. Both the existing and the upcoming double blocks are deliberately selected and they have specific code written for them so they work properly with the detailed face culling (hiding faces between two neighboring blocks when their shapes match).

If you need arbitrary combinations of simple shapes like your example, then you are better off with a multipart mod or something like Chisels & Bits.

**Comment by Ayria** [comment]
Understood, thanks for taking the time. I really love this mod. I hope you keep it up ^^
