### ISSUE TITLE
[Bug]: framed blocks has encountered an error durring the common_setup phase

### ISSUE THREAD

**Issue by Lightning267** [XFactHD/FramedBlocks#173]
### Minecraft version

1.18

### Forge version

40.1.80

### FramedBlocks version

5.7.0 / 5.6.0 / 5.5.0

### Describe the bug

Can't even finish booting the game

### How to reproduce the bug

Open the game

### Expected behavior

The game should start.

### Crash log

https://gist.github.com/Lightning267/6ca8333ba5919e85012a6fe9b4e75e44

**Comment by XFactHD** [comment]
Duplicate of #170.
The fix for this will be released with the next big update. For now, make sure to also remove Flywheel when you remove Create.
