### ISSUE TITLE
[Bug]: framed blocks used in sophisticatedstorage display feature causes crash.

### ISSUE THREAD

**Issue by GreenForzeGaming** [XFactHD/FramedBlocks#174]
### Minecraft version

1.18

### Forge version

forge-1.18.2-40.1.74

### FramedBlocks version

FramedBlocks-5.6.0

### Describe the bug

when put in the item display feature of sophisticatedstorage the game crashes

### How to reproduce the bug

use the display feature of sophisticatedstorage too display framed blocks

### Expected behavior

not too crash XD

### Crash log

https://gist.github.com/GreenForzeGaming/c578f5b44de9a79d06687a23b0cd3adf / https://gist.github.com/GreenForzeGaming/85ff9961c48ccef214d4632872541f1b

**Comment by GreenForzeGaming** [comment]
might be with actuall item frames aswell as the feature pritty much mimics that

**Comment by XFactHD** [comment]
That's a derp on my part. Item frames aren't affected by this because they work substantially different under the hood.
I'll release a hotfix for 1.18 and include it in the next big update for 1.19.

**Comment by GreenForzeGaming** [comment]
Dude, youre a legend, fixed an issue within a few hours!?!. Youre the single handadly best dev modder ive ever met, thank you so so much, my wife got so upset she crashed the game twice, now shes excited its fixed XD so thank you!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
