### ISSUE TITLE
[Feature]: Simplify crafting of framed blocks?

### ISSUE THREAD

**Issue by Martijnpold** [XFactHD/FramedBlocks#178]
### Describe the feature

It would be cool if there would be a better way to craft framed blocks into the right shapes. Maybe something similar to the Chisel mod, where you right-click on a saw item and input base Framed Blocks and allow you to just "saw" them into the right shape directly. (Similar to a stonecutter). Would probably make the creation and building process with Framed Blocks a much smoother experience.

Maybe even optionally allowing it to convert back to regular framed blocks, so you don't end up with 15 slightly different framed blocks in your storage.

**Comment by XFactHD** [comment]
Something like the stone cutter sounds like a really interesting idea. No 100% confirmation but I'll try to come up with something cool, user-friendly and automateable.

And yes, I totally agree with you that the amount of recipes and the crutches necessary in some of them is getting a bit ridiculous :D

**Comment by Martijnpold** [comment]
Haha, If I had more modding experience I'd try to PR something, sadly I mainly know spigot, so I don't trust my code to be clean enough for someone else's repo yet.

**Comment by GreenForzeGaming** [comment]
make it a stick printer, it can also read from chests beside the block
basickly it uses a certen amount of sticks for each recepie. no need for external items just sticks and having a chest full of sticks on the side would let you mass produce instead of having a full inventory with diferent items. and for specific recepies. there could be a slot in the gui for specal framed blocks, lets say the rail. would be using rails in that specal slot.
sticks are used in top slotwhile specal slot is below it for specal framed blocks that needs an function item. this way we would reduce recepies into a scrollable gui. i could make a visual exploanation aswell if needed

**Comment by XFactHD** [comment]
I kinda like the idea of using the raw materials instead of from the Framed Cube. The only issue is that it wouldn't allow converting between different shapes.

I'll have to think a lot more about how best to do this. I want to come up with something that makes manual crafting less annoying while also being as simple as possible to automate. I don't want to force the player to build one of these crafting machines per shape they want to automate.

**Comment by GreenForzeGaming** [comment]
I have a ui idea i could paint up

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by XFactHD** [comment]
Sure, go for it, more ideas can't hurt.

**Comment by GreenForzeGaming** [comment]
something like this would make it SOOOO Simple
![image](https://user-images.githubusercontent.com/62345403/194922331-497468e4-3931-47a1-b366-276ee6c9b220.png)

**Comment by GreenForzeGaming** [comment]
list on right shows what blocks exist for you too make in the crafter. the big square is for better view of the block you wana craft. the top item box is for main item "sticks" and bottom box for specal ingredients lets say framed tnt would use sticks top and tnt bottom.

**Comment by GreenForzeGaming** [comment]
this way automation can be implemented aswell. the big box is obviously your picked block. and when fed ites it can use or if the crafter picks itself from agecent chests, it would only craft the block that has been picked in the big frame. it could easely be toggeled
![image](https://user-images.githubusercontent.com/62345403/194923728-20a4bd41-d7af-43f7-b78a-581731f6d50e.png)

**Comment by XFactHD** [comment]
This is basically what I would have gone for but with three input slots: sticks and planks in the first two to mirror the resources needed to make the Framed Cube and any optional additional stuff in the third slot.

I'm not really sold on the idea of an automation toggle though and I may even decide to separate the automatic and manual crafting machine.

**Comment by Martijnpold** [comment]
That GUI draft is essentially what I meant yeah, I originally referred to the stonecutter or chisel mod, the chisel mod GUI looks like this: 
![image](https://user-images.githubusercontent.com/19569988/195363185-b63644b2-45fa-4f00-bf4a-3886ac38a4b4.png)

The mod even has some extensions for automating, the following 2 pictures are some examples of how other chisel based mods handled it:
![image](https://user-images.githubusercontent.com/19569988/195363442-6c908c90-4b69-48c9-ae0c-090d121047ad.png)
Simple GUI where the wanted output block is put in the bottom and the base block is automatically converted.

![image](https://user-images.githubusercontent.com/19569988/195363666-5016f0a1-ed61-49a4-bff4-d5aae6ea245e.png)
Similar idea but would allow for an item that uses durability while crafting.

Alternatively the crafting recipes could also remain, allowing automation through auto-crafting, but giving the saw as a manual alternative when converting a lower quantity of framed blocks.

**Comment by XFactHD** [comment]
The Stonecutter as well as Chisel and Auto Chisel UIs were also the first ones that came to my mind for this.

My plan at the moment is to add something very similar to the stonecutter but with a larger interface and a search bar for the manual crafting and something like the Auto Chisel from the original Chisel mod but with configurable energy requirement for the automated crafting (even though I would have liked to avoid the need to make an automatable machine per variant).
The existing crafting recipes will very likely remain for people who prefer to cram the crafting recipe of every single variant into their AE2 molecular assembler crafting clusters without having to build an automatable version of this new crafter for each variant.

**Comment by XFactHD** [comment]
Finally got an implementation I'm happy with. The new crafting system will be included in the next update.
