### ISSUE TITLE
all the framed rails.

### ISSUE THREAD

**Issue by GreenForzeGaming** [XFactHD/FramedBlocks#180]
### Describe the feature

 idk why this havent been added yet XD but looks wierd having slopes with powered rail thats hollow

**Comment by XFactHD** [comment]
Nobody asked yet, I guess 😄.

**Comment by GreenForzeGaming** [comment]
Makes sence 🤣

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
