### ISSUE TITLE
More pieces that fit together 

### ISSUE THREAD

**Issue by Ivybug** [XFactHD/FramedBlocks#181]
### Describe the feature

More block parts that fit together in the same block, the way the framed panel does. For example, framed vertical stairs and framed corner pillar. Or, more framed blocks to cover these different kinds of shapes.

**Comment by XFactHD** [comment]
The combination of the Framed Vertical Stairs and Framed Corner Pillar already exists in the form of the Framed Double Stairs. Please make sure you are using the latest version.

More double blocks are already planned. Feel free to suggest other specific shapes you can think of.

**Comment by Ivybug** [comment]
Ok, then my suggestion is backporting that.

**Comment by XFactHD** [comment]
It's available since 6.1.0 for 1.19 and 5.4.0 for 1.18 which were released on June 27.

Support for Minecraft versions older than 1.18 has been dropped as supporting more than two Minecraft versions is not feasible. As such those versions will not get backports of new features.

**Comment by SandWoodJones** [comment]
It would be great to stack slab edges on top of each other without leaving a gap:
![image](https://user-images.githubusercontent.com/35671374/197370031-7f12c6c7-92e3-452f-91a4-d168b141cc86.png)

**Comment by XFactHD** [comment]
Sounds reasonable, I'll add that to the TODO list.
