### ISSUE TITLE
[Feature]: create sliding doors

### ISSUE THREAD

**Issue by GreenForzeGaming** [XFactHD/FramedBlocks#184]
### Describe the feature

the train doors on create would be cool to have if create is in the players mod list. 
i dont know how possible that is

**Comment by XFactHD** [comment]
I'll look into it (once I've finally had some time to properly play with the Create train update), no promises though.

**Comment by SrRapero720** [comment]
i am dissapoinmentN'T with that
a cool/wanted thing is the capacity to have cool custom sliding doors.

**Comment by tizu69** [comment]
> I'll look into it (once I've finally had some time to properly play with the Create train update), no promises though.

@XFactHD Possibly also locked variants? The Create doors are great, but I can't really use them to build elevators

**Comment by XFactHD** [comment]
I've looked into this again and, while I would absolutely love to add this, it is effectively impossible to do so at the moment as it would require duplicating several hundred lines of code from Create and the extensive internal changes required to make this possible without code duplication are unjustifieable at the moment.

**Comment by SrRapero720** [comment]
a sad day
