### ISSUE TITLE
[Feature]: more deco ideas. 

### ISSUE THREAD

**Issue by GreenForzeGaming** [XFactHD/FramedBlocks#186]
### Describe the feature

just like my previous idea with a hollow block for a chimney, id love a pot. big pot too put 5 flowers/grass in. (each corner and then middle) obviously placed based on what side you watch while placing.

and mob heads. id love to have tiny versions of blocks displayed! tiny TNT

**Comment by XFactHD** [comment]
I'm honestly not sure how well a large flower pot would work. I'll look into it though.

The Framed Half Pillar is basically identical to a mob head and works exactly like a "Framed Mob Head" would work.

**Comment by GreenForzeGaming** [comment]
It can be placed diagonaly?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by XFactHD** [comment]
No, that's basically the only thing it can't do. I'm not sure it's worth adding a new block just for that.

**Comment by GreenForzeGaming** [comment]
Id love it. Lol cool if it could be made into a chest aswell

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by XFactHD** [comment]
I'll think about it.
Making it (or any other Framed Block) look like a vanilla chest is impossible though because the chest is rendered completely differently than "normal" blocks.
