### ISSUE TITLE
[Bug]: Create Trains placement block

### ISSUE THREAD

**Issue by SrRapero720** [XFactHD/FramedBlocks#187]
### Minecraft version

1.18

### Forge version

40.1.80

### FramedBlocks version

 FramedBlocks-5.8.0.jar

### Describe the bug

When a framed slope become a contraption (any contraption) changes the framedblock angle and finally when get placed like a block get placed like initial angle/position

CARRIAGE CONTRAPTION
![image](https://user-images.githubusercontent.com/29090346/196019673-f9507396-6d6a-4093-b2bb-b25caf90421f.png)

STATIONATY CONTRAPTION (not sponsored by Screenpresso, never download)
![2022-10-16_00h33_59](https://user-images.githubusercontent.com/29090346/196019858-6e437b30-083e-4433-956d-9abaff572c71.gif)

### How to reproduce the bug

Make framedslope a contraption
rotate contraption
make a contraption back to block
framedblock get placed "inverted"

### Expected behavior

changes rotation with the contraption after get placed like a block

### Additional details

No more details... just a sad arm

![2022-10-14_18h18_29](https://user-images.githubusercontent.com/29090346/196020078-dfc9a0a9-7781-43f7-9043-36163ea7ce03.png)
![2022-10-14_18h19_20](https://user-images.githubusercontent.com/29090346/196020080-3d4771e5-5434-4657-bdd6-c2ca0f1a46cd.png)

**Comment by XFactHD** [comment]
Good catch, I missed a small detail in the rotation code. I'll make sure this works fine on all blocks and will have a fix for this in the next version.

**Comment by XFactHD** [comment]
I've gone through all blocks to make sure they rotate properly. Unfortunately this fix will only apply to rotations around the vertical axis like they would happen in the case of the train example. Rotations around any other axis like in your second example with the crank will still be broken. For now, there is nothing I can realistically do about this, I will look into further solutions though in the hopes of getting this fully fixed at some point.
