### ISSUE TITLE
[Bug]: Crash When Putting Block Into Framed Trapdoor

### ISSUE THREAD

**Issue by SesameSlayer** [XFactHD/FramedBlocks#188]
### Minecraft version

1.19

### Forge version

43.1.1

### FramedBlocks version

6.5.1

### Describe the bug

When I masked a framed trapdoor with an Ochrum Pillar (Create mod), the game crashed. Additonally, entering the world crashes the game. The crash log claims this is due to it being unable to find the trapdoor's location.

### How to reproduce the bug

1: Use all mods referenced in crash log
2: Place framed trapdoor
3: Fill the trapdoor with Ochrum Pillar from Create
4: Game crashes

### Expected behavior

Would not crash, and would instead fill the trapdoor frame with an Ochrum Pillar.

### Crash log

[crash-2022-10-21_16.07.09-client.txt](https://github.com/XFactHD/FramedBlocks/files/9843084/crash-2022-10-21_16.07.09-client.txt)

**Comment by XFactHD** [comment]
I'll try to get a fix for this out as soon as possible, for now you can use version 6.5.0 if the changes in 6.5.1 don't matter to you.

**Comment by XFactHD** [comment]
Please excuse the long wait. The fix for this is now finally up on CurseForge, currently under review and should be available shortly.

**Comment by SesameSlayer** [comment]
thanks!
