### ISSUE TITLE
[Feature]: Connectable Slab Corners

### ISSUE THREAD

**Issue by SesameSlayer** [XFactHD/FramedBlocks#189]
### Describe the feature

It would be nice if the slab corners could be connected. That would allow you to make any combination of 1/8th blocks, and would allow things like artificial stair corners. It would also allow customization of the texture of each 8th of the block.

**Comment by XFactHD** [comment]
Combining arbitrary shapes or arbitrary amounts of shapes in a single block is not feasible and will not be added to FramedBlocks.
If you need to be able to combine an arbitrary amount of textures and shapes in a single block, then a mod like Chisels & Bits is better suited for those cases.
