### ISSUE TITLE
[Bug]: Crash on load

### ISSUE THREAD

**Issue by Saereth** [XFactHD/FramedBlocks#193]
### Minecraft version

1.19

### Forge version

40.1.38

### FramedBlocks version

FramedBlocks-6.5.1

### Describe the bug

Added the mod to my instance and it immediately crashes on launch now

### How to reproduce the bug

1.19.2 instance with forge 40.1.38 

### Expected behavior

to not crash

### Crash log

https://gist.github.com/Saereth/bc4f21a14bb9ee99a6962c9ac47b11f6

**Comment by XFactHD** [comment]
Please put the full debug.log log file on gist.github.com, the crash report unfortunately doesn't contain the actual issue in this case.

**Comment by XFactHD** [comment]
Please put the full debug.log log file on gist.github.com, the crash report unfortunately doesn't contain the actual issue in this case.

**Comment by Saereth** [comment]
Np, here you are, https://gist.github.com/Saereth/f692f19eab84e603b2bd7e49315b96cd
If there is anything else I can get for you to help debug let me know. Thanks!

**Comment by XFactHD** [comment]
This is an incompatibility with the [Waterlogged Redstone](https://www.curseforge.com/minecraft/mc-mods/waterlogged-redstone) mod. I'll open an issue with them so they can fix this.
For now, you can either remove Waterlogged Redstone or downgrade FramedBlocks to 6.5.0 (assuming the minor changes in 6.5.1 don't matter for you).

I'll keep this issue open until I have received a response from the author of Waterlogged Redstone.

**Comment by Saereth** [comment]
Ill remove waterlogged redstone for now and track their update progress later, ty for the quick response

**Comment by XFactHD** [comment]
The issue has been fixed in Waterlogged Redstone by removing their modifications to the pressure plate. Their latest version as of 3 hours ago works fine with FramedBlocks.
