### ISSUE TITLE
[Feature]: Functional Grass Camo

### ISSUE THREAD

**Issue by Jophire** [XFactHD/FramedBlocks#194]
### Describe the feature

Grass camo applied to blocks with a flat top(upper slab, full blocks, upside down stairs) should allow for plants to be grown on it(grass,flowers,saplings).

If this is already a feature then, the ability to designate what blocks count as grass.

**Comment by XFactHD** [comment]
A quick test suggests that this is fairly simple to implement. I'll make sure to include this in the next version.

**Comment by XFactHD** [comment]
I have now implented this such that any full-size face can support the plantable things that are supported by the applied camo as long as said camo is in the `framedblocks:camo_sustain_plant` block tag. By default this tag includes the following:

- `minecraft:dirt` tag - resolves to Dirt, Grass Block, Podzol, Coarse Dirt, Mycelium, Rooted Dirt, Moss Block, Mud and Muddy Mangrove Roots
- `minecraft:sand` tag - resolves to Sand and Red Sand
- `minecraft:nylium` tag - resolves to Crimson Nylium and Warped Nylium
- Soul Sand
- Soul Soil

**Comment by Jophire** [comment]
Thank you for adding the ability to plant crops/saplings/plants on full-sized faces.

Now to be a pest: can camo blocks support bonemeal based on the camo? Trying not to hand plant grass over a couple hundred square meters.

**Comment by XFactHD** [comment]
I think that would cause more issues for user experience than it would solve. In my opinion, you would be better off with a mod that allows you to craft grass blocks.
