### ISSUE TITLE
[Bug]: Using framed blocks on Arclight server core crashes server (I see 1.16 is not supported but maybe u'll take a glance)

### ISSUE THREAD

**Issue by yuompioka** [XFactHD/FramedBlocks#196]
### Minecraft version

1.16 - UNSUPPORTED

### Forge version

36.2.39

### FramedBlocks version

2.16.1

### Describe the bug

Using framed blocks (placing actually) crashes the server

### How to reproduce the bug

- Run 1.16.5 [Arclight](https://github.com/IzzelAliz/Arclight) server, put FramedBlocks in `mods` folder
- Join the world, try to place any framed block

### Expected behavior

Block being placed, no crash

### Additional details

Your mod is very valuable for my server community, so I have to try asking you solve the issue
It would be nice if you find the time, but no worries if not, we'll be ok with that

### Crash log

https://gist.github.com/yuompioka/5723070aae4d8fc0532e318c62c3a635

**Comment by XFactHD** [comment]
Apart from 1.16 not being supported anymore, there is nothing I can realistically do about this without risking to break the mod for players using a plain Forge server or server software that is fully compliant with it (which Arclight is not).

If you want to have this fixed, either update to a more modern version (1.17 or newer) where the system that is crashing works completely differently or complain to Arclight (or basically any other Bukkit-Forge hybrid server) that they are breaking basic assumptions about the vanilla game, like in this case where the `TileEntity` of a block is not placed in the world within the same tick it was created in.

**Comment by doarlock** [comment]
@XFactHD I have the same issue but on Arclight 1.18.2
So had reading this post there will not be solution? 

I already reported on Arlight's github but they response the next: 

_This should report to FramedBlocks side with these information:
The level in BlockEntity can be null. For the onLoad implementation, forge actually provide a onLoad callback in IForgeTileEntity._ 

Here is the post: https://github.com/IzzelAliz/Arclight/issues/746

**Comment by XFactHD** [comment]
This issue can't be fixed by me without removing an important feature or risking to break it on platforms where it currently works fine. Their suggestion is also a bit misinformed as I tried exactly that when I initially implemented the system that is impacted by this issue and ran into severe problems.
