### ISSUE TITLE
[Feature]: Explosion resistance

### ISSUE THREAD

**Issue by Ingraved** [XFactHD/FramedBlocks#199]
### Describe the feature

a way to increase explosion resistance of the current camo'd frame, maybe with obsidian?

**Comment by XFactHD** [comment]
Framed Blocks currently copy the explosion resistance from the applied camo.
Applying some kind of "obsidian reinforcement" would be a good option to increase the explosion resistance and durability, I just need a good way to visualize it (at least on the bare frame). I'll look into adding this

**Comment by Ingraved** [comment]
obsidian in the offhand with a tool in main hand to apply?

**Comment by XFactHD** [comment]
I would prefer a dedicated item for two reasons:
1. Placing a block in the off-hand already has a another functionality in FramedBlocks: immediately applying that block as a camo
2. If I'm adding a new tool anyway (adding that functionality to existing tools would be bad for discoverability and usability), then I might as well just make a dedicated reinforcement item

The main issue for now is the visualisation though, the rest is fairly straightforward.

**Comment by XFactHD** [comment]
The implementation I went for is pretty simplistic: the reinforcement provides the block with obsidian-level explosition resistance and can be removed by right clicking with any pickaxe-type tool that can break obsidian blocks. The status is indicated by showing a HUD when looking at a block with the reinforcement item in the main hand.
