### ISSUE TITLE
[Feature]:  Downport all current blocks to a new 1.16.5 version

### ISSUE THREAD

**Issue by Tbird2005** [XFactHD/FramedBlocks#200]
### Describe the feature

i really need those god damn wall boards and i cant fucking get them in 1.16.5 AND I NEED THEM

**Comment by FinnT730** [comment]
Isn't 1.16.5 out of... support for this mod?

**Comment by XFactHD** [comment]
Support for 1.16 has been dropped almost 5 months ago and will not get any more updates, especially not content updates.
Apart from that, multiple systems have been rewritten in the meantime, making a backport extremely tedious.
