### ISSUE TITLE
[Bug]: Face Culling

### ISSUE THREAD

**Issue by TheCosmicNebula** [XFactHD/FramedBlocks#202]
### Minecraft version

1.19

### Forge version

41.3.47

### FramedBlocks version

6.5.0

### Describe the bug

When using the vertical stairs, and locking them into the corner mode, then placing a framed slab edge next to it, the faces stop rendering when setting the blocks on both to any solid block.

![image](https://user-images.githubusercontent.com/33880828/200184114-89008ca2-cbac-4406-abba-3498d928fd16.png)
![image](https://user-images.githubusercontent.com/33880828/200184132-4b5b78b1-928d-4bf8-9581-c32c5ec0a372.png)
![image](https://user-images.githubusercontent.com/33880828/200184188-d523eeb6-9cf2-4d50-a18d-740c3644e2a7.png)

### How to reproduce the bug

1. Place vertical stairs:

![image](https://user-images.githubusercontent.com/33880828/200184213-702b3f92-068b-443f-b082-3f417ebd82a4.png)

2. then place horizontal stairs next to them to achieve this state:
![image](https://user-images.githubusercontent.com/33880828/200184227-a9e6d5e9-49f9-4a7a-a6af-dce915649367.png)

3. Next place Framed Slab Edges like this:
![image](https://user-images.githubusercontent.com/33880828/200184263-bfe9d15f-a143-4f5a-9f7f-fa5d38884c45.png)

Now set their texture to any solid block and faces get culled and stop rendering:
![image](https://user-images.githubusercontent.com/33880828/200184305-e84daf8a-44a7-4e94-9870-b0dc186f9c23.png)

### Expected behavior

The upper faces that are not directly adjacent to the Framed Slab Edges should not cull.

### Additional details

Using lots of other mods and Rubidium as an OptiFine replacement.

**Comment by XFactHD** [comment]
Nice catch, I derped the cull-face assignment on those faces.
Since I haven't gotten around to actually releasing the next version just yet, I'll include the fix there.

**Comment by TheCosmicNebula** [comment]
No problem! Awesome mod by the by!

**Comment by XFactHD** [comment]
Thank you, I'm happy you are enjoying it.
