### ISSUE TITLE
[Feature]: Block tooltips for JEI search

### ISSUE THREAD

**Issue by tizu69** [XFactHD/FramedBlocks#206]
### Describe the feature

<sup>In case you don't know, JEI can search tooltips (and afaik that's even on by default, at least in every modpack I played).</sup>

I'd love to see FramedBlocks add tooltips on some framed blocks (especially the ones that have rotated variants (eg. slabs and panels) or are often referred by something else) that simply refer to the block with other names. Examples:

- Framed Panel: `Framed Vertical Slab` (common name), `Framed Slab` (rotated version)
- Framed Floor Board: `Framed Carpet` (common name), `Franed Wall Board` (rotated version)

...

---
The normal framed cube should also have a tooltip saying the stuff that some don't know because they don't read the CF description.
```
Click with Glowstone dust onto any Framed block to make it glow.
Click with Fluid container onto any Framed block to make it look like the fluid.
Click with Framed Hammer to remove camo, click with empty fluid container to remove liquid.
```

**Comment by XFactHD** [comment]
While I can kinda see the general issue, item tooltips are neither dictionaries nor are they full-features manuals. The main issues with this are:

- Alternative names are very subjective, I've seen a tone of different names for a few blocks and adding all of those to the tooltip just makes the tooltip fairly large
- Adding a full manual to the tooltip would make the tooltip absurdly large and adding it to a single block is almost useless
- If people don't read the CF description, then they won't read a random tooltip hidden on a single block

If anything, I would add a manual with something like Patchouli, but adding tons of info (especially extremely subjective stuff like alternate names) to item tooltips is not happening.
