### ISSUE TITLE
[Bug]: Fancy Rail Slope doesn't update glowing blockstate

### ISSUE THREAD

**Issue by WenXin20** [XFactHD/FramedBlocks#207]
### Minecraft version

1.19.2

### Forge version

43.1.47

### FramedBlocks version

6.6.1

### Describe the bug

When the Fancy Rail Slopes are right-clicked with glowstone, the `glowing` blockstate doesn't update to `true`.
I use the Shimmer mod to give bloom to the blocks by checking if the `glowing` blockstate is `true`.

### How to reproduce the bug

- Place a Fancy Rail Slope
- Right-click with Glowstone
- Check blockstate

### Expected behavior

- The blockstate should change to true

**Comment by XFactHD** [comment]
Oops, missed a small detail, fix incoming but since it's non-critical I'll only release it in the next big update due in 3 weeks or so.

**Comment by WenXin20** [comment]
Sounds good, thanks!

**Comment by XFactHD** [comment]
Since I need to release an update for a crash fix, this fix is now going live as well. The new version is currently pending approval.
