### ISSUE TITLE
[Feature]: A Half-Slab + Half Edge Slab Stair Block

### ISSUE THREAD

**Issue by SpokenWig620933** [XFactHD/FramedBlocks#209]
### Describe the feature

I want a Slab + Edge Slab block put together to form a stair block.
![2022-11-13_18 06 54](https://user-images.githubusercontent.com/49125888/201549418-102a71e0-741c-4526-94e0-09f332f3e302.png)
![2022-11-13_18 08 08](https://user-images.githubusercontent.com/49125888/201549422-3b89293e-c0f0-48dd-9436-b6d0331e06f0.png)
 
I made this example with Chisel & Bits, but their blocks get laggy quickly because of the amount of data they need to store in each block, so I want a block that will work from your mod.

**Comment by XFactHD** [comment]
This kind of block is already planned, I'm still looking for a good name though. Keep an eye on https://github.com/XFactHD/FramedBlocks/issues/165 to follow the progress.
