### ISSUE TITLE
[Feature]: Upside down Slope Slab

### ISSUE THREAD

**Issue by Rackzo** [XFactHD/FramedBlocks#210]
### Describe the feature

![2022-11-14_04 57 12](https://user-images.githubusercontent.com/7839900/201572769-f408f3b1-6154-447c-9fb1-cc5c35720fce.png)

Currently (at least in 1.18) there's no way to bridge inverted double slope slabs with the regular slope slab unless I'm missing something, an upside down slope slab would fix this

**Comment by Rackzo** [comment]
Nvm this, I just pressed shift, did not know that was a feature

**Comment by XFactHD** [comment]
No worries. I really need to document stuff like this better as currently some of these things are only mentioned briefly in the block list on the CurseForge page. I haven't decided on a documentation solution yet though
