### ISSUE TITLE
[Feature]: One-way glass/camouflage block request

### ISSUE THREAD

**Issue by tanyan-tanyan** [XFactHD/FramedBlocks#212]
### Describe the feature

Hi, this is a slightly unorthodox suggestion, but the gist is that I would like to request a camouflage block that lets you see through it only one-way, just like in interrogation rooms.

This one-way camouflage block was in the Voltz modpack a long time ago, here's a wiki page that explains how it works: [https://voltz.fandom.com/wiki/Camouflage](url)

I'm not sure about the render limitations but I'm curious if it'd be possible to set up the camouflage block as if it was a double block, except it detects if the texture is transparent/semi-transparent and omits the render of the solid texture from that one side.

**Comment by XFactHD** [comment]
I'll look into the feasibility of this but it may not be possible with the internal architecture of FramedBlocks. For now I'll put this on the list of things to ponder over at some point since there are a bunch of other features still waiting to be implemented.

**Comment by XFactHD** [comment]
I've decided to go with a very simple implementation where hitting a side with a Framed Wrench will set that side as the see-through side and replace the solid block with a tinted glass window (seemed like the most fitting texture to me). Hitting the block with a Framed Wrench while crouching will make all sides opaque again. By default the see-through side can only be set by the player who placed the block but this restriction can be disabled in the server config.

**Comment by tanyan-tanyan** [comment]
I just wanted to say I was away from modpacks for a while and accidentally ran into this block in JEI today, while checking out Direwolf.
I have to say I'm beyond elated to see this addition in the mod now. Thank you so much, you made my day <3

**Comment by XFactHD** [comment]
You're welcome. I'm happy you like what I made out of your suggestion
