### ISSUE TITLE
[Feature]: Light Blocks

### ISSUE THREAD

**Issue by Xaikii** [XFactHD/FramedBlocks#214]
### Describe the feature

Would it be possible to add Light Blocks like [these](https://www.curseforge.com/minecraft/mc-mods/additional-lights)? (Maybe as a ModCompat)
Torches are neat and all, but "blocky" lights would really help and look good in some builds (Potentially even with colored Flames(still emitting normal light, no albedo)).
![image](https://user-images.githubusercontent.com/25128633/203289349-c152a463-2de7-4c88-998b-999ca37cbc22.png)
![image](https://user-images.githubusercontent.com/25128633/203289439-db6813a7-6e9e-443b-9da4-1106b86e6d9e.png)

**Comment by XFactHD** [comment]
Looks like a pretty good candidate for mod compat. I'll add it to the pile of planned features.

**Comment by Xaikii** [comment]
Neat :)

**Comment by XFactHD** [comment]
FramedBlocks has moved to NeoForge in 1.20.2+ and will no longer be developed for Forge on future versions. AdditionalLights remains on Forge. As such, integration with AdditionalLights is no longer possible.
