### ISSUE TITLE
[Bug]: You dont get back glowstone 

### ISSUE THREAD

**Issue by f0kx** [XFactHD/FramedBlocks#216]
### Minecraft version

1.19

### Forge version

43.1.52

### FramedBlocks version

6.6.2

### Describe the bug

When you bring a framed block to emit light and break it again with glowstone in it you dont get back the glowstone dust.

### How to reproduce the bug

place a framed block
put glowstone dust into it
break it

### Expected behavior

get back framed block and glowstone dust

**Comment by XFactHD** [comment]
This is intended behaviour. If I remember correctly, Carpenters Blocks (which is the main inspiration for this mod) did it the same way back in the day.
I can however add a config setting to enable dropping the glowstone dust. Let me know if that's a satisfactory solution for you.

**Comment by f0kx** [comment]
ahhhh its intended so all is fine ... if that is your design of the mod all is good ... thx you for answering

**Comment by XFactHD** [comment]
Thank you for the quick feedback, I'll close this as done then.
