### ISSUE TITLE
[Feature]: inverted triangular prism?

### ISSUE THREAD

**Issue by Lilygabe** [XFactHD/FramedBlocks#218]
### Describe the feature

As of now, it's possible to use the triangular slab prism to have pointy roofs that are an odd number of blocks wide, but this leaves a space where the intersection between the right triangle blocks would start. 
A theoretical block which would be the inverted version of the triangular slab prism, I believe, would probably solve the issue.

**Comment by XFactHD** [comment]
Can you show a screenshot of what you mean? I'm having a hard time imagining what shape you are describing and under which circumstance it would be used.

**Comment by Lilygabe** [comment]
> Can you show a screenshot of what you mean? I'm having a hard time imagining what shape you are describing and under which circumstance it would be used.

Nevermind, I think I've been using an older version of the mod. The inner prism has been in the mod for a bit, apparently.
It might also be that some blocks are confusing to understand

**Comment by XFactHD** [comment]
A few shapes aren't immediately obvious, I definitely agree on that. When I find the time for it, I want to make proper documentation for the content, tools and configurability of the mod in the hopes of alleviating some of this confusion.

I'm gonna close this issue for now. If you find that you are indeed missing a shape, feel free to reply to this issue again and I'll reopen it if needed.
