### ISSUE TITLE
[Bug]: No textures displayed when CARRY-ON places a block

### ISSUE THREAD

**Issue by SrRapero720** [XFactHD/FramedBlocks#219]
### Minecraft version

1.18

### Forge version

40.1.85

### FramedBlocks version

5.9.2

### Describe the bug

When carry places a framed block with texture, block get placed normally, and containt data about what block its holding
but visually block have not texture. (visual bug)
Also corners from other blocks arround no show textures.

https://user-images.githubusercontent.com/29090346/207200947-3b9fe92f-705a-46f9-94c0-2ee816e15670.mp4

### How to reproduce the bug

Carry a framed block with texture and place it again

### Expected behavior

Show texture

### Additional details

Just a axoloth with a maid dress
![2022-12-12_19h06_56](https://user-images.githubusercontent.com/29090346/207201148-8e67d247-17a3-4391-be9f-810818eeb6b5.png)

**Comment by XFactHD** [comment]
Please report this to Carry On, they are not properly updating the world when placing and removing the block.

**Comment by XFactHD** [comment]
Fixed by CarryOn, closing.
