### ISSUE TITLE
[Suggestion] Orientation Improvements

### ISSUE THREAD

**Issue by JuicyCosmos** [XFactHD/FramedBlocks#22]
Hello! Comparing this mod with BlockCarpentry, I have come to the conclusion that this mod behaves much better visually, without those weird light issues with shaders and has more shape options. I'm replacing BlockCarpentry with FramedBlocks in my next survival world. But there are a few QOL things I would like to suggest.
So, it seems slopes do not exactly behave like vanilla stairs when you try to place them and their slope can only be vertical if there's a block immediately above or beneath it. If you try to place them from a block on the same y level the slope ends up being horizontal. This makes creating outer parts of roofs with framed slopes very annoying as you need to constantly place then break support blocks. I suggest changing the block orientation behavior similar to vanilla stairs, or implementing a way of selecting orientation before placing the blocks down. Alternatively, adding a wrench which can rotate the blocks should also work. So far wrenches from other mods don't seem to work and Quark's lock orientation feature doesn't workm either.

**Comment by XFactHD** [comment]
This is something that has annoyed me the whole time but I haven't found a satisfactory solution to it.

One solution I am thinking about is to determine the type of slope depending on the y position of the crosshair on the side of the block:

- If you aim at the bottom quarter of the block side, you get an upwards slope
- If you aim at the top quarter of the block side, you get a downwards slope
- If you aim between the top and bottom quarter, you get a sideways slope

Would that be an appropriate solution or do you have another idea that doesn't involve manually selecting the desired shape before or after placing the block?

**Comment by JuicyCosmos** [comment]
Your solution sounds absolutely great!
I suppose it looks like something like this:
![image](https://user-images.githubusercontent.com/79921098/116832309-2dda2c00-abe7-11eb-8b56-5b20fbf10d51.png)
Have you considered if this one is better or not? 
![image](https://user-images.githubusercontent.com/79921098/116832352-611cbb00-abe7-11eb-8eab-8594aaa17525.png)
Or maybe this one if possible:
![image](https://user-images.githubusercontent.com/79921098/116832382-96c1a400-abe7-11eb-95ff-4ab423b6b1b3.png)

Actually you can also separate it into two items which freely convert between themselves like most other mods do: a vertical one and a horizontal one. But anyway whichever solution you choose the problem can be solved. I'm just giving a little reminder, xD

**Comment by XFactHD** [comment]
The first drawing is exactly what I meant.
I will go with that one because it make more sense than the second one in my opinion. The third one is possible but a little more complex.

**Comment by XFactHD** [comment]
Implemented in 55bf215c54a76d74c388175c07652568c3438721
