### ISSUE TITLE
[Feature]: Allow Framed Slop Slab and Framed Elevated Slop Slab to be placed Vertically

### ISSUE THREAD

**Issue by Glitched94** [XFactHD/FramedBlocks#220]
### Describe the feature

Similar to the Framed slope, allow for Slop Slabs to be placed vertically

Allows smoother transitions in vertical shapes like below:

![2022-12-16_12 25 02](https://user-images.githubusercontent.com/49892068/208183263-65ea7386-45eb-4016-a17b-333c61e6386d.png)

**Comment by XFactHD** [comment]
This already exists as the Framed Slope Panel and Framed Extended Slope Panel respectively. Those blocks being separate from the slope slabs has both technical and usability reasons.

Keep in mind that the placement behaviour of the slope panels is a bit more complex, so I'd suggest playing around a bit with the specific position of the crosshair on the block face you are looking at, the specific face you are looking at and the relative rotation between the player and the face you are looking at.
