### ISSUE TITLE
[Bug]: framed vertical half stairs crashes the client

### ISSUE THREAD

**Issue by xinwolfthorn** [XFactHD/FramedBlocks#221]
### Minecraft version

1.16 - UNSUPPORTED

### Forge version

36.2.34

### FramedBlocks version

2.16.1

### Describe the bug

when selecting framed_vertical_half_stairs in inventory, client crashes to launcher.

### How to reproduce the bug

give self framed_vertical_half_stairs and hold item, client crashes with:

The game crashed whilst tesselating block model
Error: java.lang.IllegalArgumentException: Cannot get property EnumProperty{name=type, clazz=class xfacthd.framedblocks.common.data.StairsType, values=[VERTICAL, TOP_CORNER, BOTTOM_CORNER]} as it does not exist in Block{framedblocks:framed_half_stairs}

### Expected behavior

not to crash =P

### Crash log

https://gist.github.com/xinwolfthorn/724c15e707356dce5e3afe44462798ee

**Comment by XFactHD** [comment]
As you may or may not have noticed, 1.16 is unsupported and would normally not get any updates anymore. You are in luck that I need to release a fix to another major crash bug where I'll include the fix for this.
