### ISSUE TITLE
[Question]: Server Properties config missing? 1.19

### ISSUE THREAD

**Issue by Taikira** [XFactHD/FramedBlocks#225]
### Question

I saw on your Curseforge page that making blocks intangible is supposed to be possible but requires turning the option on in server configs, however I can't seem to locate the file.  I checked configs as well as defaultconfigs and could not find any config with the required setting to toggle.  Is it supposed to be missing at this time or is there a way to fix this?

**Comment by XFactHD** [comment]
The server configs are in the world folder under `saves/WorldName/serverconfigs/framedblocks-server.toml`.
If you want to have this feature enabled in all worlds you create, you can copy the config file out of the world into the defaultconfigs folder and it will automatically be copied to all new worlds you create after that.

I'm aware that the way Forge handles server configs might be a bit confusing but it's the only way I can ensure the server and client have the same values for these config options.

I hope that clears up the confusion.

**Comment by Taikira** [comment]
Thank you so much, that was exactly what I was missing! ^^
