### ISSUE TITLE
[Feature]: double framed elevated slope split horizontally

### ISSUE THREAD

**Issue by schismatix** [XFactHD/FramedBlocks#227]
### Describe the feature

so as to be able to make a sloped roof would it be possible to have a block that is a double elevated slope that is spit horizontally so it would be like a slab having a sloped slab on top in one block like this:
![doubleframedelevatedslopesplitt](https://user-images.githubusercontent.com/4486588/215268617-38478e34-7e8a-4cfd-bb54-ab26b846cc4f.png)

**Comment by XFactHD** [comment]
I hadn't planned to add this kind of block but I can see why it would make sense. I'll add it to the list of blocks to add.
