### ISSUE TITLE
[Feature]: split block textures

### ISSUE THREAD

**Issue by GreenForzeGaming** [XFactHD/FramedBlocks#229]
### Describe the feature

the blocks that has multiple blocks put together should have 2 textures, base 1 and base 2 so we can see what parts are together.
![image](https://user-images.githubusercontent.com/62345403/216682134-5129b9c1-4af4-4613-a9c9-a1b38544fca8.png)

**Comment by XFactHD** [comment]
I actually really like this idea, just not sure how to implement it. I'll look into it.
