### ISSUE TITLE
[Feature]: Ghost/Non-Collideable Blocks

### ISSUE THREAD

**Issue by CosmicTelluride** [XFactHD/FramedBlocks#230]
### Describe the feature

Allow framed blocks to have their collision disabled by right-clicking them with a Phantom Membrane (or another item of choice).

**Comment by XFactHD** [comment]
This feature already exists and does indeed use the Phantom Membrane. You just need to enable it via the `enableIntangibleFeature` setting in the server config as explained on the CurseForge page.
