### ISSUE TITLE
[Feature]: Disabling certain frame shapes on servers

### ISSUE THREAD

**Issue by etzabo** [XFactHD/FramedBlocks#232]
### Describe the feature

I have a server and would like to maintain the "look" of Minecraft by disabling shapes with slopes. It would be nice to have a server-side config option that disables the ability to use specific frames.

**Comment by XFactHD** [comment]
Adding config options for close to 100 blocks and even more in the future is not a viable option. I also refuse to control the registration of the blocks via configs, so they would only be disabled at a surface level anyway.

The proper way for you to disable these shapes is to remove their recipes with a datapack (or CraftTweaker or KubeJS if you prefer those).
