### ISSUE TITLE
[Bug]: Render failing

### ISSUE THREAD

**Issue by ZKvAL96** [XFactHD/FramedBlocks#233]
### Minecraft version

1.19

### Forge version

Forge 43.2.0

### FramedBlocks version

Frameblock-6.7.0

### Describe the bug

![Captura de pantalla_20230225_113246](https://user-images.githubusercontent.com/126325261/221352433-cdd0faea-1ce4-4a09-addb-db0b25d2abdb.png) 
### Faces don't render
As you can see in the screenshot, for some reason 1 face render but the others don't. I don't know whats causing this, it happens with all framed blocks. _Help please_.

**1.19.2**
**FORGE 43.2.0**
**Optifine HD I1 Ultra**
**FramedBlocks-6.7.0**

### How to reproduce the bug

Pick a Framed block, then place it (_doesn't matter if have a block_) always dissapear the faces.

### Expected behavior

![Captura de pantalla_20230225_113246](https://user-images.githubusercontent.com/126325261/221352841-221bc0fe-6adc-4249-ae12-d530ce3e627e.png)

**Comment by XFactHD** [comment]
Please try removing OptiFine.
If you want to play with shaders, I would highly recommend using Rubidium and Oculus instead.

**Comment by XFactHD** [comment]
Closing due to lack of feedback.
If the suggested fix didn't work, feel free to comment on this issue with more detailed info (including a debug crash created by holding F3 + C for 10 seconds) and I will reopen it if needed.
