### ISSUE TITLE
[Feature]: Stackable framed corner pillars

### ISSUE THREAD

**Issue by chrisgates301** [XFactHD/FramedBlocks#234]
### Describe the feature

Basically up to 4 framed corner pillars put together to make a full block made of 4 different textures on each corner

**Comment by XFactHD** [comment]
When I started implementing the double blocks, I decided that two shapes combined in a single block will be the limit and that's not going to change. The last thing I want is to have FramedBlocks be a tool used to chunk-ban other players.
