### ISSUE TITLE
[Bug]: Rubidium Extra's Biome Blending breaks biome-dependent block tinting

### ISSUE THREAD

**Issue by tobylindup01** [XFactHD/FramedBlocks#236]
### Minecraft version

1.19

### Forge version

v43.2.6

### FramedBlocks version

v6.7.0

### Describe the bug

Framed blocks with grass blocks used as the texture render with a greyish coloured grass instead of green
![2023-02-28_15 28 18](https://user-images.githubusercontent.com/126593578/221901158-e7641151-98cd-4f89-b938-07413866e27e.png)

### How to reproduce the bug

1) Place Framed Block
2) Use Grass Blocks

### Expected behavior

The block should have green grass instead of grey

### Additional details

Rubidium - v0.6.2
Oculus 1.19.2 - v1.2.8

**Comment by XFactHD** [comment]
I've looked into this a bit more and found that this is Rubidium Extra's fault: https://github.com/dimadencep/sodium-extra-forge/issues/29. Unfortunately it looks like they have no plans to fix this for 1.19.2. As such there isn't anything I can do about this.
