### ISSUE TITLE
[Bug]: Crash on startup with JEI ≥10

### ISSUE THREAD

**Issue by unilock** [XFactHD/FramedBlocks#240]
### Minecraft version

1.18

### Forge version

40.2.0

### FramedBlocks version

5.11.0

### Describe the bug

The game crashes during setup with FramedBlocks and the latest version of JEI installed.

### How to reproduce the bug

1. Install [JEI 10.2.1.1002](https://www.curseforge.com/minecraft/mc-mods/jei/files/4352925) (latest version).
2. Install [FramedBlocks 5.11.0](https://www.curseforge.com/minecraft/mc-mods/framedblocks/files/4431051).
3. Start the game.
4. Crash.

### Expected behavior

The game is able to load and reach the title screen successfully.

### Additional details

This does not occur with 5.10.0 - which makes sense, as that version didn't declare any sort of dependency on JEI.

This is probably the change causing the issue:
https://github.com/XFactHD/FramedBlocks/commit/1acc298ce7752d012a42deb54b9e7b1caeb37387#diff-3bc2a2f6cb6e625914eaf245e536e39108fbc2a24acd076bd6bbc2a60f56c214

### Crash log

https://gist.github.com/unilock/cd9a1cfa985c4409fa13ebea42af9690#file-crash-2023-03-10_14-44-33-fml-txt

**Comment by 5stigma** [comment]
Same problem

**Comment by XFactHD** [comment]
FramedBlocks 5.11.0 requires JEI 9 for the time being. That decision was made based on the fact that ATM7 uses JEI 9 and is one of the largest packs this mod is included in.
I'm looking into the viability of a workaround for this issue but I can't promise anything yet.

**Comment by XFactHD** [comment]
Found a somewhat acceptable workaround. New version will be available on CurseForge shortly.
