### ISSUE TITLE
[Bug]: Framed Blocks crashing with JEI 9 Release Build

### ISSUE THREAD

**Issue by DaRealSparky** [XFactHD/FramedBlocks#241]
### Minecraft version

1.18

### Forge version

40.2.1

### FramedBlocks version

5.11.0+

### Describe the bug

Game crashes with Error Code 1 and no logs.

(Note: All JEI builds (Beta, Alpha, and Release) on Minecraft 1.18.2 are of JEI 9 and 10, and according to the change log should be supported and working.)

### How to reproduce the bug

Install Framed Blocks Version 5.11.0 or higher and JEI Release Build Version 9.7.1.255 with Forge 40.2.1 on Minecraft 1.18.2.
Load game and observe launcher with Error Code 1.

### Expected behavior

Game should run normally and shouldn't crash with any JEI Build on 1.18.2

### Additional details

N/A

### Crash log

No Logs Generated

**Comment by XFactHD** [comment]
You need to use JEI 9.7.2.266 or newer.

Next time you encounter a crash, please provide the logs, the game always creates log files.
