### ISSUE TITLE
[Bug]: Minecraft Crashes whit 7.1.0 for 19.3 version

### ISSUE THREAD

**Issue by DiebderSeelen** [XFactHD/FramedBlocks#242]
### Minecraft version

1.19

### Forge version

1.19.3

### FramedBlocks version

7.1.0

### Describe the bug

i got this mod on my server, and when i put the new version, all looks ok, but when i try to get in ,like 5 sec after, the game crashes, so i had to back to 7.0.0 version.. but it take a bit lag on the server, something i can do to fix it?? 

### How to reproduce the bug

try to get in the game whit 7.1.0 version

### Expected behavior

the mod works well, cause its a rlly awesome mod...

**Comment by XFactHD** [comment]
Please provide a crash report as requested by the issue template, otherwise I have no way to find out what's wrong.

**Comment by DiebderSeelen** [comment]
FramedBlocks BlockEntity Warning: Not applicable
	Crash Report UUID: d8f08758-aa46-4c84-b7cb-0414bc7d1fd9
	FML: 44.1
	Forge: net.minecraftforge:44.1.17

FramedBlocks BlockEntity Warning: Not applicable
	Crash Report UUID: 496384d0-0ad1-4378-ac98-dd9a6ee91681
	FML: 44.1
	Forge: net.minecraftforge:44.1.17
	
	that??

**Comment by XFactHD** [comment]
I need the full content of the file where that snippet comes from. This snippet alone doesn't provide the needed information.

Also, please put the log on https://gist.github.com and link that here instead of pasting the wall of text into an issue comment.

**Comment by XFactHD** [comment]
I just uploaded FramedBlocks 7.1.1 to CurseForge to fix a crash bug introduced in 7.1.0. Please try updating to that version and report back if that fixes the issue for you as well. If it doesn't, then I'll still need the full crash report.

**Comment by DiebderSeelen** [comment]
Amazing work team, I'm looking for make a donation but I'm a bit new on this.... Really amazing... Who is the best hosting panel? Cuz I'm trying whit Multicraft, and to be honest one of the worst..


[http://graphics.hotmail.com/i.p.emcool.gif]
JuSt nanndO
That'S alL
[http://graphics.hotmail.com/i.p.emwink.gif]
________________________________
De: Dennis C ***@***.***>
Enviado: jueves, 16 de marzo de 2023 11:36 a. m.
Para: XFactHD/FramedBlocks ***@***.***>
Cc: DiebderSeelen ***@***.***>; Author ***@***.***>
Asunto: Re: [XFactHD/FramedBlocks] [Bug]: Minecraft Crashes whit 7.1.0 for 19.3 version (Issue #242)


I just uploaded FramedBlocks 7.1.1 to CurseForge to fix a crash bug introduced in 7.1.0. Please try updating to that version and report back if that fixes the issue for you as well. If it doesn't, then I'll still need the full crash report.

**Comment by XFactHD** [comment]
I'm gonna assume that updating to 7.1.1 fixed the crash.

I currently do not have any donation system set up but I appreciate the thought.
