### ISSUE TITLE
[Bug]:The sides of the framed slops disappear sometimes.

### ISSUE THREAD

**Issue by Aerhtjiz** [XFactHD/FramedBlocks#245]
### Minecraft version

1.18

### Forge version

40.2.1

### FramedBlocks version

5.11.2

### Describe the bug

When using the create mod along with framed blocks the sides of the slopes disappear entirely

Video Description
\/
https://www.dropbox.com/s/7qmh54r5ybudk90/2023-03-17%2020-34-27.flv?dl=0

### How to reproduce the bug

Using the sticky mechanical pistons to grab a portion of the slopes.

### Expected behavior

For the sides of the slope to not disappear.

**Comment by XFactHD** [comment]
Well, it had to happen at some point that my optimizations fall apart due to an edge case and need reinforcing. I'll get an update out shortly that should prevent these edge cases once and for all.
