### ISSUE TITLE
[Bug]: Game Refuses to Launch and Lingers in Background after 5.11.0 Update

### ISSUE THREAD

**Issue by Camawama** [XFactHD/FramedBlocks#246]
### Minecraft version

1.18

### Forge version

40.2.1

### FramedBlocks version

FramedBlocks-5.11.0.jar

### Describe the bug

I am working on my modpack (CamaCraft) and I recently went through some mods to update. After updating, my game refused to launch from the launcher. Not even a Window would open.... I tried reverting a bunch of the other mods which were updated but when I got to FramedBlocks, it finally worked.

### How to reproduce the bug

Run my modpack but update FramedBlocks

### Expected behavior

The game should launch.

### Additional details

NO CRASH REPORT BUT HERE ARE THE LOGS:

[latest.log](https://github.com/XFactHD/FramedBlocks/files/11012569/latest.log)

**Comment by XFactHD** [comment]
You need at least JEI 9.7.2.266 or newer with FramedBlocks 5.11.0 and newer but you are currently running JEI 9.7.1.255. I would also highly advise updating FramedBlocks to 5.11.3.

Be sure to report back whether that fixes it or whether you are still running into issues.

**Comment by Camawama** [comment]
I shall test this later tonight, thank you!

**Comment by Camawama** [comment]
Can report that it is now working fine, thank you for your time and help!

**Comment by XFactHD** [comment]
Perfect, thank your for the confirmation.
