### ISSUE TITLE
[Feature]: Block with two cut corners and flat surface between.

### ISSUE THREAD

**Issue by ThoBekMic** [XFactHD/FramedBlocks#248]
### Describe the feature

![image](https://user-images.githubusercontent.com/3033414/227953980-7efb44b7-2217-4b46-a79f-b2d4e48c5b9e.png)

(10 years in mspaint.)

I may be missing it, but I don't think such a block is in yet.

**Comment by ThoBekMic** [comment]
Also this block.

![image](https://user-images.githubusercontent.com/3033414/228262773-e2b9619b-da97-4962-a99d-1b3987d5e603.png)

(mspaint skills improving)

**Comment by XFactHD** [comment]
The first one makes sense to me and also seems quite useful, I'll add that to the list and expand a bit on it.
I'm not getting the second one though. Are those supposed to be two blocks on top of each other?
