### ISSUE TITLE
[Bug]: Crash when leaving minecraft server

### ISSUE THREAD

**Issue by Branjoman** [XFactHD/FramedBlocks#250]
### Minecraft version

1.19

### Forge version

43.2.6

### FramedBlocks version

6.8.2

### Describe the bug

When I leave the minecraft server I'm running, sometimes instead of returning me to the server selection screen the game instead crashed to desktop.

### How to reproduce the bug

As this bug seems to be intermittent, I currently don't know of a way to reliably reproduce the crash.

### Expected behavior

When exiting the server, I should return to the server selection screen.

### Additional details

This crash on the outside does appear to be generic, however this line in the crash log:
`at xfacthd.framedblocks.api.util.client.ClientUtils.onClientTick(ClientUtils.java:219) ~[FramedBlocks-6.8.2.jar%23494!/:6.8.2] {re:classloading}`
indicated to me that framed blocks was potentially causing this, which is why I made the bug report here.

### Crash log

https://pastebin.com/Zd4Kw8J2

**Comment by XFactHD** [comment]
Your instinct was correct, this is 100% my fault. The reason it's intermittent is that a specific sequence of events involving a block update and your disconnection needs to happen in a very short time frame.

I'll get this fixed for the next small update which I hope to get done within the next few days.
