### ISSUE TITLE
[Bug]: java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by LanCeeXD** [XFactHD/FramedBlocks#252]
### Minecraft version

1.19

### Forge version

41.1.0

### FramedBlocks version

6.1.0

### Describe the bug

Can't load the game with the mod in my folder. Started with a completely clean .minecraft folder as well and it still will not load the game.

### How to reproduce the bug

Step 1: Put the mod in the mods folder
Step 2: Start game
Step 3: Result

### Expected behavior

The game is supposed to run

### Crash log

https://gist.github.com/LanCeeXD/c8dc23a30114e51a00eca239e0af89e2

**Comment by XFactHD** [comment]
You need to update to FramedBlocks 6.2.0 to use that Forge 1.19 version.

Though, I would highly suggest updating to 1.19.2 and the latest version of FramedBlocks for that version as the Minecraft version and accompanying Forge version you are using is severely outdated, not supported anymore by basically any modder and the FramedBlocks versions available for it are missing major improvements and feature additions.
