### ISSUE TITLE
[Feature]: Framed Double/Divided Cube?

### ISSUE THREAD

**Issue by LanCeeXD** [XFactHD/FramedBlocks#254]
### Describe the feature

I'm surprised there's a Divided Slab but not a full block variant of this, or that I can't stack the slabs on top of them to turn it into a full block variant

**Comment by LanCeeXD** [comment]
never mind, turns out I needed to do 2 panels, and that works lol. i haven't seen this kind of behaviour in any other block so far.

**Comment by XFactHD** [comment]
The slab and panel both act like the vanilla slabs in terms of conversion to the double variant. I had initially assumed that people would expect that behavior to be on par with vanilla. I'm in the slow process of documenting these special behaviors in an in-game book to try to prevent this confusion in the future.
