### ISSUE TITLE
[Feature]: Let horizonal pillars connect to each other like fences

### ISSUE THREAD

**Issue by LanCeeXD** [XFactHD/FramedBlocks#255]
### Describe the feature

Currently working on a house in creative mode and I am adding a few details, however I've noticed that the horizontal pillars don't really connect to each other, so the only way I've found so far to avoid this is by putting in a full size block, otherwise there would be some visible gaps between the horizontal and vertical pillars. This is the current workaround I have, I hope this is enough context and gives you an idea of what I'm trying to describe.
![2023-04-18_18 52 49](https://user-images.githubusercontent.com/18635351/232862552-2d02e35e-21d7-46fd-8e59-dce10f8f51fd.png)

**Comment by XFactHD** [comment]
Sounds reasonable to me, I think there is a better approach though: a thicker version of the Framed Lattice suitable for the Framed Pillar. Keep in mind though that this wouldn't be a perfect connection with camos like logs though since one block can only have a single orientation of the camo.
