### ISSUE TITLE
[Feature]: rotateable textures 

### ISSUE THREAD

**Issue by Flintley** [XFactHD/FramedBlocks#257]
### Describe the feature

Please add the ability to rotate the top texture of a block. My problem is that I want to use Oak planks to make a table with a block of a other mod but the planks (the stripes) are pointing in the wrong direction. If you want a picture for better understanding just ask. And sorry for my bad English.

**Comment by XFactHD** [comment]
Blocks which can themselves be oriented in some way (like how logs can be placed on any of the three axis) can already be rotated by right-clicking the framed block with a Framed Screwdriver after applying the camo. For blocks that cannot be oriented, like planks, that's unfortunately not possible.

**Comment by Flintley** [comment]
OK, thanks for the explanation. I just used the vertical oak planks from chipped.
