### ISSUE TITLE
1.16.5 Support for Wallpapercraft-Fresh Roll

### ISSUE THREAD

**Issue by Drakkxs** [XFactHD/FramedBlocks#26]
Issue:
Wallpapercraft-Fresh Roll has glass blocks, when I try to put it on the double slab it doesn't work, normal glass and stained glass work including all other blocks.

some questions:
Is this is intended? why?
If it isn't can you please fix this?

**Comment by XFactHD** [comment]
I have no way to determine in code if these blocks are "basic" blocks with six sides or blocks with a complex model.
Therefore you need to add any additional blocks that you think should work to the `framedblocks:frameable` tag via a data pack. You can find the default tag that adds vanilla glass blocks [here](https://github.com/XFactHD/FramedBlocks/blob/1.16.x/src/generated/resources/data/framedblocks/tags/blocks/frameable.json).
I will add an explanation for this on the CurseForge page when I have some free time.
