### ISSUE TITLE
[Feature]: FTB Ultimine idea

### ISSUE THREAD

**Issue by ClickErrorxD** [XFactHD/FramedBlocks#263]
### Describe the feature

Could you make it so that we can mass-convert framed blocks into a block of our choice using the ftb ulti mine?

Meaning if I held the ftb ultimine key and faced framed blocks and then **right-clicked** a block into the frame, it would convert all framed blocks connected to it. (Up to the max set via ftb ultimine ofc.)

**Comment by ClickErrorxD** [comment]
https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-forge

**Comment by XFactHD** [comment]
As far as I can tell from checking the code of FTB Ultimine, there is no way for me to implement that. I'll ask one of the FTB devs just to be sure but it's likely not going to be possible. I'll keep this issue open until I have an answer.

**Comment by ClickErrorxD** [comment]
Ah that's a shame... I was hoping it was possible. I thought there might of been a slim chance, since it was a right-click like for harvesting in bulk as well. Definitely keeping my fingers crossed.

**Comment by XFactHD** [comment]
After looking into this some more and not receiving any response so far, I'll have to declare this as not possible.
