### ISSUE TITLE
[Bug]: Cooking For Blockheads - Kitchen tile shows invisible

### ISSUE THREAD

**Issue by xFirefalconx** [XFactHD/FramedBlocks#265]
### Minecraft version

1.18

### Forge version

40.2.0

### FramedBlocks version

5.11.4

### Describe the bug

I put some floor boards. 
It works with stone, but Cooking For Blockheads kitchen tiles... disappear and don't render at all. (Ignore the bedrock, that's wanted behaviour)

![grafik](https://user-images.githubusercontent.com/106652912/235183286-50275573-6e36-4d4f-ad6f-04558c34c9f9.png)

I use Oculus, Flywheel and Flywheel Compat plus a shader. 

### How to reproduce the bug

Install Cooking For Blockheads together with FramedBlocks, if that is no issue, also install Oculus, Flywheel, Flywheel Compat and Complementary Reimagined Shader. 
I will ask around if any knows a common issue with that. 

### Expected behavior

Kitchen tiles show on the floor board like the stone block does.

### Additional details

Loaded Shaderpack: ComplementaryReimagined_r2.0.3

current Mod list

modernfix-mc1.18.2-2.4.1
minecard-1.18.2-0.4.0
seasonhud-1.18.2-1.4.13
canary-mc1.18.2-0.1.7
better_enchantments-2023.17.4-TEST1.18.2
ExperienceBugFix-1.18-1.38.0.2
AxolotlBucketFix-1.2.1+forge-mc1.18
FixMySpawnR-forge-1.18.2-1.0.0
MaxHealthFix-Forge-1.18.2-5.0.1
Entity_Collision_FPS_Fix-forge-1.18.2-1.0.0
modelfix-1.8
CraftPresence-2.0.0-rc.2+1.18.2
FramedBlocks-5.11.4
chipped-forge-1.18.2-2.0.1
CTM-1.18.2-1.1.5+5
DynamicTrees-1.18.2-0.11.0-Beta10.1
DynamicTreesQuark-1.18.2-2.2.3
bettervillage-forge-1.18.2-3.1.0
Pehkui-3.7.3+1.18.2-forge
sit-1.18.2-1.3.3
netherportalfix-forge-1.18.2-9.0.1
ExplorersCompass-1.18.2-1.3.0-forge
BetterBeekeeping-1.18.2-1.2.0
rubidium-0.5.6
oculus-flywheel-compat-1.18.2-0.1.8-BETA
oculus-1.5.2
architectury-4.11.90-forge
DynamicTreesPlus-1.18.2-0.2.0-Beta4
so_many_enchants-1.8.0 (1.18)
ManyIdeasCore-1.18.2-1.4.1
supermartijn642corelib-1.1.7-forge-mc1.18
fm_animation_maker_1.2.0
konkrete_forge_1.6.0_MC_1.18-1.18.2
starlight-1.0.2+forge.546ae87
CustomLAN-1.18.1-18.1.2
HammerLib-1.18.2-18.2.16
QuarkOddities-1.18
DiagonalFences-v3.1.0-1.18.2
BetterLogs-1.18.2-(3.0)
nocubes_better_fletching_table_1.0.0_forge_1.18.2
nocube's_better_frogs_1.0.0_forge_1.18.2
bettertaskbar-forge-mc1.18.2-mc1.19.2-1.5.1
flytre_lib-1.18.2-1.8.2-forge
nocube's_better_smoker_1.0.0_forge_1.18.2
BetterCrates-1.18.2-1.0.0
betterconduitplacement-1.18.2-3.0
betterbeaconplacement-1.18.2-3.1
brb-1.18.2-forge-1.5.6
betterfpsdist-1.18.2-1.5
cobbled_paths-forge-0.1.7
Random_mailbox_1.0.0_1.18.2
hexerei-0.2.2
adaptive_performance_tweaks_player_1.18.2-3.18.0
adaptive_performance_tweaks_core_1.18.2-3.20.1
sereneseasonfix-1.18.2-1.0.6
Serene Seasons-1.18.2-7.0.0.13
journeymap-1.18.2-5.9.5-forge
Barsita-1.18.2-1.0.2
lazydfu-1.0-1.18+
Toasty Coins 1.1
PriorityTarget-Forge-1.18.2-2.0.2
Fastload-Reforged-2.6.9+1.18.2
CobbleForDays-1.5.1
randomvillagenames-1.18.2-3.2
randomworldname-2.1
areas-1.18.2-4.3
libraryferret-forge-1.18.2-4.0.0
Mushroom_Villager1.18.2beta
kingvillager-1.10
productivevillagers-1.0.6
villagernames-1.18.2-5.2
villagertools-1.18-1.0.2
chunkloaders-1.2.3-forge-mc1.18
durabilitytooltip-1.1.4-forge-mc1.18
connectedglass-1.1.6-forge-mc1.18
PuzzlesLib-v3.3.6-1.18.2-Forge
UniversalEnchants-v3.0.6-1.18.2-Forge
Teerth's Traffic Control 4.0.0
Traffic_Plus_1.3.0_1.18.2
SaveSettings-1.0.0
StructureCompass-1.18.2-1.3.2
ManyIdeasChristmas-1.18.2-1.0.0
ManyIdeasHalloween-1.18.2-1.0.0
BetterTitleScreen-1.18-1.12.0
seamless_loading_screen-1.18-3.0.0
OpenLoader-Forge-1.18.2-12.0.1
moreoverlays-1.20.11-mc1.18.2
Bookshelf-Forge-1.18.2-13.2.53
configured-2.0.1-1.18.2
nocube's_villagers_sell_animals_1.2.0_forge_1.18.2
NaturalDecorMod_1.18.2_V0.1.5
spells_and_shields-1.18.2-1.10.2-LEGACY
SnowRealMagic-1.18.2-forge-4.2.4
SereneShrubbery-1.18.2-1.4.0
xptome-1.18.2-2.1.7
XPFromHarvest-1.18.2-1.2.2
workers-1.18.2-1.5.2
wooltostring-forge-1.18.2-1.0.1
wildberries-1.1.2[forge-1.18.2]
WhatTheBucket-Forge-1.18.2-4.0.2
weaponleveling-1.18.2-1.4.3
waystone_towers-1.18.2-FORGE-1.0.9
waystones-forge-1.18.2-10.2.0
VillagersRespawn-1.18.1-1.39.0.5
villagebellrecipe-1.18.2-3.0
village-employment-1.18.2-1.5.1
verdure-1.18.2-1.1.3a
VariantCraftingTables-1.18.2-1.7.0_1
VendingMachine-1.18.2-1.0.8
untamedwilds-1.18.2-2.3.0
unordinary_basics-1.18.2-1.0.1.4
towns_and_towers_forge-1.10.0.1+1.18.2
torchmaster-18.1.0
Tips-Forge-1.18.2-5.0.11
TexelsPaintings-forge-1.18.2-5.1.0
swingthroughgrass-1.18.2-1.9.1
SoL-Carrot-1.18.1-1.12.0
snowyspirit-1.18.2-1.3.2
smoothboot(reloaded)-mc1.18.2-0.0.2
smarterfarmers-1.18.2-1.6.0
skylightlanterns-1.18.2-1.0.0
SHAB (1.18.2) V1.1.1
SBM-Jukebox-1.18-1.0.4
Roads-1.18.1-1.4.0
Regrowth-1.18.2-1.40.31.1
RedstoneExtras-1.18-1.0.11
realisticroads-v2
polymorph-forge-1.18.2-0.46
player-animation-lib-forge-1.0.2+1.18
pettransfer-1.18.2
projectsavethepets-3.1.0-old.1.18+2022.10af157d70.forge
Patchouli-1.18.2-71.1
passiveendermen-1.18.2-4.2
Netherited-forge-1.18.2-1.2.1
NaturesCompass-1.18.2-1.9.7-forge
Multiplayer-Server-Pause-1.18-Forge-1.1.0
MouseTweaks-forge-mc1.18-2.21
MoreMobGriefingOptions-1.18.2-2.0.1
MoreCrashInfo-2.3.1
modnametooltip-1.18.1-1.18.0
MobCatcher-Forge-1.18.2-1.1.6
merenc-forge-1.18.x-v1.9
MemorySweep-1.18.2-0.8
mcw-roofs-2.2.3-mc1.18.2forge
mcwfencesbop-1.18.2-1.4
mcw-windows-2.1.1-mc1.18.2forge
mcw-fences-1.0.7-mc1.18.2forge
mcw-doors-1.0.9forge-mc1.18.2
mcw-bridges-2.0.7-mc1.18.2forge
ManyIdeasDoors-1.18.2-1.2.0
RecipesLibrary-1.18.2-2.0.0
manascore-1.18.2-1.0.2.0
majrusz-library-1.18.2-3.3.0
majruszs-accessories-1.18.2-1.1.4
little_geode 1.18.2-1.3.0
Level-One-MC1.18.2-v1.6.0
kleeslabs-forge-1.18.2-11.1.1
keepmysoiltilled-1.18.2-2.0
JustEnoughResources-1.18.2-0.14.1.171
Jade-1.18.2-forge-5.2.6
ItemLocks-Forge-1.18.2-1.3
itemcollectors-1.1.7-forge-mc1.18
InfoDataPack-1.18.1-2.0.2.8
IBICF-1.4.0-build.8+mc1.18.2
horse_colors-1.18.2-1.8.0
hole_filler_mod_1.2.5-mc_1.18.1-forge
hedgehog-1.18.2-1.1.0
hauntedharvest-1.18.2-1.7.7
selene-1.18.2-1.17.9
guardvillagers-1.18.2.1.4.3
GameMenuModOption-1.18-Forge-1.14.2
ftbbackups2-forge-1.18.2-1.0.18
polylib-forge-1801.0.2-build.13
FruitTrees-1.18.2-forge-5.0.1
Kiwi-1.18.2-forge-6.1.3
forgivingvoid-forge-1.18.1-6.0.1
ferritecore-4.2.2-forge
FastLeafDecay-28
overweightfarming-1.18.2-1.6.0-forge
largemeals-1.18.2-2.0
honeyexpansion-1.1.1
FarmersRespite-1.18.2-1.3.0
fantasyfurniture-1.18.2-3.14.0
ExtendedItemInformation-4.0.2-1.18.2
exoticbirds-1.18.2-1.8.0
ExNihiloSequentia-1.18.2-20221113-044349
EnderBags-1.18.1-8.0.0
JEIEnchantmentInfo-1.17.1-2.0.0
EnchantmentDescriptions-Forge-1.18.2-10.0.12
DynamicTreesBOP-1.18.2-3.0.0-Beta3
Quark-3.2-358
DynamicSurroundings-5.0.0.4
DungeonCrawl-1.18.2-2.3.12
Disenchanting-forge-1.18.2-2.2.2
Dessertv1.3
deepslate_dubble003
Curses_and_magic_1.9_1.18.2
croptopia-chocolaterie-1.1
Croptopia-1.18.2-FORGE-2.1.0
crittersandcompanions-1.18.2-1.0.2
creeperconfetti-3.11
create_food-1.18.2
create-1.18.2-0.5.0.i
flywheel-forge-1.18.2-0.6.8.a
Crated_Vanilla_Foods_1.1-1.18.2
corn_delight-1.0.6-1.18.2
FarmersDelight-1.18.2-1.2.0
mmlib-1.2.0-1.18.2
Copper Armory Remastered 1.2.1 1.18.2
farmingforblockheads-forge-1.18.2-10.0.2
cookingforblockheads-forge-1.18.2-12.2.0
Controlling-forge-1.18.2-9.0+22
Clumps-forge-1.18.2-8.0.0+17
cloth-config-6.4.90-forge
citydecor-1.1.1
citadel-1.11.3-1.18.2
ChiselsBits-forge-1.18.2-1.2.116-universal
ChinjufuMod[1.18.2]6.2.4
Chimes-1.1.2-1.18.2
cherryblossomgrotto-0.4.6-v1.18.2
cell-lever-1.18-3.0.0.1
burgermod-2.8.0-1.18.2
BorderlessWindow-1.18-1.4.0
biomespawnpoint-1.18.2-2.0
villagespawnpoint-1.18.2-4.0
Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.7
BiomesOPlenty-1.18.2-16.0.0.109-universal
TerraBlender-forge-1.18.2-1.2.0.126
Beyond-Earth-1.18.2-6.2
geckolib-forge-1.18-3.0.57
BetterThirdPerson-Forge-1.18.2-1.9.0
betterspawnercontrol-1.18.2-4.0
collective-1.18.2-6.53
bettersafebed-1.18-forge-a
betterfoliage-3.1.4
BetterCompatibilityChecker-1.1.21-build.48+mc1.18.2
Book Fishing 1.0.0 - 1.18.2
Better Fishing Rods 1.0.0 - 1.18.2
benched-1.2.2-forge-mc1.18
supermartijn642configlib-1.1.6-forge-mc1.18
Beekeeper-1.18.2-1.0.5
beehive-tooltips-forge-1.4.2
BeeFix-1.18-1.0.7
BambooEverything-forge-1.3.8-build.45+mc1.18.2
bamboo2-1.18.1_0.4
balm-3.2.6
BadMobs-1.18.2-13.01
autoplant-1.18.2-1.0.0
ArtisticCraft v0.16.1-1.18.2
atmospheric-1.18.2-4.0.0
blueprint-1.18.2-5.5.0
astikorcarts-1.18.2-1.1.2
appleskin-forge-mc1.18.2-2.4.1
anviltooltipmod-MC1.18.2-1.0.0
AkashicTome-1.5-20
AutoRegLib-1.7-53
BetterAdvancements-1.18.2-0.2.0.146
AbsolutelyUnbreakable1.18.2-2.0.1-1.18.2
3dskinlayers-forge-1.5.2-mc1.18.2
(Forge)SimpleMango-1.18.2-1.2.0
jei-1.18.2-forge-10.2.1.1004
Placebo-1.18.2-6.6.7
notenoughcrashes-4.2.0+1.18.2-forge
FemaleVillagers-1.18.2-1.6
supplementaries-1.18.2-1.5.17
sophisticatedcore-1.18.2-0.5.50.250
sophisticatedbackpacks-1.18.2-3.18.45.818
sophisticatedstorage-1.18.2-0.6.28.334
movingelevators-1.4.1-forge-mc1.18
sootychimneys-1.18.2-1.1.0
ChunkByChunk-forge-1.18.2-1.13.4
carryon-1.18.2-1.17.1.11
fancymenu_forge_2.14.7_MC_1.18.2
drippyloadingscreen_forge_2.2.1_MC_1.18.2

**Comment by XFactHD** [comment]
I've looked into it and found that this needs to be fixed by Cooking for Blockheads. Their kitchen floor model does not specify the so-called cull-faces which tell the game that a certain surface of the block can be culled when it's covered by a neighboring block on the given side: https://github.com/TwelveIterationMods/CookingForBlockheads/blob/1.19.x/shared/src/main/resources/assets/cookingforblockheads/models/block/kitchen_floor.json#L12-L17. I rely on that information to get the model surfaces and transform then into the various shapes. Please report this to them with the above explanation.

**Comment by xFirefalconx** [comment]
I'm struggling a tiny bit to understand the issue itself, so I hope I don't bother. 
Does this ... model?? work with your mod? 
https://github.com/TwelveIterationMods/CookingForBlockheads/blob/e9949711585f48d36b8356bb754bb92f302890eb/shared/src/main/resources/assets/cookingforblockheads/models/block/kitchen_floor.json

They fixed it on 1.19 apparently but told me to use a resource pack on 1.18... I don't know how to do this so I am a bit lost right now. 

If you could... explain the situation for noobs, I'd really appreciate that. I can add a resource pack to my modpack I guess. I just... don't know where to even begin. Thanks for your time so far.

**Comment by XFactHD** [comment]
Yes, that fixed model will work with FramedBlocks due to these six lines now correctly specifying the `cullface` property: https://github.com/TwelveIterationMods/CookingForBlockheads/blob/e9949711585f48d36b8356bb754bb92f302890eb/shared/src/main/resources/assets/cookingforblockheads/models/block/kitchen_floor.json#L12-L17.

I just saw that they provided a resource pack for you, otherwise I would have tried explaining how to build it. I would highly suggest looking into the resource pack ZIP they gave you with 7zip or WinRAR to get to know how it's built, it's a fairly simple structure. What the specific parts of the model system do is a bit much to explain in a GitHub issue, I'd suggest reading through the MC wiki page for that: https://minecraft.fandom.com/wiki/Tutorials/Models

**Comment by xFirefalconx** [comment]
Thank you for the explanation, I will consider taking a peek in the zip file to understand it more. I tested it in my modpack and it does indeed work. Love my new kitchen tiles with carpet behaviour *squee* 
Thanks also for the help and the words I could relay to them. Have a good time, hopefully without any more bugs from my side xD
