### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by StarTheProot** [XFactHD/FramedBlocks#266]
### Question

When I opened Minecraft, I was met with an error, I opened the TXT file with the crash info and I got this as the failure message:

Failure message: Mod File FramedBlocks-8.0.2.jar needs language provider javafml:45 or above to load We have found 43.

How Do I Fix?

Forge Version: 43.1.57
Framed Blocks Version: 8.0.2

**Comment by XFactHD** [comment]
The version of FramedBlocks you are using was built for 1.19.4 but you are running 1.19.2. You need to either downgrade to the latest version of FramedBlocks for 1.19.2 (version 6.8.3) or upgrade Forge to 1.19.4 and upgrade all other mods accordingly. The first option is of course far easier.

Please carefully check the version of Minecraft a certain FramedBlocks version is compatible with when downloading it from CurseForge.

**Comment by XFactHD** [comment]
Closing due to lack of feedback. I'm going to assume that you managed to fix your issue with the help of my explanation above.
