### ISSUE TITLE
[Feature]: Remove Glass Border when placing multiple framedblocks with glass in them

### ISSUE THREAD

**Issue by kamitojaeger** [XFactHD/FramedBlocks#269]
### Describe the feature

Would there be an option to adjust the outlook of multiple framedblocks that r placed together. Player can use wrench to remove/add border between the framedblocks, which would offer more choices for builders to change the outlook of their builds

**Comment by XFactHD** [comment]
Removing the borders between blocks such as glass is the task of connected textures mods such as [CTM](https://www.curseforge.com/minecraft/mc-mods/ctm). Connected textures support is still a work in progress though and has some issues at the moment. See #235 for more details and progress on the implementation.

If that is not what you are talking about, then please go into more detail and provide screenshots of what exactly you mean.

**Comment by XFactHD** [comment]
Closing due to lack of feedback, I'm going to assume that the message above answered your question.
