### ISSUE TITLE
[Bug]: "Exit Code 1", possible mod conflict

### ISSUE THREAD

**Issue by George0079** [XFactHD/FramedBlocks#271]
### Minecraft version

1.18

### Forge version

40.2.2

### FramedBlocks version

8.0.2

### Describe the bug

My game refuses to launch and will always crash with this mod installed. I am going through my modlist to find the specific conflict.

### How to reproduce the bug

Launch the game with the mod installed.

### Expected behavior

I expected my game to launch and for any bugs to occur mid-game.

### Additional details

Here is my current modlist. I'm trying to make my own pack and am still in the "Plug and Play" stage.
Framed Blocks is not installed in this pack and will have to be installed.

[Issue.zip](https://github.com/XFactHD/FramedBlocks/files/11513061/Issue.zip)

**Comment by XFactHD** [comment]
Please provide the crash report and the debug log (you may have to enable the debug log in the CurseForge settings first and then reproduce the crash again) via https://gist.github.com, otherwise I won't be able to help you.

**Comment by XFactHD** [comment]
Closing due to lack of feedback.
The only potential hint I can give you is that FramedBlocks requires JEI 9.7.2.266 or newer if JEI is installed.
If you decide to provide the requested information at a later time, feel free to comment on this issue and I will reopen it if needed.
