### ISSUE TITLE
[Bug]: framed signs with create mod trains

### ISSUE THREAD

**Issue by Quinnie333** [XFactHD/FramedBlocks#272]
### Minecraft version

1.19

### Forge version

43.2.0

### FramedBlocks version

FramedBlocks-6.8.3.jar

### Describe the bug

blocks put on a sign on a train (create mod) disappear after assembling the train, after 2 or 3 assembly attempts

### How to reproduce the bug

1. build a train
2. place signs
3. use blocks on framed signs (blocks from chipped and Dave building extended here) 
4. assemble the train, then disassemble it and do it two or three times

### Expected behavior

blocks on the framed sign are supposed to stay on it

### Crash log

any crash

**Comment by XFactHD** [comment]
Will be fixed in the next update, the release date is still unknown though.
