### ISSUE TITLE
[Bug]: framed doors cant open on create trains/

### ISSUE THREAD

**Issue by Quinnie333** [XFactHD/FramedBlocks#273]
### Minecraft version

1.19

### Forge version

43.2.0

### FramedBlocks version

FramedBlocks-6.8.3.jar

### Describe the bug

framed doors cant open on create trains

### How to reproduce the bug

place a framed door on a train and try to open it

### Expected behavior

door is supposed to open

**Comment by XFactHD** [comment]
Will be fixed in the next update, the release date is still unknown though.
