### ISSUE TITLE
[Feature]: Vertical double stairs

### ISSUE THREAD

**Issue by Zaritrix** [XFactHD/FramedBlocks#274]
### Describe the feature

![image](https://github.com/XFactHD/FramedBlocks/assets/48804009/94590cb9-5a10-40cb-9f44-8f88e1ecfb7f)
A vertical half slab of any block and the little ledge/first step of the stairs being another block.
Basically those two blocks in the picture but glued together.

**Comment by XFactHD** [comment]
Duplicate of #165.
These are already planned but I'm still looking for short, descriptive names for them, so if you have ideas for that, I'm all ears :)
