### ISSUE TITLE
[Crash]: New DiagonalFences update crashes on startup

### ISSUE THREAD

**Issue by xFirefalconx** [XFactHD/FramedBlocks#277]
### Minecraft version

1.18

### Forge version

40.2.4

### FramedBlocks version

5.11.5

### Describe the bug

https://github.com/Fuzss/diagonalfences/issues/41

Updated mods to latest version and pressed start. Game attempts to load but then goes to NEC screen, crashes. 

### How to reproduce the bug

Uh... put DiagonalFences latest update and FramedBlocks in an 1.18.2 Forge modpack.
If that doesnt work, download my modpack Royal Equines: Petrified Magic and update all mods to latest (06.05.2023) via the profile management enabled option. 
Let me know if that still doesn't work. Will post a full mod list then.

### Expected behavior

Game loads

### Additional details

``java.lang.NoClassDefFoundError: fuzs/diagonalfences/api/IDiagonalBlock``

I think because the API changed (idk if that's the right term) the whole issue appeared in the first place. Old version of DiagonalFences works fine with my modpack and doesn't show this error.

### Crash log

https://gist.github.com/xFirefalconx/ff45e41a19e60bd2787538402b84caae

**Comment by XFactHD** [comment]
This looks like an oversight that happened while updating the 1.18 branch with the latest changes from the 1.19 development, though I'd need @Fuzss to confirm whether this API break was intentional.

**Comment by Fuzss** [comment]
Yeah, it's an oversight, I'll fix it on my end.

**Comment by XFactHD** [comment]
Thank you for the confirmation. I'll leave the issue open until you've had a chance to upload an update (which most likely won't be anytime soon due to the ongoing situation on CurseForge).

**Comment by XFactHD** [comment]
The crash issue is fixed in DiagonalFences 3.2.1. The visual issue Fuzss mentioned in https://github.com/Fuzss/diagonalfences/issues/41 will be addressed separately

**Comment by XFactHD** [comment]
The visual issue has been fixed in DiagonalFences 3.2.2
