### ISSUE TITLE
[Crash]: Game crashing when using Effortless Building

### ISSUE THREAD

**Issue by TheBarnyOfBarnim** [XFactHD/FramedBlocks#278]
### Minecraft version

1.19

### Forge version

43.2.8

### FramedBlocks version

6.8.4

### Describe the bug

When using another mod named Effortless Building (2.40) the game crashes when holding any Framed block in hand.
I use Optifine (1.192. HD U 11), but does not seem like to affect crash

### How to reproduce the bug

1. Craft a Framed Block.
2. Select a Placement mod in Effortless Building (e.g. Line)
3. Game crashes

### Expected behavior

Game not crashing

### Crash log

https://gist.github.com/TheBarnyOfBarnim/53e4284101cb178b2d9ce8a66d0f9c1b

**Comment by XFactHD** [comment]
This is a bug in Effortless Building which has been reported to them a few months ago. I have added a bit more detail to the report on their tracker in the hopes of this being fixed soon: https://bitbucket.org/Requios/effortless-building/issues/145.
Unfortunately there is nothing more that I can do about this.

**Comment by Totomio** [comment]
Is it possible to make the fix ourself in the solutions you discribed in his mod for a personnal use ? Sorry i'm a noob.

**Comment by XFactHD** [comment]
If you have sufficient knowledge of Java and the Minecraft code, then you could technically do that and their license would allow it. If you don't, then you won't get far.

**Comment by XFactHD** [comment]
This issue has been fixed by Effortless Building in version 3.0 and later.
