### ISSUE TITLE
[Feature]: Framed Slope Corner Panel & Framed Extended Slope Corner Panel

### ISSUE THREAD

**Issue by blahpers** [XFactHD/FramedBlocks#281]
### Describe the feature

Greetings!

I see that we can use framed slope panels and framed extended slope panels to make, e.g., a nice upward-pointing apex for a Washington Monument-style fixture.  However, unlike the regular framed slopes, there don't appear to be corresponding corner pieces for these panels.

Any chance of adding them in a future update?

**Comment by XFactHD** [comment]
Duplicate of #156.
The missing corners are being worked on right now. I can't promise you when exactly they will be released though.

**Comment by blahpers** [comment]
Sweet, thank you!
