### ISSUE TITLE
[Feature]: Config Option to not consume block when making framed block look like another block

### ISSUE THREAD

**Issue by 321nick** [XFactHD/FramedBlocks#283]
### Describe the feature

As the title says, right now when you right click on a framed block, it consumes the block in hand to make the framed block look like another block. Id like it so theres a config option, which when enabled ,makes setting the apperance of a framed block not consume the block in your hand. And when this config option is set, breaking framed blocks set to look like another block also doesnt drop the block that its appearance is set to, which they do now. 

This way, if i have an expensive block i want to make my base look like, i dont have to make a bunch of them, i can just make 1 of them and a bunch of framed blocks.

**Comment by XFactHD** [comment]
I'm a bit divided on this because in my eyes it makes it too easy to use this mod. But since it's trivial to implement and I can also see the argument for it, I'm going to add it regardless.
