### ISSUE TITLE
[Feature]: Double Slope Slab

### ISSUE THREAD

**Issue by superbrotherx4** [XFactHD/FramedBlocks#284]
### Question

What I want is the framed double slope slab, except I want it to be one block texture rather than two separate. I want it because it causes a plane in the middle to be rendered when used with glass, which is something that doesn't happen if you use two of the individual slopes on the block boundary. The two attached pictures (hopefully) should show just the double slope slab, and then two individuals without the issue. Is this a thing that exists? Is it for some reason impossible? I might be missing something important (like some brain cells) but would honestly appreciate the help. Thanks in advance.
![2023-07-11_16 44 26](https://github.com/XFactHD/FramedBlocks/assets/39819700/3a0073bb-2927-4453-88f2-b7c968f90025)
![2023-07-11_16 45 06](https://github.com/XFactHD/FramedBlocks/assets/39819700/77796381-03d3-46b5-afc1-24306ef621dc)

**Comment by XFactHD** [comment]
This is absolutely possible to implement, it just doesn't exist at the moment because it didn't come to my mind yet for some reason. I'll add it to the list of planned features.

**Comment by superbrotherx4** [comment]
Awesome! Thank you much. I would also appreciate if it came with the vertical version as well, as that's actually the version I'm trying to use. Awesome work!

**Comment by XFactHD** [comment]
Yes, that was the goal. Just making it for one but not the other would be a bit silly 😄
