### ISSUE TITLE
[Feature]: Framed divided panel double stairs

### ISSUE THREAD

**Issue by rockett1** [XFactHD/FramedBlocks#285]
### Describe the feature

![image](https://github.com/XFactHD/FramedBlocks/assets/1695078/244b1159-45b3-49f1-ad8e-daf1660f0324)
Please may I request you create a "Framed divided panel stairs" block? It would make for some incredibly lovely thin walls.

The block I am attempting to describe would basicaly be a "framed double stairs" block but cut in half so it would fit on the corner without sticking out.

![image](https://github.com/XFactHD/FramedBlocks/assets/1695078/6c6ba4e5-2ffc-454d-a9e5-e30b7100bfce)

![image](https://github.com/XFactHD/FramedBlocks/assets/1695078/2f018817-5d99-4863-bdd8-51d0ddab94b5)

At the moment there is no corner block for these so I am resorting to "framed double stairs"

Thanks for considering the request.

**Comment by rockett1** [comment]
![block edited](https://github.com/XFactHD/FramedBlocks/assets/1695078/6593f3be-7baa-4058-9829-06678e884a35)

I drew a crude diagram in paint of the part shaded in red that I would like cutting off. I hope it illustrates better than I was describing in the initial post.

**Comment by rockett1** [comment]
I have an additional block request, removing the bit in red and keeping the bit in blue as a separate block material: 

![block request 2](https://github.com/XFactHD/FramedBlocks/assets/1695078/3c2cf11f-7c05-4456-b367-e45ab815fbf6)

 so it's basically a corner staircase but with 1/8th of the blocks being another material

**Comment by XFactHD** [comment]
I can see the use for the first block, I'll add that to the list of planned blocks.
Can you elaborate on the usefulness of the second block? It seems extremely niche to me and hard to justify the effort.

**Comment by rockett1** [comment]
I would just ignore my second request. Very excited to have the first block implemented in a future update! cant wait!

**Comment by superbrotherx4** [comment]
![2023-07-16_00 21 01](https://github.com/XFactHD/FramedBlocks/assets/39819700/6610891e-d95f-4001-b1b0-a72bc910551a)
This is a case where I could use that 1/8th of a block being different, as I'd rather have the little corner at the bottom match the black tiles, but my specific case would get solved by horizontally divided stairs as well, and so I think the corner one might be a little too niche

**Comment by XFactHD** [comment]
That's very niche and would also require a large amount of variations, so that's not going to happen unfortunately.
