### ISSUE TITLE
[Bug]: Crash

### ISSUE THREAD

**Issue by Endmateria** [XFactHD/FramedBlocks#287]
### Minecraft version

1.2

### Forge version

47.1.39

### FramedBlocks version

FramedBlocks-9.0.2.jar

### Describe the bug

The newest "FramedBlocks-9.0.2.jar" crashes against the newest Optifine "preview_OptiFine_1.20.1_HD_U_I6_pre3".  The same Optifine version does not crash with "FramedBlocks-9.0.0".  No other mods/datapacks installed.

### How to reproduce the bug

Install FramedBlocks-9.0.2.jar.
Install Optifine preview_OptiFine_1.20.1_U_I6_pre3.
Launch Minecraft.
Crash on startup.
Exit Code 1.

### Expected behavior

Game launch.

**Comment by XFactHD** [comment]
Please put the crash report on a paste site (i.e. https://gist.github.com) and put a link to it in the "Crash log" section as requested by the template.

**Comment by Endmateria** [comment]
Weird, I just tried re-creating these exact circumstances I noted above and it's launching consistently now, whereas it crashed at launch three times yesterday with no crashlogs.  Haven't changed any configs either.  Maybe the Twitch/Curseforge Modloader was just crapping out or there was a second instance of the Minecraft launch screen running in the background.  I'll close this issue, sorry if I wasted any of your time.  While I'm here though, thanks for making/keeping this mod updated... I know it's probably a pain in the ass to do so, but it's appreciated.

**Comment by XFactHD** [comment]
No worries, glad you could resolve it. As a side note: if the game doesn't produce a crashreport, then the best option is to provide the normal game logs as those almost always contain at least some hint regarding the cause.

I'm happy you like the mod. Rest assured that I wouldn't be doing this if it weren't fun.

**Comment by Endmateria** [comment]
Here, I think these were the log files from those crashes, though redundant at this point, maybe they'll provide some use. https://gist.github.com/Endmateria/33f79189302ab70d4859c69b46ea9f46#file-2023-07-20-1-log

**Comment by XFactHD** [comment]
These logs are from the issue that was fixed by version 9.0.2. Thank you nonetheless though.

I did a quick check with the versions you mentioned in your report and found that your issue was very likely caused by OptiFine being incompatible with the Forge version you were using. When using OptiFine, you have to make sure to use the exact version of Forge mentioned as compatible on the OptiFine download page.
