### ISSUE TITLE
[Feature]: Ability to place framed slabs in the same block as another slab frame

### ISSUE THREAD

**Issue by ArcTrooper210** [XFactHD/FramedBlocks#289]
### Describe the feature

Feature: This goes for panels as well. You should be able to place another half slab variant of a frame in the same block that another framed slab variant is in. Currently if you try to place them together it will just place in front

![2023-07-21_15 51 01](https://github.com/XFactHD/FramedBlocks/assets/69335775/7ee3e42f-1395-45e9-a14d-45a4e9a01552)

In the image below what would happen is the diamond slab would be right under the diamond slope slab. And on the right the gold block panel would be right under the gold slope panel
![2023-07-21_15 55 16](https://github.com/XFactHD/FramedBlocks/assets/69335775/df8c63c3-f268-4186-947b-301a17099701)

**Comment by XFactHD** [comment]
This already exists in the form of the Framed Elevated Slope Slab and Framed Extended Slope Panel for single camos and the Framed Stacked Slope Slab and Framed Stacked Slope Panel for two camos. These have to be crafted separately though and cannot be combined in the world.
