### ISSUE TITLE
[Feature]: Port to Fabric

### ISSUE THREAD

**Issue by FefitoGaming** [XFactHD/FramedBlocks#290]
### Describe the feature

is there like a possibility to port this mod to fabric?

**Comment by XFactHD** [comment]
There are currently no concrete plans for a Fabric port, mainly due to the significant amount of work involved in such a port.

**Comment by DCI-Mage** [comment]
@XFactHD can’t you use multiloader apis such as architectury api?

**Comment by XFactHD** [comment]
See my response on #305
