### ISSUE TITLE
Glass panes in framed blocks.

### ISSUE THREAD

**Issue by unweeked** [XFactHD/FramedBlocks#296]
### Describe the feature

Maybe you could make it possible to place glass panes (or framed panes) into framed blocks to make stuff like this possible:
![dps3t4r8mw851](https://github.com/XFactHD/FramedBlocks/assets/96650761/900886d6-e6b8-43a2-8c44-7d0dff738b9f)

**Comment by XFactHD** [comment]
This is very unlikely to be added due to the significant complexity involved in making that work nicely with all blocks it would make sense for. I'd be curious which mod was used to create that screenshot.

**Comment by XFactHD** [comment]
I've looked into this a bit further and it's unfortunately not feasible to implement.
