### ISSUE TITLE
[Feature]: Sloped Edge Block

### ISSUE THREAD

**Issue by HeVeZz** [XFactHD/FramedBlocks#298]
### Describe the feature

Not much more to explain other than what the title states, having a sloped edge block will really help with designs for create trains, if possible a half/half version too

**Comment by XFactHD** [comment]
Am I correct in assuming that you mean a block like the Framed Slab Edge in terms of size but as a slope? If that's the case, then I'll add it to the planned blocks.

**Comment by HeVeZz** [comment]
Yes that would be correct, i have no way of presenting it in a pictorial format, Thank you

**Comment by Feliixtc** [comment]
I'd like to add a companion block to this request: I think, via the naming scheme, it would be a Framed Small Prism Corner Slope Panel.
![Block Request](https://github.com/XFactHD/FramedBlocks/assets/22123597/fd76684a-853a-4dba-b3ef-6c03efe02a72)
HeVezz's request would be the horizontal version of the ghost white block. Mine would be the ghost yellow.

**Comment by XFactHD** [comment]
Seems useful to me, I'll include it when I implement #226 as it falls under the umbrella of the suggestion in that issue.

**Comment by YukkiPlays** [comment]
I was also looking for opening this exact enhancement request. That would allow me to build Clean Hexagons for my Bee farm :D

**Comment by mikerooni** [comment]
As another companion block, I'd like to suggest the exact "opposite" of the sloped edge block.

In this picture, the one on the left would be the side view of the block I'm suggesting, while the one on the right would be the sloped edge block:
![image of the two blocks in question](https://github.com/XFactHD/FramedBlocks/assets/139889766/81079f3c-7409-4907-8357-e647814ce41c)

**Comment by Feliixtc** [comment]
> As another companion block, I'd like to suggest the exact "opposite" of the sloped edge block.
> 
> In this picture, the one on the left would be the side view of the block I'm suggesting, while the one on the right would be the sloped edge block. 

Indeed. I’d just assumed there would also be a horizontal version of the block added as well.

**Comment by XFactHD** [comment]
Both the opposing block as well as horizontal versions of both blocks are planned.
