### ISSUE TITLE
Can you let the Framed Slope be placed upside down?

### ISSUE THREAD

**Issue by dajiuji** [XFactHD/FramedBlocks#30]
Can you let the Framed Slope be placed upside down?He can only be placed upright or placed vertically, not upside down.

**Comment by XFactHD** [comment]
What version of Minecraft, Forge and FramedBlocks are you using?
Please provide a forced crash report (hold F3 + C for 10 seconds) via pastebin.com or gist.github.com.

The Framed Slope can already be placed upside down by placing it on the underside of another block or (starting with version 2.8.0) by targetting the upper 1/5 of the side of another block when placing the slope.

**Comment by dajiuji** [comment]
> 您使用的是什么版本的 Minecraft、Forge 和 FramedBlocks？
> 请通过 pastebin.com 或 gist.github.com 提供强制崩溃报告（按住 F3 + C 10 秒）。
> 
> 框架斜坡已经可以通过将其放置在另一个块的底部或（从版本 2.8.0 开始）通过在放置斜坡时定位另一个块侧面的上部 1/5 来颠倒放置。

Ah, it was my fault. I updated the mod version, and now it can be upside down, but I have a new idea... Can I add a stackable frame? Like snow flakes?

**Comment by XFactHD** [comment]
There are "double" versions of certain blocks, namely slabs, panels, slopes and the three corner types.
More detailed combinations go into microblock territory, which is a route I am not going to go down.
