### ISSUE TITLE
[Bug]: Framed Blueprint consumes camo block even if disabled in config

### ISSUE THREAD

**Issue by Hiconel** [XFactHD/FramedBlocks#300]
### Minecraft version

1.2

### Forge version

47.1.44

### FramedBlocks version

9.0.3

### Describe the bug

I have disabled "Consume Camo Item" in the server config, but the Framed Blueprint still consumes the camo item.

### How to reproduce the bug

1. Set "Consume Camo Item" in server config to false.
2. Apply a camo item to any framed block.
3. Use the Framed Blueprint to copy the settings of the block.
4. Place a block with the blueprint and both the framed block as well as the camo item will be consumed.

### Expected behavior

The camo item should not be consumed by the blueprint, if disabled in the config.

**Comment by XFactHD** [comment]
Good catch, I totally overlooked the blueprint when I implemented that setting
