### ISSUE TITLE
[Bug]: infinite void on load

### ISSUE THREAD

**Issue by Nicodemus111** [XFactHD/FramedBlocks#301]
### Minecraft version

1.2

### Forge version

47.1.1

### FramedBlocks version

9.03

### Describe the bug

when i loaded into my world after setting up some farming plots i would infinitely fall into the void. when disabling framedblocks it did not have any issues.

### How to reproduce the bug

i am unsure of what exactly i did since i only used framed stairs and framed slabs with quartz bricks and glowstone. if it would help get this patched i can send the world file over and my modrinth profile.

### Expected behavior

it should load in normally

### Additional details

sidenote, the minecraft version dropdown in your form has 1.2 instead of 1.20

### Crash log

https://gist.github.com/Nicodemus111/f3b9bdab12fadbf5a3b0037b41e13df9

**Comment by Nicodemus111** [comment]
i did some more troubleshooting and it seems to only trigger when placing a waterlogged framed glowstone slab in the chunk coordinates 1 7 0 and rejoining. it might be tied to something else in the chunk since testing in those coordinates in new worlds has inconsistent results, but the chunk right next to the problem one in my world also triggers the loading issue.

**Comment by XFactHD** [comment]
Thank you for the detailed troubleshooting. The fact that it only affects blocks with glowstone narrows it down to a known issue: FramedBlocks is currently incompatible with Starlight. I have a fix in the pipeline but cannot release it at this time. For now, please try removing Starlight, that should fix it. Please let me know whether it does.

It's worth mentioning that Starlight has been basically obsoloted by the improvements to the light engine in vanilla, so you're not losing any relevant amount of performance by removing it: <https://gist.github.com/Spottedleaf/6cc1acdd03a9b7ac34699bf5e8f1b85c>

**Comment by Nicodemus111** [comment]
that makes sense, thanks

**Comment by XFactHD** [comment]
Version 9.1.0 was just released and includes a fix for this issue.
