### ISSUE TITLE
[Bug]: My games crash while minecraft loading is on end

### ISSUE THREAD

**Issue by TymqTPL** [XFactHD/FramedBlocks#303]
### Minecraft version

1.2

### Forge version

47.1.44

### FramedBlocks version

9.0.3

### Describe the bug

I try to play minecraft with some mods (~58), when minecraft loading is at end, game crashes and show the bug: 
Description: Unexpected error
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.player.LocalPlayer.m_6117_()" because "this.f_91074_" is null

I read some of crash report and in it is 
"Caused by: java.lang.NullPointerException: IStateCacheAccessor#framedblocks$getCache() called too early" and if I try to run game without Framed Blocks all works.

### How to reproduce the bug

I just try to run game

### Expected behavior

I think it's bug with player client (this is in bug) I add i have original buyed minecraft and I play in minecraft launcher with connection to wifi

### Crash log

https://gist.github.com/TymqTPL/69377e8b81f7649197e4b9e4e29e65cf

**Comment by XFactHD** [comment]
The crash report indicates that multiple other mods have also encountered loading errors. I'll need to see the entire latest.log to find out where the game runs into errors in the first place and why that triggers this specific crash in FramedBlocks

**Comment by TymqTPL** [comment]
Okay, i give you the entire log

**Comment by TymqTPL** [comment]
I'm sorry, but I don't know where is the entire logs, i have only that, that I give on gist, is it a special folder to the logs, or this is debug log?

**Comment by TymqTPL** [comment]
Okay, i remake this crash, and I get propably that, that You need: 
https://gist.github.com/TymqTPL/b312788ca8e0363ad575ecd023d58f7d

**Comment by XFactHD** [comment]
It looks like Valkyrien Skies is broken, please try removing it. If that doesn't fix it, then the next candidate would be Essential. If removing both of those doesn't fix it, then I'll need a new log with both of them removed.

**Comment by TymqTPL** [comment]
Okay, thak you very very much :)

**Comment by TymqTPL** [comment]
I check it and all is wroks! Two time I thank you real very very very much! You're the best! :)
