### ISSUE TITLE
[Bug]: Crash

### ISSUE THREAD

**Issue by justsomebodynew** [XFactHD/FramedBlocks#306]
### Minecraft version

1.2

### Forge version

47.1.0

### FramedBlocks version

9.1.0

### Describe the bug

[crash-2023-09-08_16.00.52-client.txt](https://github.com/XFactHD/FramedBlocks/files/12563437/crash-2023-09-08_16.00.52-client.txt)

### How to reproduce the bug

crash on startup

### Expected behavior

The game to start.

**Comment by XFactHD** [comment]
The crash report itself unfortunately provides no useful information in this case. Please provide the full latest.log on a paste site like https://gist.github.com

**Comment by justsomebodynew** [comment]
https://gist.github.com/justsomebodynew/8d11887d69fdb4d98d8728f6682fd5ab

**Comment by XFactHD** [comment]
This log does not contain any trace of a crash, it shows a clean startup and shutdown of the game. Please make sure to reproduce the crash and provide the log right after it crashed to make sure it contains the crash.

One detail I just noticed in your initial crash report is that you are using Forge 47.1.0. FramedBlocks 9.1.0 requires 47.1.3 though, so you'll have to update Forge. This will most likely also fix this issue. Please let me know whether it does.

**Comment by justsomebodynew** [comment]
Updating Forge fixed it.

**Comment by XFactHD** [comment]
Perfect, thank you for the feedback.
