### ISSUE TITLE
[Feature]: Framed Inner Threeway Corner Edge

### ISSUE THREAD

**Issue by 2001herne** [XFactHD/FramedBlocks#307]
### Describe the feature

Basically what is says in the title.
In the following diagram, the fist section is the lower half of a block, and the second is the upper half. Both diagrams represent a 1x1 space. an 'X' represents a filled section, and an empty section is not filled.
```
┌─┬─┐
│X│X│
├─┼─┤
│X│ │
└─┴─┘
┌─┬─┐
│X│ │
├─┼─┤
│ │ │
└─┴─┘
```

Would be usefull for joining two edge slabs at 90 degrees to a corner pillar - i.e. for adding some detail to the inside of a square corner. Ideally would have all 8 rotations (4 lower, 4 upside down)

**Comment by XFactHD** [comment]
I can see the usefulness of that, I'll add it to the planned blocks
