### ISSUE TITLE
[Feature]: Add a way to pick the item inside of framed item frame, like the vanilla one does

### ISSUE THREAD

**Issue by AlisonHuang777** [XFactHD/FramedBlocks#310]
### Describe the feature

When you middle click on the vanilla item frame (in creative mode), you can get what's inside of the item frame. But for framed item frame, you get the frame itself. Please add a way to do that like vanilla behavior.

**Comment by XFactHD** [comment]
I completely missed that detail when implementing the item frames, that's an easy fix.
