### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Sander437** [XFactHD/FramedBlocks#311]
### Minecraft version

1.19

### Forge version

all

### FramedBlocks version

all

### Describe the bug

when i try to play the mod via curseforge i get an error

### How to reproduce the bug

start the mod via the curseforge app

### Expected behavior

the game won't start

### Additional details

it doesn't happen on all devices

**Comment by TelepathicGrunt** [comment]
@Sander437 please reproduce the crash and give us the latest.log file. You can use a paste site like pastebin to share the contents of that file. The log file can be found in the logs folder above the mods folder

**Comment by XFactHD** [comment]
Closing due to lack of feedback.
If you decide to provide the necessary information at a later time, feel free to comment on this issue and I will reopen it if needed.
