### ISSUE TITLE
[Feature]: Additional feature to the Collapsable Block.

### ISSUE THREAD

**Issue by Feliixtc** [XFactHD/FramedBlocks#313]
### Describe the feature

I think it'd be nice to add a center change point?, hitbox?, whatever it would be called. When clicked it would change all 4 corners of the block at one time. It would make using them soo much faster.
![Collapsable Block hitbox](https://github.com/XFactHD/FramedBlocks/assets/22123597/98b98c9a-1fd0-4096-af3a-b5768440bd16)

**Comment by XFactHD** [comment]
I like this idea a lot, I'll put it in the plans for the next update after the one I just released.
