### ISSUE TITLE
[Bug]: framed item frame bug

### ISSUE THREAD

**Issue by michelle1574** [XFactHD/FramedBlocks#314]
### Minecraft version

1.19

### Forge version

43.2.23

### FramedBlocks version

6.8.4

### Describe the bug

When middle mouse clicked, it picks up the framed item frame, not the item in it.

### How to reproduce the bug

1. Place a framed item frame
2. Choose a block to frame with it
3. Place a map on it
4. Middle-mouse click (creative)

### Expected behavior

I would get the map, not the framed item frame item.

**Comment by XFactHD** [comment]
Duplicate of #310. This is fixed in FramedBlocks 6.8.6 and 9.1.1 for 1.19.2 and 1.20.1 respectively
