### ISSUE TITLE
[Bug]: Crash when exiting Framing Saw GUI

### ISSUE THREAD

**Issue by exceedinglyaverage** [XFactHD/FramedBlocks#316]
### Minecraft version

1.2

### Forge version

47.1.3

### FramedBlocks version

9.1.1

### Describe the bug

Game Crashes Client when on server when closing framed saw gui.

### How to reproduce the bug

Open framed saw gui on a server  (Possibly after opening Minecrafts recipe book, may have replicated it on single player map after doing so), then close window or hold shift when crafting

### Expected behavior

no crash

### Additional details

Also, 1.20 seems to be marked as 1.2

### Crash log

https://gist.github.com/exceedinglyaverage/170658fba4790fa76e68faf759134499

**Comment by exceedinglyaverage** [comment]
here is the full log
https://pastebin.com/hJc4DDx1

**Comment by XFactHD** [comment]
Welp, that's what I get for testing against a comparatively ancient JEI version. I'll release a hotfix shortly.
