### ISSUE TITLE
[Bug]: Crash with Sinytra Connector

### ISSUE THREAD

**Issue by L1neHypeR** [XFactHD/FramedBlocks#319]
### Minecraft version

1.19

### Forge version

47.1.3

### FramedBlocks version

9.1.0

### Describe the bug

![image](https://github.com/XFactHD/FramedBlocks/assets/145922134/82890c4b-1a97-4926-8fc4-f91574060b85)

### How to reproduce the bug

.

### Expected behavior

.

### Crash log

Error: java.lang.IncompatibleClassChangeError: Conflicting default methods: net/minecraftforge/common/extensions/IForgeBlock.getAppearance net/fabricmc/fabric/api/block/v1/FabricBlock.getAppearance xfacthd/framedblocks/api/block/IFramedBlock.getAppearance

**Comment by XFactHD** [comment]
Please report this to [Connector](https://github.com/Sinytra/Connector), this needs to be fixed on their end, there is nothing I can do about this.
