### ISSUE TITLE
Texture/Render break with shaders (Optifine) 

### ISSUE THREAD

**Issue by MMDGLaDOS** [XFactHD/FramedBlocks#32]
Versions Effected: 1.16.5 Versions
it seems that if anyone uses any type of shader the blocks textures will break into a glitchy mess, this effect also transfers to the block used on it as camo, is there any possible fix for this that could be implemented? in the link here ill show a picture of what is going on while a shader is in use with all blocks in the frame as well as the shader's name as well a name of the blocks effect will also be provided
[https://prnt.sc/18qpvp3](url)
Block of Effected names: Framed Slope, Framed Inner Corner Slope, Framed Corner Slope, Framed Prism Corner, Framed Threeway Corner, Framed Double Slope, Framed Inner Threeway Corner, Framed Sign
Name of Shader: Sildurs Vibrant Shaders v1.29 Lite
EDIT: I found out its a Render Issue from what me and my friends think

**Comment by XFactHD** [comment]
OptiFine is not supported. Due to OptiFine being closed source there is no way for me to debug and fix this.
