### ISSUE TITLE
[Feature]: Framed collapsible copycat block

### ISSUE THREAD

**Issue by AlisonHuang777** [XFactHD/FramedBlocks#320]
### Describe the feature

This suggestion takes a different approach about #302. I suggests adding a new block (which name is described in the title) whose length, width and height are (the only things that are) configurable (to ensure its final shape is always a rectangular cuboid) by clicking/shift-clicking corresponding side with a framed hammer, similar to framed collapsible block. That way, it is ensured that each face of the block will be a rectangle, thus prevent copycat rendering from breaking.

**Comment by AlisonHuang777** [comment]
_(I'm not sure how copycat rendering deals with textures, though. I'm assuming that it can handle all possible rectangular area no bigger than 16x16 pixels.)_

**Comment by XFactHD** [comment]
This is a significantly more viable option, I'll look into getting this to work
