### ISSUE TITLE
[Bug]: Game crashes because of framed blocks

### ISSUE THREAD

**Issue by fromage222** [XFactHD/FramedBlocks#324]
### Minecraft version

1.2

### Forge version

atm 9

### FramedBlocks version

9.1.2

### Describe the bug

If i try to join my server I´m on the server for 1 second afterwards the game crashes.
That happens to all players that are coming close to my building wit the half framed blocks.

Crash: https://mclo.gs/WqLbTLy

### How to reproduce the bug

Join the Server or go to the building

### Expected behavior

If possible fix with the next update or a work around

### Crash log

https://mclo.gs/WqLbTLy

**Comment by XFactHD** [comment]
New version with the fix has just been approved on CurseForge
