### ISSUE TITLE
[Bug]: Crash when launching

### ISSUE THREAD

**Issue by Kotyarendj** [XFactHD/FramedBlocks#325]
### Minecraft version

1.2

### Forge version

47.2.0

### FramedBlocks version

9.1.3

### Describe the bug

When launching with my other mods it just crashes after Forge starts loading mod process. I've tried other versions of mod and Forge, but the weird thing it works normally for my friend who has same mods.

### How to reproduce the bug

Can't find a way to reproduce

### Expected behavior

I expected it to _load_

### Crash log

https://gist.github.com/Kotyarendj/733108e24bec5bc4c43d1b96606fab22

**Comment by XFactHD** [comment]
Please provide the full latest.log. The crash report unfortunately doesn't provide any useful information in this case.

**Comment by Kotyarendj** [comment]
You can check the revisions tab, I have originally provided latest.log but then changed it to report

**Comment by XFactHD** [comment]
Ah, thank you. I've managed to reproduce the issue and I have a fix that should prevent this once and for all which I'll release in a few minutes. If it somehow doesn't fix it, then please get back to me with a new log and I'll take another look.
