### ISSUE TITLE
Framed Fences Missing Break Particles

### ISSUE THREAD

**Issue by WenXin20** [XFactHD/FramedBlocks#33]
`Minecraft v1.16.5`
`Forge v36.1.32`
`Framed Blocks v2.9.0`

Empty Framed Fences are missing textures for their breaking particles.

![2021-07-05_16 36 26](https://user-images.githubusercontent.com/12000593/124519516-284bbe80-ddaf-11eb-8f04-009b488d385b.png)

**Comment by XFactHD** [comment]
I can't reproduce this.
If you have Sodium installed, can you reproduce this without it?

**Comment by WenXin20** [comment]
I'll give it a try. I also have diagonal fences installed, as the fence is the only one I've noticed missing break particles.

**Comment by XFactHD** [comment]
I tried it in a normal MC instance with DiagonalFences and can't reproduce this there either.

**Comment by WenXin20** [comment]
Oh odd. I'll try without sodium tomorrow

**Comment by WenXin20** [comment]
Ok, with only this mod, Diagonal Fences, and PuzzlesLib installed, and I still got the missing particles. No block is placed in the Framed Fence. Sodium was not installed. The bug stops after removing the mod Diagonal Fences.

I also realized that the block placement preview doesn't work when Sodium Reforged is installed, is that a bug?

![2021-07-06_10 34 27](https://user-images.githubusercontent.com/12000593/124628122-cb4f1780-de45-11eb-897e-a837e11a4bf3.png)

**Comment by XFactHD** [comment]
Which version of PuzzlesLib and Diagonal Fences are you using?

The block placement preview not working with Sodium is a result of a crash mitigation. The hook I use to render that preview can't be injected when Sodium is installed because it completely overwrites the method I am hooking into.

**Comment by WenXin20** [comment]
Found this error in the log only when Diagonal Fences is installed.
```
Exception loading blockstate definition: 'framedblocks:blockstates/framed_fence.json' missing model for variant: 'framedblocks:framed_fence#east=false,north=true,north_east=false,north_west=true,south=false,south_east=false,south_west=true,waterlogged=true,west=true'
```

**Comment by WenXin20** [comment]
`Diagonal Fences v1.1.1` & `PuzzlesLib v1.0.7`

**Comment by WenXin20** [comment]
> The block placement preview not working with Sodium is a result of a crash mitigation. The hook I use to render that preview can't be injected when Sodium is installed because it completely overwrites the method I am hooking into.

Ah, I see

**Comment by XFactHD** [comment]
Please send me the log containing that error via pastebin or gist.github.com

**Comment by WenXin20** [comment]
Oh right.
https://gist.github.com/WenXin20/981f10251288fcaab7ca9e63db3c0e58

**Comment by XFactHD** [comment]
I can reproduce this now aswell. This error is extremely weird: It is complaining about a file not existing that definetely exists in the jar. I will have to take a deeper look into this.

**Comment by WenXin20** [comment]
Yeah, definitely odd

**Comment by XFactHD** [comment]
Found the problem: I removed a lot of unnecessary model data in the last update which the resource generator in Diagonal Fences didn't like.
I don't know yet when the next update with this fix will come out though.

**Comment by WenXin20** [comment]
Alright, no problem
