### ISSUE TITLE
[Bug]: Framed Item Frame destroys item when breaking attached block

### ISSUE THREAD

**Issue by c0rphan** [XFactHD/FramedBlocks#330]
### Minecraft version

1.20

### Forge version

forge-1.20.1-47.1.3

### FramedBlocks version

FramedBlocks-9.1.5

### Describe the bug

When breaking the block the Framed Item Frame is attached to, the frame and the block that was used for appearance are dropped, but the item in the frame does not drop.

### How to reproduce the bug

- Place framed item frame on a block
- (optional) Place a block on the framed item frame to set the appearance
- Place an item in the item frame
- Break the block the framed item frame is attached to

### Expected behavior

The item in the framed item frame should also drop

**Comment by XFactHD** [comment]
How did I miss this...
