### ISSUE TITLE
[Bug]: Crash while connecting to server updated from 1.19.2 [with mod Create]

### ISSUE THREAD

**Issue by Pecl-ffdd** [XFactHD/FramedBlocks#331]
### Minecraft version

1.2

### Forge version

47.2.1

### FramedBlocks version

9.1.5

### Describe the bug

So, I created server on 1.19.2. I added mods like Create, Framed Blocks and others. Today I updated it to 1.20.1 and updated all mods. I connected to the server and it was ok but randomly minecraft crashed. I thinked it will be ok if it crashes once a time. Then I was riding a train when it crashed. I connected back, it was loading, I saw some grass in the game and it crashed again and again. I don't know why, maybe it's because an (train) entity with framed blocks. I didn't really know what was meant by "Remove state metadata caches". I didn't found "state" or "metadata" or "caches" on the server and in %appdata%\.minecraft I removed every folder that contained on of these words. Thanks for help.

### How to reproduce the bug

I don't know.

### Expected behavior

I expected to not crash.

### Crash log

https://mclo.gs/PWhM7f8

**Comment by XFactHD** [comment]
That's a really strange one, that will take some digging to find out why this happens. For now, try setting `conTexMode = "NONE"` in the `framedblocks-client.toml` config file, that should prevent the crash.

**Comment by XFactHD** [comment]
I've pushed an update (FramedBlocks 9.1.6) which prevents this crash and adds additional logging. Please update to that version without applying the workaround I suggested earlier, enter the affected world or server and then provide the client's latest.log (preferably through https://gist.github.com). Screenshots of the structures using framed blocks in the area would be very useful as well, my guess would also be that this is related to Create contraptions or trains.

**Comment by Pecl-ffdd** [comment]
I think the problem was the train. Tt was loading, I saw some framed blocks in 3rd car/wagon. Then I tried to kill one (train) entity and it didn't crash to now.

**Comment by Pecl-ffdd** [comment]
And one thing, I don't want to create new issue. In the 1.20.1 version of FramedBlocks you can open trapdoors in (train) entity. We have a lot of trains and replacing all of the trapdoors with something isn't something I would like to do. So I suggest: Can you add boolean option in settings where you can disable operating with framed blocks when they are in entity? When the option is disabled it should act something like in Framed Blocks version 6.8.3.

**Comment by XFactHD** [comment]
> I think the problem was the train. Tt was loading, I saw some framed blocks in 3rd car/wagon. Then I tried to kill one (train) entity and it didn't crash to now.

Does the game's log contain anything along the lines of `AppearanceHelper#getAppearance() trying to recurse multiple times, this is a bug.`? If it does, then please provide the log as requested so I can look into fixing this properly.

> And one thing, I don't want to create new issue. In the 1.20.1 version of FramedBlocks you can open trapdoors in (train) entity. We have a lot of trains and replacing all of the trapdoors with something isn't something I would like to do. So I suggest: Can you add boolean option in settings where you can disable operating with framed blocks when they are in entity? When the option is disabled it should act something like in Framed Blocks version 6.8.3.

Please always make new issues for things entirely unrelated to the existing issue, this is an issue tracker after all and not an open chat like Discord.

**Comment by Pecl-ffdd** [comment]
This is the log: [https://mclo.gs/PWhM7f8](url) and in the log file I found just `at TRANSFORMER/framedblocks@9.1.5/xfacthd.framedblocks.api.block.render.AppearanceHelper.getAppearance(AppearanceHelper.java:43)` and `at xfacthd.framedblocks.api.block.render.AppearanceHelper.getAppearance(AppearanceHelper.java:43) ~[FramedBlocks-9.1.5.jar%23178!/:9.1.5]`

**Comment by XFactHD** [comment]
Posting the exact same crash report doesn't help me in any way. I need the full game log (`<game directory>/logs/latest.log`) after you've upgraded FramedBlocks to 9.1.6, assuming it contains *exactly* the sentence I quoted before.

**Comment by XFactHD** [comment]
Closing due to lack of feedback
