### ISSUE TITLE
[Mod Support]: Create 1.16 contraption

### ISSUE THREAD

**Issue by lm4mine** [XFactHD/FramedBlocks#332]
### The mod to integrate with

Create mod

### Describe the feature

Having texture staying on create contraption, like the next version of the mod if it is possible

**Comment by XFactHD** [comment]
This would require the Create devs to backport a change which made this possible in the first place on their end but as far as I'm aware they have also dropped support for 1.16. There is nothing I can do to make this work and apart from that I have dropped support for anything older than 1.19.2 anyway.
