### ISSUE TITLE
[Feature]: Quoin blocks, i.e. two Framed Divided Slabs stacked at right angles.

### ISSUE THREAD

**Issue by mozartbeatle** [XFactHD/FramedBlocks#333]
### Describe the feature

Stack two divided slabs in a specific way and make any castle/stone building you build look 10x more real/aesthetic.

Somewhat niche, but as a niche decorative block this could be of immeasurable usefulness in a great many build types that emulate masonry building styles. Been jonesing for a block like this since 2012.

![2023-10-22_07 58 31](https://github.com/XFactHD/FramedBlocks/assets/81265997/8a551e26-5610-49d4-b9a6-6652a9e72596)

![2023-10-22_07 54 17](https://github.com/XFactHD/FramedBlocks/assets/81265997/b67e9530-0e7a-4ef9-929c-21343f85181b)

(Edited)
<img width="512" alt="2023-10-22_07 37 25" src="https://github.com/XFactHD/FramedBlocks/assets/81265997/5de7e550-f81c-4ab1-b194-9f1aada090e6">

Even if it's a no, I do want to thank you just in general for this mod. Incredible work.

**Comment by XFactHD** [comment]
I really like this idea and it's fairly simple to implement, I'll add it to the list of planned blocks.
