### ISSUE TITLE
[Feature]: Slope Wall Board and Floor Board

### ISSUE THREAD

**Issue by EpicProKillerFTW** [XFactHD/FramedBlocks#343]
### Describe the feature

Basically I'd like to see a slope/split variant of Wall Board and Floor Board. Example in the image below.

![image](https://github.com/XFactHD/FramedBlocks/assets/105395892/29ffb468-bf0b-4f23-9e5e-1cbb05e9f03e)

**Comment by XFactHD** [comment]
I can see the appeal of this, but I'm gonna say no for now as adding these two would create an expectation to have the same for other split shapes, which I currently do not have the capacity for (I currently have a backlog of roughly planned 70 blocks which I need to get through).
