### ISSUE TITLE
[Question]: How to apply camo blocks to Double Doors?

### ISSUE THREAD

**Issue by Gantros** [XFactHD/FramedBlocks#344]
### Question

I've been struggling to apply camo blocks to double Framed Iron Doors, and I cannot do so when the doors are paired, only when one has been placed. I attempted to use a Framed Blueprint to get around this, but no matter which block I used for the camo, the blueprint tells me I'm missing the camo block, making it impossible to place.

**Comment by XFactHD** [comment]
Hmm, that's an odd one, it should just work:tm:. The only case I've seen this is when a mod adds simultaneous double door opening, though that shouldn't apply to iron doors. Please provide a mod list so I can look into this further, preferably in the form of a debug crash report (press and hold F3+C until the game crashes, also works in the main menu) via https://gist.github.com.
As for the blueprint issue, I'll need to check that but I'll also need the mod list for that. In my testing it always worked fine.

If you want the same camo on both parts of the door, then you can hold the desired camo in your off-hand while placing the door as mentioned in a previous report about an almost identical issue: https://github.com/XFactHD/FramedBlocks/issues/84

**Comment by Gantros** [comment]
I am using Serilium's Double Doors mod, and your off hand workaround has worked.
Mods:
  [✔️] AdditionalPlacements-1.20-1.7.6.jar
  [✔️] AdLods-1.20.1-8.1.0.0-build.0142.jar
  [✔️] AI-Improvements-1.20-0.5.2.jar
  [✔️] AirHop-v8.0.0-1.20.1-Forge.jar
  [✔️] alexscaves-1.0.8.jar
  [✔️] alexsmobs-1.22.5.jar
  [✔️] almostunified-forge-1.20.1-0.7.2.jar
  [✔️] animal_feeding_trough-1.0.3+1.20.1-forge.jar
  [✔️] appleskin-forge-mc1.20.1-2.5.0.jar
  [✔️] architectury-9.1.11-forge.jar
  [✔️] athena-forge-1.20.1-3.1.1.jar
  [✔️] balm-forge-1.20.1-7.1.4.jar
  [✔️] bellsandwhistles-0.4.3-1.20.x.jar
  [✔️] BetterBeekeeping-1.20.1-1.3.0.jar
  [✔️] bettercombat-forge-1.8.1+1.20.1.jar
  [✔️] betterdays-1.20.1-3.1.0.3-FORGE.jar
  [✔️] better-respawn-forge-1.20.1-2.0.3.jar
  [✔️] betterspawnercontrol-1.20.1-4.3.jar
  [✔️] bigbrain-1.20-1.7.3.jar
  [✔️] Bookshelf-Forge-1.20.1-20.1.6.jar
  [✔️] brazier-forge-6.1.1.jar
  [✔️] buildersaddition-1.20.1-20230928a.jar
  [✔️] BuildGuide-1.20-0.3.3.jar
  [✔️] Butchersdelight+beta+1.20.1+2.0.8f.jar
  [✔️] carryon-forge-1.20.1-2.1.2.7.jar
  [✔️] chalk-1.20.1-1.6.3.jar
  [✔️] charmofundying-forge-6.4.4+1.20.1.jar
  [✔️] chickensshed-1.4.0-0.jar
  [✔️] chunksending-fabric-1.20.1-2.8.jar
  [✔️] citadel-2.4.9-1.20.1.jar
  [✔️] cloth-config-11.1.106-forge.jar
  [✔️] Clumps-forge-1.20.1-12.0.0.3.jar
  [✔️] collective-1.20.1-7.9.jar
  [✔️] comforts-forge-6.3.4+1.20.1.jar
  [✔️] Continents_1.20.2_v1.1.3.jar
  [✔️] corpse-1.20.1-1.0.3.jar
  [✔️] create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.7.g.jar
  [✔️] create_jetpack-forge-4.1.1.jar
  [✔️] create_recycle_1.0.2_forge_1.20.1.jar
  [✔️] create-1.20.1-0.5.1.f.jar
  [✔️] CreativeCore_FORGE_v2.11.5_mc1.20.1.jar
  [✔️] cristellib-1.1.3-forge.jar
  [✔️] cryingportals-1.20.1-2.4.jar
  [✔️] cupboard-1.20.1-2.1.jar
  [✔️] curios-forge-5.4.4+1.20.1.jar
  [✔️] dismountentity-1.20.1-3.1.jar
  [✔️] DistractingTrims-Forge-1.20.1-2.0.3.jar
  [✔️] domesticationinnovation-1.7.0-1.20.jar
  [✔️] doubledoors-1.20.1-5.1.jar
  [✔️] DramaticDoors-QuiFabrge-1.20.1-3.1.3_3.jar
  [✔️] EasyAnvils-v8.0.1-1.20.1-Forge.jar
  [✔️] effortlessbuilding-1.20.1-3.6-all.jar
  [✔️] embeddium-0.2.10+mc1.20.1.jar
  [✔️] embeddiumplus-1.20.1-v1.0.1.jar
  [✔️] EnchantmentDescriptions-Forge-1.20.1-17.0.9.jar
  [✔️] enchantmenttransfer-0.0.6-1.20.1.jar
  [✔️] endportalrecipe-1.20.1-5.1.jar
  [✔️] entityculling-forge-1.6.2-mc1.20.jar
  [✔️] ExplorersCompass-1.20.1-1.3.3-forge.jar
  [✔️] FarmersDelight-1.20.1-1.2.3.jar
  [✔️] FastSuite-1.20.1-5.0.1.jar
  [✔️] ferritecore-6.0.1-forge.jar
  [✔️] ForgeEndertech-1.20.1-11.1.0.0-build.0142.jar
  [✔️] FramedBlocks-9.1.6.jar
  [✔️] functionalarmortrim-1.20.1-4.jar
  [✔️] geckolib-neoforge-1.20.1-4.2.4.jar
  [✔️] Grass_Overhaul-Forge-23.10.10-MC1.20.1.jar
  [✔️] hole_filler_mod-1.2.8_mc-1.20_forge.jar
  [✔️] Incendium_1.20.2_v5.3.2.jar
  [✔️] interiors-0.5.2+mc1.20.1-FORGE.jar
  [✔️] InventoryProfilesNext-forge-1.20-1.10.6.jar
  [✔️] Jade-1.20.1-forge-11.6.3.jar
  [✔️] JadeAddons-1.20.1-forge-5.2.0.jar
  [✔️] jei-1.20.1-forge-15.2.0.27.jar
  [✔️] justenoughbreeding-forge-1.20.x-1.0.9.jar
  [✔️] Kiwi-1.20.1-forge-11.1.1.jar
  [✔️] kotlinforforge-4.5.0-all.jar
  [✔️] LeavesBeGone-v8.0.0-1.20.1-Forge.jar
  [✔️] libIPN-forge-1.20-3.0.2.jar
  [✔️] libraryferret-forge-1.20.1-4.0.0.jar
  [✔️] liquidburner-1.20.1-0.5.jar
  [✔️] lmft-1.0.4+1.20.1-forge.jar
  [✔️] mcw-bridges-2.1.1-mc1.20.1forge.jar
  [✔️] mcw-fences-1.0.7-mc1.20.1forge.jar
  [✔️] mcw-lights-1.0.6-mc1.20.1forge.jar
  [✔️] merenc-forge-1.20.x-v3.2.jar
  [✔️] modernfix-forge-5.9.3+mc1.20.1.jar
  [✔️] moonlight-1.20-2.8.66-forge.jar
  [✔️] moveboats-1.20.1-3.0.jar
  [✔️] NaturesCompass-1.20.1-1.11.2-forge.jar
  [✔️] netherportalfix-forge-1.20-13.0.0.jar
  [✔️] Nullscape_1.20.2_v1.2.3.jar
  [✔️] nutritiousmilk-1.20.1-3.1.jar
  [✔️] obsidianui-0.1.2+1.20.1.jar
  [✔️] Patchouli-1.20.1-82-FORGE.jar
  [✔️] Placebo-1.20.1-8.5.8.jar
  [✔️] player-animation-lib-forge-1.0.2-rc1+1.20.jar
  [✔️] polymorph-forge-0.49.1+1.20.1.jar
  [✔️] prettybeaches-forge-1.20-11.0.1.jar
  [✔️] PuzzlesLib-v8.1.9-1.20.1-Forge.jar
  [✔️] radiantgear-forge-2.1.2+1.20.1.jar
  [✔️] RainShield-1.20.1-1.1.2.jar
  [✔️] realisticbees-1.20.1-3.4.jar
  [✔️] recipeessentials-1.20.1-3.2.jar
  [✔️] redstonepen-1.20.1-neoforge-1.3.22.jar
  [✔️] reefredux-1.20.1-1.1.1.jar
  [✔️] resourcefullib-forge-1.20.1-2.1.11.jar
  [✔️] rubidium-extra-0.5.3.1+mc1.20.1-build.110.jar
  [✔️] Ryoamiclights-0.1.5+1.20.1.jar
  [✔️] saturn-mc1.20.1-0.0.7.jar
  [✔️] scaffoldingdropsnearby-1.20.1-3.0.jar
  [✔️] seasonhud-forge-1.20.1-1.6.2.jar
  [✔️] SereneSeasons-1.20.1-9.0.0.46.jar
  [✔️] sliceanddice-forge-3.2.0.jar
  [✔️] smoothchunk-1.20.1-3.3.jar
  [✔️] SoLOnion_FORGE_v1.1.3_mc1.20.1.jar
  [✔️] sophisticatedbackpacks-1.20.1-3.18.68.952.jar
  [✔️] sophisticatedcore-1.20.1-0.5.107.496.jar
  [✔️] spyglassofcurios-forge-1.20.1-1.5.1.jar
  [✔️] Steam_Rails-1.5.3+forge-mc1.20.1.jar
  [✔️] storagedrawers-1.20.1-12.0.2.jar
  [✔️] supplementaries-1.20-2.6.31.jar
  [✔️] tact-1.0.5+1.20.1.jar
  [✔️] TaxFreeLevels-1.3.6-forge-1.20.2.jar
  [✔️] TerraBlender-forge-1.20.1-3.0.0.169.jar
  [✔️] Terralith_1.20.2_v2.4.7(modified).jar
  [✔️] textrues_embeddium_options-0.1.3+mc1.20.1.jar
  [✔️] togenc-forge-1.20.x-v1.0.jar
  [✔️] ToolBelt-1.20-1.20.0.jar
  [✔️] trashslot-forge-1.20-15.0.0.jar
  [✔️] village_nullifier-2.0.0.jar
  [✔️] village-nullifier-terralith-2.0.0.jar
  [✔️] weakerspiderwebs-1.20.1-3.2.jar
  [✔️] world_preview-forge-1.20-1.1.0.jar
  [✔️] WWOO-FABRIC+FORGE+QUILT-2.0.0.jar
  [✔️] Xaeros_Minimap_23.8.4_Forge_1.20.jar
  [✔️] XaerosWorldMap_1.36.0_Forge_1.20.jar
  [✔️] YungsApi-1.20-Forge-4.0.2.jar
  [✔️] YungsBetterDesertTemples-1.20-Forge-3.0.3.jar
  [✔️] YungsBetterDungeons-1.20-Forge-4.0.3.jar
  [✔️] YungsBetterJungleTemples-1.20-Forge-2.0.4.jar
  [✔️] YungsBetterMineshafts-1.20-Forge-4.0.4.jar
  [✔️] YungsBetterNetherFortresses-1.20-Forge-2.0.5.jar
  [✔️] YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar
  [✔️] YungsBetterStrongholds-1.20-Forge-4.0.3.jar
  [✔️] YungsBetterWitchHuts-1.20-Forge-3.0.3.jar

**Comment by XFactHD** [comment]
Serilum's Double Doors mod is unfortunately known to break camo application on Framed Doors. Their implementation is technically fairly clean, it does have downsides though.

As for the blueprint issue, that turns out to be a really stupid mistake on my part. I hope to get a new version out relatively soon which will include a fix for that.

**Comment by Gantros** [comment]
As long as I have your ear, I'd love to see framed block doors in 1x3 and 1.5x3, the latter intended to make 3x3 double doors.

**Comment by XFactHD** [comment]
I currently have no plans to add larger doors as they are an absolute pain in the ass to implement. However, the latest 1.19.2 and 1.20.1 versions of [Dramatic Doors](https://www.curseforge.com/minecraft/mc-mods/dramatic-doors) add support for FramedBlocks by adding 3 block high framed doors. Maybe they'd be willing to also add 1.5x3 doors.
