### ISSUE TITLE
[Bug]: Framed vertical stairsdo not behave as expected when connecting to both normal and vertical stairs

### ISSUE THREAD

**Issue by InterFelix** [XFactHD/FramedBlocks#345]
### Minecraft version

1.2

### Forge version

47.2.0

### FramedBlocks version

9.1.6

### Describe the bug

Vertical stair corners do not behave as expected:
![grafik](https://github.com/XFactHD/FramedBlocks/assets/29462559/a19eb55b-ec84-4d94-b62a-255e3ebc2065)
On the top left are normal, vertical stairs.
On the bottom are normal, downward facing stairs.
On the bottom left are vertical stairs that connect to both the normal stairs and the vertical stairs, akin to vanilla outward corner stairs, but on a wall.
However, as can be seen in the screenshot, the "outer corner" of the connecting vertical stairs is missing.

### How to reproduce the bug

1. Place Vanilla stairs under a reference block, facing downwards towards the player
2. Place Framed vertical stairs on the left side of the reference block, facing left towards the player
3. Place Framed vertical stairs in the corner between the Vanilla stairs and the Framed vertical stairs.
The vertical stairs in the corner connect, but the bottom left corner of the connecting vertical stairs is missing.

### Expected behavior

The vertical stairs connect correctly, akin to Vanilla stairs on an outward facing corner:
![grafik](https://github.com/XFactHD/FramedBlocks/assets/29462559/27607daf-8b4f-4c0a-a4c0-67ce4db59b19)

**Comment by XFactHD** [comment]
This is technically intended behavior at the moment, the block only has three connection types: none (the entirely vertical section), top (the variant missing in your first screenshot) and bottom (the bottom block in your screenshot with the normal stairs on its right). I can see however why that might not be desired behaviour. I'll look into changing this to behave like you are suggesting, this change will however not be implemented for 1.20.1 and earlier as the required change would break existing worlds
