### ISSUE TITLE
[Question]: Could this mod be published on Modrinth in addition to CurseForge?

### ISSUE THREAD

**Issue by Jerome226** [XFactHD/FramedBlocks#347]
### Question

I have multiples reasons I think it could benefits both users and you:
- Modrinth is for what I know, a pretty good platform
- Modrinth has it's own client and lot of people use it instead of curse, so posting it there, would allow other players to be able to use your mod.
- Extra points and revenues for you
- More people can enjoy the mod

(I'm not sponsored by them, It's just that because of some mods like you're not being avalaible on modrinth, it makes pack making harder, because you can only use modrinth mods on modrinth packs)

**Comment by lonevox** [comment]
I just came here to write the exact same request, so consider this a decently popular idea :) If it won't be released on Modrinth, is it okay for me to distribute your mod jar in my pack (the actual jar file, not a link)?

**Comment by XFactHD** [comment]
I have been thinking about releasing FramedBlocks on Modrinth for a while, I just didn't bother actually setting it up yet as there's been little incentive to do so. Since there seems to actually be interest in this now, I'm gonna bite the bullet and finally do it.

**Comment by XFactHD** [comment]
FramedBlocks is now available on Modrinth: https://modrinth.com/mod/framedblocks
