### ISSUE TITLE
[Feature]: Create shaft camo block

### ISSUE THREAD

**Issue by CcMenta** [XFactHD/FramedBlocks#348]
### Describe the feature

A block that can placed on the shaft, so you can run it in your house's wall.

**Comment by XFactHD** [comment]
Hmm, that's an interesting idea, I'll look into the feasibility of this.

**Comment by XFactHD** [comment]
I've looked into this some more and, while I would absolutely love to add this, it is effectively impossible to do so at the moment as it would require duplicating several hundred lines of code from Create and the extensive internal changes required to make this possible without code duplication are unjustifieable at the moment.
