### ISSUE TITLE
I think i found (temp) solution for shading issues with optifine/shaders

### ISSUE THREAD

**Issue by dusieq95** [XFactHD/FramedBlocks#35]
Just instead of using solid blocks use framed cube under/next to slopes, works! 

Left: Solid Blocks
Right: Framed Cubes
![image](https://user-images.githubusercontent.com/59163540/124782973-f9ffe780-df44-11eb-9740-f6187da676aa.png)

**Comment by XFactHD** [comment]
OptiFine is not supported, that's going to be your permanent solution if you want to use OptiFine. Mitigating crashes is everything I am going to do in respect to OptiFine.
