### ISSUE TITLE
[Bug]: Crash when launching 

### ISSUE THREAD

**Issue by vidalviv** [XFactHD/FramedBlocks#353]
### Minecraft version

1.19

### Forge version

43.2.4

### FramedBlocks version

6.8.6

### Describe the bug

When i try to start with Version 6.8.6 the game crash. With 6.8.4 no problem.

### How to reproduce the bug

launch the game (1.19.2-forge-43.2.4) with the 35 mods i have already installed (list in the crash log?) + framedblock 6.8.6

### Expected behavior

Any chance to solve the problem? If it isn't to much work. That would be great.

### Crash log

https://gist.github.com/vidalviv/4d03dfba3520245ac5c61523fcacbc63

**Comment by XFactHD** [comment]
The error in that crash report is caused by an earlier error. Please provide the full latest.log, it should contain the actual error.

**Comment by vidalviv** [comment]
ok. so.. i reproduced the bug. i get a little window with "exit code: -1" and a short overview: 

The game crashed whilst initializing game
Error: java.lang.IllegalAccessError: class com.laidbacksloth.brightnessslider.BetterSlider cannot access its superinterface net.minecraft.client.OptionInstance$SliderableValueSet (com.laidbacksloth.brightnessslider.BetterSlider is in module brightnessslider@1.0 of loader 'TRANSFORMER' @7c5d1d25; net.minecraft.client.OptionInstance$SliderableValueSet is in module minecraft@1.19.2 of loader 'TRANSFORMER' @7c5d1d25)

and i get the option to click on a button "full crashlog". you should find it under the same link. the new one have the following timestamp: Time: 2024-01-04 05:39:13

**Comment by XFactHD** [comment]
As I said, the error in the crash report is not the actual issue, the real error happened earlier. I would need to see the latest log to tell you what exactly is wrong. The only thing I can generally tell you from such a crash report is that FramedBlocks is almost guaranteed to not be at fault.

Now, in this case I missed the obvious issue when I initially responded: you are using Forge 43.2.4 but FramedBlocks 6.8.6 requires Forge 43.2.14. The latest log would have told you that and, if the subsequent error (which FramedBlocks has nothing to do with) from that crash report hadn't happened, then the game would have told you that as well with a nice error screen.
