### ISSUE TITLE
[Feature]: Place Framed Slope Slab Upside Down

### ISSUE THREAD

**Issue by theJERMwarfare** [XFactHD/FramedBlocks#357]
### Describe the feature

Add the ability to place the Framed Slope Slab upside down or add a separate Inverted Framed Slope Slab block, this would work well when using the Framed Elevated Slope Slab upside down/inverted.

**Comment by XFactHD** [comment]
This is already possible though very poorly (i.e. not at all) documented. To place a slope slab upside down, you need to hold the sneak key while placing it.

**Comment by theJERMwarfare** [comment]
Worked as you descried, thanks for the help.
