### ISSUE TITLE
Texture bug on framed block slopes

### ISSUE THREAD

**Issue by LowcaX** [XFactHD/FramedBlocks#36]
Hey. I reported this bug to optifine author and it can be solution for this problem. Please check this link: https://github.com/sp614x/optifine/issues/5991

**Comment by XFactHD** [comment]
Thank you for that, I found the problem.
To make sure this is fixed, please try it with this test build: https://www.dropbox.com/s/zsdhdxqdgbtl4tx/FramedBlocks-2.9.1-oftest.jar?dl=0 and report back if it works for you

**Comment by LowcaX** [comment]
Works perfect! 
![2021-07-08_21 35 01](https://user-images.githubusercontent.com/41991876/124980254-6efe1a80-e034-11eb-900e-2b68160db9e7.png)

**Comment by XFactHD** [comment]
Perfect, thanks for the confirmation.
