### ISSUE TITLE
[Feature]: A configuration to disable the sloped block

### ISSUE THREAD

**Issue by Xiarno** [XFactHD/FramedBlocks#361]
### Describe the feature

I personally hate the sloped block. I feel like they just don't belong in Minecraft. Of course for other people who like it, I'd hate to suggest removing it. That's why I'd like a config to just disable sloped blocks.
Just to make sure, when I say "sloped blocks", I meant the ones unnatural to Minecraft, that aren't voxel-liked. (With the exception of the rails)

**Comment by XFactHD** [comment]
I will never add configuration settings for individual blocks or groups of blocks. This mod has reached over 180 blocks and more will be added, adding a config option for each block or even just groups of blocks would significantly bloat the config file, cause severe issues if the config doesn't match between your client and the server you are connecting to and is conceptually incompatible with the core architecture of the mod.

If you want to make the blocks unobtainable, then a datapack, CraftTweaker or KubeJS can be used to remove the recipes. Mods like JEI and REI also allow hiding the blocks from their list. But that is all the configuration there will be.
