### ISSUE TITLE
[Feature]: Missing sloped variants

### ISSUE THREAD

**Issue by JWTHDYTWA** [XFactHD/FramedBlocks#362]
### Describe the feature

I'm completely sure those two obvious sloped variations are missing.

![Missing Framed Blocks](https://github.com/XFactHD/FramedBlocks/assets/30724185/3d82a215-557c-40d1-8f04-09f9cc63c92a)

**Comment by XFactHD** [comment]
Duplicate of #248.

These blocks in both orientations are already planned and will be added in a future version.
Nonetheless, I highly appreciate the detailed example of what you're requesting.
