### ISSUE TITLE
[Question]: 1.19.2 FrameBlocks with Texkit 4.0

### ISSUE THREAD

**Issue by Friarobby** [XFactHD/FramedBlocks#363]
### Question

I am helping a friend set up a Texkit 4.0 through the Technic Launcher. Currently, I am running the mod pack on my PC to test and make sure things are working properly. I have noticed that while the jar file is in the mod folder, the mod is not currently loading into the game. After reading through the 1.19.2 files, it does appear there are dependencies for this mod. Are those required to run this mod, or are they just there in case those mods are also installed so that they are integrated with FramedBlocks?

**Comment by XFactHD** [comment]
All dependencies (which I assume you found in the `mods.toml` file in the JAR) are optional, you can use the mod just fine without any of them.

With that being said, FramedBlocks is a Forge mod while Tekxit 4 appears to be a Fabric-based modpack. If FramedBlocks is included by default in the modpack, then that is a mistake on the pack author's part as Forge and Fabric are entirely incompatible mod loaders. A Fabric port of FramedBlocks is not planned at this time.

**Comment by XFactHD** [comment]
Closing due to lack of feedback. I'm going to assume my prior response answered your question.
