### ISSUE TITLE
[Feature]: Create a trapdoor/stair block

### ISSUE THREAD

**Issue by Sinsei33** [XFactHD/FramedBlocks#365]
### Describe the feature

![image](https://github.com/XFactHD/FramedBlocks/assets/72999688/cc794788-51f3-4dd0-b9a2-623e0a903503)

No idea if it is already possible in a way (didnt find it yet), but stairs with a trapdoor on top would be great. Possibly both being able to have different blocks. So you can hide your stairs below trapdoors that are at ground level.

**Comment by XFactHD** [comment]
This is unfortunately not possible as the entire system used for double blocks is based on the assumption that the two components don't overlap. That assumption would be violated by such a block and would cause z-fighting on the four faces where the trapdoor and the stairs intersect.
