### ISSUE TITLE
Off-hand support

### ISSUE THREAD

**Issue by Erysch** [XFactHD/FramedBlocks#37]
I thought about how nice it would be if you could place the framed block with your main hand and it instantly takes the texture of your second hand. Is that possible or is something like this already implemented?

This would be a nice quality of life improvement.

Greetings (:
Love your mod

**Comment by XFactHD** [comment]
Sounds like a useful addition, I will look into it.

**Comment by Erysch** [comment]
Seems that it worked. In which version it'll be added?

**Comment by XFactHD** [comment]
Next version, no idea yet when that will be.

**Comment by Erysch** [comment]
I just tested the feature and I am happy. Thank you!
