### ISSUE TITLE
[Bug]: Framed Vertical Sloped Stairs Texture Bug

### ISSUE THREAD

**Issue by f0kx** [XFactHD/FramedBlocks#370]
### Minecraft version

1.20

### Forge version

43.3.5

### FramedBlocks version

6.8.6

### Describe the bug

When i insert some Blocks inside the Block in two rotation some strange texture bug appears.
After rotating with screwdriver it will be fixed ...but in two states texture bugs appearing.
![image](https://github.com/XFactHD/FramedBlocks/assets/14795020/86b68f18-f586-459d-afe0-7997824444e6)

### How to reproduce the bug

place the framed block and insert a block...in a specific rotation the texture is broken

### Expected behavior

texture should be fine like other rotations

### Additional details

https://imgur.com/a/MkblwvL

**Comment by XFactHD** [comment]
Are you using OptiFine?

**Comment by f0kx** [comment]
no iam using oculus ... 
this is stage 1
![image](https://github.com/XFactHD/FramedBlocks/assets/14795020/9375887c-5c62-41a3-9852-bed6c649a6e7)
this is stage 2
![image](https://github.com/XFactHD/FramedBlocks/assets/14795020/e5790e58-f298-435e-85fc-1adbc42fc264)
and this stage 3
![image](https://github.com/XFactHD/FramedBlocks/assets/14795020/2ae601ab-3abe-4ca5-b332-3397b651f3a7)

but its only on this side
![image](https://github.com/XFactHD/FramedBlocks/assets/14795020/855fc8a9-7ba7-4242-8379-56876c3cfc16)

other side is fine
when i take deepslate this bug will happens but when iam using cobble deepslate all is fine...very strange

**Comment by f0kx** [comment]
![image](https://github.com/XFactHD/FramedBlocks/assets/14795020/1ebc1fcd-9428-4299-92b0-36a6bcb9ff4b)

**Comment by XFactHD** [comment]
Unfortunately I cannot reproduce this issue in 1.20.4, 1.20.1 or 1.19.2 with the provided information and I have been advised that this issue is also most likely not fixable on my end. Apart from that, support for 1.19.2 is limited to the most critical bugs such as crashes and world corruption, the issue template has just not been updated yet to reflect that.
