### ISSUE TITLE
[Bug]: Shift Clicking out of Powered Framing Saw

### ISSUE THREAD

**Issue by LuziferSenpai** [XFactHD/FramedBlocks#371]
### Minecraft version

1.20

### Forge version

47.2.19

### FramedBlocks version

9.1.6

### Describe the bug

When shift clicking out of the powered framing saw with only one framed cube inside, it will crash the game.

### How to reproduce the bug

Put one framed cube inside the powered framing saw, shift click it out.

### Expected behavior

Not crash the game and give me the item.

### Additional details

Playing All the Mods 9.
This doesnt happen when more then one framed cube is inside.

### Crash log

https://gist.github.com/LuziferSenpai/00f9bec3443f794a79203140cc8fbec6

**Comment by XFactHD** [comment]
Thank you, this sneaked past me since it's somewhat random whether it happens (at least in the environments I can test in). I hope to have a new version out with a fix for this in the coming days.
