### ISSUE TITLE
[Question]: Slope slab???

### ISSUE THREAD

**Issue by 34486** [XFactHD/FramedBlocks#372]
### Question

Is there another block to act as the slope slab to place upside down or is the slope slab supposed to be capable of being placed upside down (it wont for me..?) 

Maybe I am missing a block or something, am trying to continue a gradual incline starting with the framed inverted double slope slab. 

Maybe this requires a slope edge which I was was a feature request already, I must be missing something simple...

**Comment by XFactHD** [comment]
The slope slab can be placed upside down by crouching while placing it. This is unfortunately entirely undocumented at the moment.
I might change this in the future as it is a somewhat annoying mechanic.
