### ISSUE TITLE
[Feature]: Corner for Framed Slope Panels

### ISSUE THREAD

**Issue by clingysloth** [XFactHD/FramedBlocks#374]
### Describe the feature

There doesn't seem to be just a corner for Framed Slope Panels, similar to the Framed Slope Corner.

**Comment by XFactHD** [comment]
That shape has been introduced in FramedBlocks 9.1.0 for Minecraft 1.20.1 in the form of the various Framed Corner Slope Panels. A backport to earlier versions is not possible.
