### ISSUE TITLE
[Feature]: Block with missing corner

### ISSUE THREAD

**Issue by Gingrids** [XFactHD/FramedBlocks#375]
### Describe the feature

Hi, is it possible to add a block that is missing a slab corner? Preferably add two, one with the right corner missing and then one with the left one. If possible, could it behave like a stair block? So, generally, a stair with an added corner (left and right). Thanks :D

**Comment by XFactHD** [comment]
I can see the use, but this seems very niche to me. I'll think about it.
For the time being, you can achieve the same effect by placing a Framed Stairs block with the necessary neighbors to achieve the desired shape, then use the Framed Key to lock the block into that shape and then remove the unwanted neighboring blocks again.

**Comment by Gingrids** [comment]
Yes it might be niche, just thought it would be easy to have a block like that. Well Thanks!
