### ISSUE TITLE
[Question]: Fabric Port

### ISSUE THREAD

**Issue by Roester1** [XFactHD/FramedBlocks#376]
### Question

Hi! I would like to ask for permission to make a fabric port of FramedBlocks with the same textures etc.

**Comment by XFactHD** [comment]
Sure, go ahead. The license permits it and, as I've said in the past, I'm open to people trying to make it work.
With that said, there's two points I want to make:

- I request that you rename the fork and indicate clearly that it's an unofficial port, I don't want to be dealing with Fabric issues on this repo
- It's probably a good idea if you wait for the first 1.20.4 release as I have made a significant refactor to the model wrapping system that should make it easier to make it work with Fabric's model loading APIs

**Comment by saphsara** [comment]
> ### Question
> 
> Hi! I would like to ask for permission to make a fabric port of FramedBlocks with the same textures etc.

omg i would be so happy if someone made this available for fabric. love this mod. please leet me know if it comes available

**Comment by PeakXing** [comment]
I like fabric,I use Fabric Loader

**Comment by DriHut** [comment]
Should've asked before using the texture on my version but I found this searching for a good place to ask if I could use it Otherwise I would have changed them but I guess that's fine. 

Still want to make sure you are fine with me calling the mod ReFramed and uses the textures you've made? 

I made most of the logic based on Template 2 but there is quite a bit more features than it ^^. (it on modrinth and on github if you want to have a look)

**Comment by XFactHD** [comment]
I'm 100% fine with the name, but you cannot re-use any code or assets from FramedBlocks as your license (MIT) is incompatible with mine (LGPL v3).

**Comment by DriHut** [comment]
Thanks for the quick feedback. I think I can just multi license the project in that case. Unless you prefer that I use other assets anyway so that there is a clear distinction between both mods which I would get ^^.

**Comment by XFactHD** [comment]
I don't know whether dual-licensing the project afterwards would work for that. Other assets would definitely be easier and would of course also have the other benefit you mentioned.

**Comment by XFactHD** [comment]
Closing this issue for now as all questions are answered.
