### ISSUE TITLE
[Feature]: Consume Camo config for 1.18: a desperate plea..

### ISSUE THREAD

**Issue by theivycoder** [XFactHD/FramedBlocks#377]
### Describe the feature

Hello! 
I am a long time adorer of your mod and have added it to my vault hunters 3 server and noticed a lack of config to disable camo consumption. I took a peak at the code between the 1.18 version and the version for 1.19 with the config info and noticed quite a difference in the implementation of camo as a data factory itself, so I realize my request would be a massive undertaking but I would be eternally grateful to see the config option to disable camo consumption for my vault hunters server so I can again ignore any other similar mod in favor of your vastly superior one <3 I look forward to reading a response shortly!

**Comment by XFactHD** [comment]
Support for 1.18 has been dropped several months ago. I'm not even sure whether I could get that branch set up and building again at this point.
