### ISSUE TITLE
[Bug]: Framed Levers are inverted

### ISSUE THREAD

**Issue by superjaja05** [XFactHD/FramedBlocks#380]
### Minecraft version

1.20

### Forge version

47.2.19

### FramedBlocks version

9.1.6

### Describe the bug

The wall levers are inverted, the ON state is pointing upward and the OFF state is pointing downward

### How to reproduce the bug

Place a framed lever on a wall

### Expected behavior

the ON state should be pointing downward, like with vanilla levers

### Additional details

I checked the assets of the mod and also the vanilla assets, 
And it seems that the vanilla lever blockstates are just.. dumb, in vanilla "powered=false" equals to the "lever_on" model lmao

**Comment by XFactHD** [comment]
God damnit, Mojang 🤦. I'll look into it once I have a functional PC again.
