### ISSUE TITLE
[Feature]: Add a config option to hide the texture overlay of Framed Button variants and Framed Pressure Plate variants

### ISSUE THREAD

**Issue by AlisonHuang777** [XFactHD/FramedBlocks#382]
### Describe the feature

1. They have z-fighting issues. (Using Embeddium)
![2024-02-13_20 59 27](https://github.com/XFactHD/FramedBlocks/assets/51637996/d9611c76-af8c-4010-8b42-b94c7b9a7a6a)
2. It looks redundant. If the players want to know what variation it is, they can use Jade or Debug Screen (F3) if they don't have Jade installed.

**Comment by XFactHD** [comment]
I honestly expected this to be requested at some point. I'll add a config option for it when I have a working PC again.
