### ISSUE TITLE
[Feature]: Framed Strip

### ISSUE THREAD

**Issue by KurageAkagami** [XFactHD/FramedBlocks#385]
### Describe the feature

Back in 1.7.10 there was a mod called forge Microblocks and it let you cut down a block into different parts of a cube. I really loved those blocks a lot and we already have a lot of them in this mod. Just not the strips which are a quarter of the quarter blocks (While being alligned to the edge of a block, or corner). Of course Microblocks had a feature to have multiple strips in one Block because of its library Multipart (I think it's called). Assuming that won't be possible in the framed blocks mod but just having framed strips in the game would be so nice. I see if I can find some screenshots.

Here the Light strips are probably the best example I could find
![yottanks](https://github.com/XFactHD/FramedBlocks/assets/130392115/d8ed7768-40b8-40b6-ae02-75c5bae749d6)

More examples with Light strips (I know simply light has similar ones but they are just white and don't look as clean when placed next to each other)
![2023-02-16_16 42 27](https://github.com/XFactHD/FramedBlocks/assets/130392115/694b03a3-4778-4156-913b-65839286ba76)
![2022-10-25_20 54 59](https://github.com/XFactHD/FramedBlocks/assets/130392115/ae0cc331-04f7-4032-923f-29316a0829a1)
![image](https://github.com/XFactHD/FramedBlocks/assets/130392115/9e14a66a-4470-4c93-b875-01c31d85d3f9)
![2023-07-06_00 30 12](https://github.com/XFactHD/FramedBlocks/assets/130392115/919954e5-06ef-4c62-885d-554eaf3a0eff)
![2023-02-16_16 41 21](https://github.com/XFactHD/FramedBlocks/assets/130392115/02e154fd-38b0-4258-8c8b-8d17f76c2b27)

I hope those screenshots help and clarify what I mean by "edge aligned strips" 
I can provide more screenshots when I get back to my PC

**Comment by XFactHD** [comment]
Placing multiple of these in the same block space won't be possible in FramedBlocks. Adding these strips is simple and I already have them implemented locally.
