### ISSUE TITLE
[Feature]: Additional block/variants of blocks

### ISSUE THREAD

**Issue by Imperum** [XFactHD/FramedBlocks#386]
### Describe the feature

Hello! Big appreciation for your mod!
I've got a few suggestions for blocks I've missed so far. If already requested or on the todo-list, my apologies. (Tried to check open issues to prevent doubles.)

First two are modifications of existing blocks:

![image](https://github.com/XFactHD/FramedBlocks/assets/10833865/012bfcea-229f-4068-b086-c33c911de08d)

![image](https://github.com/XFactHD/FramedBlocks/assets/10833865/8abed964-d850-42b0-bd0e-090474a035b6)

Both are modified versions of stair variants, with half material option. Which provide better options for transits in material, or poles attached to low walls for example.

New block would be a dedicated corner piece, with 1/8 taken out. (Without needing attached blocks to make it from a stair piece.)

![image](https://github.com/XFactHD/FramedBlocks/assets/10833865/e4650c04-214a-4efe-b1fd-05a0a2576baa)

Maybe in multi-material also, split between top- and bottom half? To go along with the stairs pieces from earlier.

Many thanks for the mod so far and hope to see it grow even better!

**Comment by XFactHD** [comment]
The first two blocks have been added recently and will be released as part of the next update.
I'll consider the third one, especially with the connection to the first two blocks, though for now you can achieve that shape by placing a stairs block with appropriate neighbors, locking it into that shape by right clicking it with a Framed Key and then breaking the supporting neighbors again.

**Comment by Imperum** [comment]
Very nice! Much appreciated, that's all I can ask for.
Looking forward to it.

**Comment by SephirothWS** [comment]
I would like to expand on this request with a split stair between a stair block and a panel,  where basically I can use two textures, one for the stair, and one for a panel corner (which is 1/8th of a block) to match a different block texture.

![image](https://github.com/XFactHD/FramedBlocks/assets/9165737/f32abff1-bd18-414a-b3d8-d35a9cc919c7)

**Comment by XFactHD** [comment]
@Imperum I've decided against a dedicated block for the inner corner stair shape as I want to put a larger emphasis on the "state locking" feature instead of adding blocks that duplicate shapes this feature can already achieve.

@SephirothWS The requested shape and similar ones can be achieved in the upcoming 1.20.6 release with the various double stair blocks (Double Stairs, Divided Stairs, Sliced Stairs and their vertical equivalents). Backporting these to 1.20.1 is unfortunately not possible.

**Comment by SephirothWS** [comment]
@XFactHD Well, all packs I have been encountering are on 1.20.1, and "unfortunately not possible" doesn't exactly state why its not possible. Is there something new in Forge or whatever loader you're using in 1.20.6 that's not available in 1.20.1?
