### ISSUE TITLE
enable Intangible Feature

### ISSUE THREAD

**Issue by RiaNoir** [XFactHD/FramedBlocks#389]
### Describe the feature

I'm using the cursedforge launcher and don't have my own server. Unless I'm doing something wrong, could you enable the Intangible Feature for solo players not just for people who have their own servers?

**Comment by XFactHD** [comment]
The config setting being in a file called `framedblocks-server.toml` does not mean that those settings can only be used on a dedicated server. In singleplayer this config file is located in your world folder in `saves/<save name>/serverconfigs` and on a server it would be in `world/serverconfigs`.

Starting with 1.20.4 (once I finally release the update) it will be in the normal config folder as well and the folder in the world will only serve as an override.

**Comment by RiaNoir** [comment]
Thank you very much!
