### ISSUE TITLE
Mod Compatibility: Building Gadgets

### ISSUE THREAD

**Issue by Erysch** [XFactHD/FramedBlocks#39]
Mod: https://www.curseforge.com/minecraft/mc-mods/building-gadgets

Is it possible to implement building gadget compatibility, since you can only place untextured frames with it. I guess this is something what the Building Gadgets's Maker has to do?

This would be a huge addition like the second hand feature.

I will suggest this to the other modder's github.

Greetings (=

**Comment by XFactHD** [comment]
It looks like Building Gadgets doesn't have any kind of API I could interface with. From my point of view there is currently no way to make this work.
Let's see what the guys over there have to say about this in https://github.com/Direwolf20-MC/BuildingGadgets/issues/644

**Comment by XFactHD** [comment]
The compatibility implementation for BuildingGadgets is done now.
I will wait with the release until the discussion in the BuildingGadgets issue is done.

**Comment by Erysch** [comment]
Wow, nice. Well done so!

**Comment by XFactHD** [comment]
I have now released a new version with Building Gadgets compatibility included with the dependency locked to a very specific version of Building Gadgets. When they have the time to fix the issues related to the compatibility API, then I will release a new version with updated compatibility.
