### ISSUE TITLE
[Bug]: Framed Door does not accept blocks

### ISSUE THREAD

**Issue by Sixdd6** [XFactHD/FramedBlocks#391]
### Minecraft version

1.20

### Forge version

47.2.20

### FramedBlocks version

9.1.6

### Describe the bug

Framed Door does not accept blocks if the Double Doors mod by Serilum is installed or the Quark Double Door Opening feature is enabled. When right-clicking the doors the behavior varies from either completely not allowing the block to be emplaced or only disallowing certain halves of the block to be emplaced.

### How to reproduce the bug

Install either Quark or Double Doors with this mod
Place a Framed Door
Try to emplace a block into the door
Notice unwanted behavior

### Expected behavior

Should work as expected

**Comment by XFactHD** [comment]
This is a known issue with Serilum's Double Doors mod. It has been reported to them (https://github.com/Serilum/.issue-tracker/issues/2071) and there is nothing I can do to fix this.
A quick look at Quark's Double Door module suggests that their implementation works the exact same way as Serilum's and therefore suffers from the same issue. Please report this to them.

**Comment by Sixdd6** [comment]
Ok thanks for the quick reply.
