### ISSUE TITLE
[Question]: What mods does this support

### ISSUE THREAD

**Issue by RunTellObama** [XFactHD/FramedBlocks#396]
### Question

I can use blocks from some mods but not others

**Comment by XFactHD** [comment]
In principle, FramedBlocks supports blocks from all mods. In practice, this is significantly more complicated:

- For blocks which are considered solid, such as stone and wood, it's trivial to ensure that they are actually a solid cube
- For blocks which are not considered solid, such as glass and stained glass, such a check is not possible. Instead, the block must be tagged as `framedblocks:frameable` as documented on the CurseForge page. For vanilla blocks, modded blocks which are part of certain vanilla tags and blocks from a few mods, this tagging is handled in FramedBlocks itself. For anything else, this would need to be done by the other mod's author or by you adding a datapack with the appropriate tags

**Comment by RunTellObama** [comment]
More specifically, the issue i'm having is some blocks from the mod Ad Astra do not work, like the iron plating and pillars

**Comment by XFactHD** [comment]
That's an issue on Ad Astra's side. They have since fixed this in version 1.15.18, so you'll have to update that.

**Comment by RunTellObama** [comment]
So do I have to wait till atm9 updates then?

**Comment by XFactHD** [comment]
The fixed version is included in ATM9 0.2.49, so you just need to update the pack

**Comment by RunTellObama** [comment]
Oh sorry slight typo there, i'm currently playing on atm9 no frills, does that include the fixed version?

**Comment by XFactHD** [comment]
ATM9 No Frills does not include the fixed version of Ad Astra yet.

**Comment by XFactHD** [comment]
The latest version of ATM9 No Frills (0.1.10) includes the fixed version of Ad Astra.
