### ISSUE TITLE
[Feature]: divided threeway corner pillar

### ISSUE THREAD

**Issue by 1foxy2** [XFactHD/FramedBlocks#398]
### Describe the feature

![image](https://github.com/XFactHD/FramedBlocks/assets/127777030/f17df5f8-a704-4dbf-b17c-6dbf4403deef)

**Comment by XFactHD** [comment]
I'm not totally sure about this one, it seems kinda niche to me. I'll think about it.

**Comment by 1foxy2** [comment]
![image](https://github.com/XFactHD/FramedBlocks/assets/127777030/6b13877c-413f-4c93-9852-6eea55c93083)
the reason i want them is because there's no cornerblock for sliced stairs

**Comment by XFactHD** [comment]
Ok, yeah, that sounds reasonable. I'll add it to my list

**Comment by 1foxy2** [comment]
![image](https://github.com/XFactHD/FramedBlocks/assets/127777030/e5904ae7-23d3-4f2f-823b-98799308838c)
also these two for the same reason

**Comment by XFactHD** [comment]
I will most likely do those two differently, see #409 for more details.

**Comment by XFactHD** [comment]
The requested shapes and similar ones can be achieved in the upcoming 1.20.6 release with the various double stair blocks (Double Stairs, Divided Stairs, Sliced Stairs and their vertical equivalents). Backporting these to 1.20.1 is unfortunately not possible.
