### ISSUE TITLE
Block face still visible when it shouldn't be

### ISSUE THREAD

**Issue by Sixdd6** [XFactHD/FramedBlocks#4]
This is kinda hard to explain but when the framed stairs are in a certain configuration there is a block face still visible where it shouldn't be, I've attached an image to show it better.

![2021-02-25_07 46 42](https://user-images.githubusercontent.com/29067133/109162978-6f111400-773e-11eb-918b-fcf05a0d4101.jpg)

**Comment by XFactHD** [comment]
What MC version?
What mod version?
Does it happen without Optifine?
