### ISSUE TITLE
[Bug]: FramedBlocks keep crashing the world with create schematics

### ISSUE THREAD

**Issue by OlaPessoa** [XFactHD/FramedBlocks#400]
### Minecraft version

1.20

### Forge version

Forge-47.2.0

### FramedBlocks version

FramedBlocks-9.1.6

### Describe the bug

as soon as i get the schematic on my main hand the game crashes

### How to reproduce the bug

all i did was make a build and within the build i made some details with some framed divided stairs, and now whenever i get the schematic on my hand and try to edit it, it crashes the world, then i can get back in and place the schematic but whenever i get my hand off of it and try to get the schematic back on my hand it crashes, also the framed blocks aren't place with the camo blocks.

### Expected behavior

well, i expected that it would... work? lol

### Crash log

https://gist.github.com/OlaPessoa/e33acc708b2bd9e6f86334ea6fdf42ca

**Comment by OlaPessoa** [comment]
it's still occuring https://gist.github.com/OlaPessoa/fa234c08ad636f8af4b09939efdc7072

**Comment by XFactHD** [comment]
Well, yeah, of course it's still occuring for you because I haven't released a mod update with this fix yet. Me making a commit to fix a bug does not magically fix stuff on your computer.

**Comment by XFactHD** [comment]
Version 9.2.1 which includes the fix for this issue has just been approved on CurseForge
