### ISSUE TITLE
[Question] 1.20.1 Glowstone applied blocks

### ISSUE THREAD

**Issue by FrozenGalaxy** [XFactHD/FramedBlocks#402]
### Question

Is it inteded that blocks that have glowstone added, stop being lit when the server restarts?

**Comment by XFactHD** [comment]
No, that's not at all intended, it's an unfortunate interaction between Starlight and the way lighting based on data from a blockentity works in 1.20.1 and earlier. This will be fixed properly in 1.20.4 (whenever I actually release that). I will look into the possibility of backporting that fix to 1.20.1, but it might not be feasible to do so. For now the fix is to remove Starlight.

**Comment by FrozenGalaxy** [comment]
Ah so its Starlight, guess ill uninstall it then, on another note, any idea what this is caused by? And is there a fix? (The obvious difference between a framedglowstoned block and non glowstone
![image](https://github.com/XFactHD/FramedBlocks/assets/156858866/d00e7eb9-2570-4d59-b56d-a93dc747db46)

**Comment by XFactHD** [comment]
That's caused by how the vanilla game handles light-emitting blocks, specifically the fact that emitting light causes ambient occlusion to be disabled for the respective block. There is unfortunately nothing I can do about this.

**Comment by FrozenGalaxy** [comment]
> That's caused by how the vanilla game handles light-emitting blocks, specifically the fact that emitting light causes ambient occlusion to be disabled for the respective block. There is unfortunately nothing I can do about this.

That's sad. Any tips nonetheless? Maybe a setting or mod that mitigates it a bit?

**Comment by XFactHD** [comment]
You could try disabling smooth lighting in the video settings, but that will of course make other things look worse. Other than that I currently have nothing for you unfortunately

**Comment by FrozenGalaxy** [comment]
Aww, thats a shame, but thanks a lot for your time anyway :) and thanks for keeping the mod active!

**Comment by XFactHD** [comment]
After some more digging, I've found a very simple solution to light-emitting blocks being very obvious next to "normal" blocks.
