### ISSUE TITLE
[Bug]: Crashes game when framed block right-clicked with milk bucket

### ISSUE THREAD

**Issue by ExotisDev** [XFactHD/FramedBlocks#403]
### Minecraft version

1.20

### Forge version

47.2.20

### FramedBlocks version

9.1.6

### Describe the bug

The game entirely crashes when any framed block is right-clicked with a milk bucket. 

### How to reproduce the bug

1. Place down any framed block
2. Right-click with a milk bucket
3. Game crashes

### Expected behavior

The framed block rejects the milk fluid from getting inserted

### Additional details

Other enabled mods when the game has crashed:
- ad_astra-forge-1.20.1-1.15.17.jar
- appleskin-forge-mc1.20.1-2.5.1.jar
- botarium-forge-1.20.1-2.3.3.jar
- car-forge-1.20.1-1.0.15.jar
- cc-tweaked-1.20.1-forge-1.109.3.jar
- chisels-and-bits-forge-1.4.145.jar
- constructionwand-1.20.1-2.11.jar
- create-1.20.1-0.5.1.f.jar
- create-new-age-forge-1.20.1-1.1.2.jar
- createaddition-1.20.1-1.2.3.jar
- createdeco-2.0.1-1.20.1-forge.jar
- create_connected-0.7.2-mc1.20.1-all.jar
- dynamiclightsreforged-1.20.1_v1.6.0.jar
- entityculling-forge-1.6.2-mc1.20.1.jar
- ExtremeReactors2-1.20.1-2.0.77.jar
- FarmersDelight-1.20.1-1.2.3.jar
- ferritecore-6.0.1-forge.jar
- FramedBlocks-9.1.6.jar
- jei-1.20.1-forge-15.2.0.27.jar
- modernfix-forge-5.12.1+mc1.20.1.jar
- oculus-mc1.20.1-1.6.9.jar
- ParCool-1.20.1-3.1.0.6-R.jar
- Patchouli-1.20.1-81-FORGE.jar
- pipez-forge-1.20.1-1.2.6.jar
- pneumaticcraft-repressurized-6.0.13+mc1.20.1.jar
- rangedwirelessredstone-1.20-4.0.0.jar
- redstonepen-1.20.1-forge-1.3.20.jar
- resourcefulconfig-forge-1.20.1-2.1.2.jar
- resourcefullib-forge-1.20.1-2.1.23.jar
- rubidium-mc1.20.1-0.7.1a.jar
- rubidium_extras-1.20.1_v1.4.3.jar
- searchlight-1.20-forge-1.1.11.jar
- simpleplanes-1.20.1-5.2.3.jar
- Steam_Rails-1.5.3+forge-mc1.20.1.jar
- theoneprobe-1.20.1-10.0.1.jar
- tinygates-1.20-4.0.0.jar
- tinyredstone-1.20-5.0.1.jar
- worldedit-mod-7.2.15.jar
- ZeroCore2-1.20.1-2.1.41.jar

### Crash log

https://gist.github.com/ExotisDev/10befc0387e721c36332f25a7ceab057

**Comment by XFactHD** [comment]
This has been fixed in FramedBlocks 9.2.1, please update the mod.
