### ISSUE TITLE
[Bug]: Crash when launching

### ISSUE THREAD

**Issue by Reenzo220** [XFactHD/FramedBlocks#407]
### Minecraft version

1.20

### Forge version

47.0.19

### FramedBlocks version

9.2.1

### Describe the bug

when i launch my forge profile with the FramedBlocks mod added, the game crashes.
If i launch the profile without the FramedBlocks mod, it runs without any problems.

### How to reproduce the bug

launch the game with the mod installed

### Expected behavior

is there a solution for this?

### Additional details

When crashed, it gives Exit-Code: -1073740791 or the Exit-Code: -1. Here are the mods i use: 
[modlist.txt](https://github.com/XFactHD/FramedBlocks/files/14638941/modlist.txt)

### Crash log

https://gist.github.com/Reenzo220/80da31fba0cf4c4fc8fd8ef4e77adb74

**Comment by XFactHD** [comment]
You are using an ancient version of Forge. You need to update Forge to at least 47.1.3. Normally, the game should have shown you a nice dependency error screen, but due to a secondary error (which is what the crash report contains) unrelated to FramedBlocks the game crashed completely instead.

**Comment by Reenzo220** [comment]
its working now, thx :)
