### ISSUE TITLE
[Feature]: Corner Piece for Framed Vertical Silced Stairs and Framed Silced Stairs (Panel)

### ISSUE THREAD

**Issue by OberMarcLP** [XFactHD/FramedBlocks#409]
### Describe the feature

Is it possible to do like that, but it is filled in the left top corner..?

![image](https://github.com/XFactHD/FramedBlocks/assets/95079459/840a1bfb-6f4c-4758-a729-c0114b8dedf5)

**Comment by XFactHD** [comment]
That's currently not possible, none of the double variants have any connection behaviour, they are fairly "dumb" blocks. Some recent technical changes in the unreleased 1.20.4 version would allow for this in the future, so I'll consider it for 1.20.4 and later. This will however not be possible in 1.20.1 or earlier.

**Comment by XFactHD** [comment]
The requested shape and similar ones can be achieved in the upcoming 1.20.6 release with the various double stair blocks (Double Stairs, Divided Stairs, Sliced Stairs and their vertical equivalents).
