### ISSUE TITLE
directional wood rotation

### ISSUE THREAD

**Issue by Deragonis** [XFactHD/FramedBlocks#41]
so new thing once the wrench is added, the ability to rotate stacked blocks individually, so like with slabs, this would be possible;
![image](https://user-images.githubusercontent.com/27950401/126899747-8143a9e7-530d-4a8e-8065-c8e7cb56d627.png)

**Comment by XFactHD** [comment]
From the logic side this is already possible but there is currently an issue with the model manipulation that causes certain texture rotations to be nullified. I am currently looking into fixing that.

**Comment by XFactHD** [comment]
This is now fully implemented and will be included in the next version.
Thanks again for reminding me of this, I had totally overlooked the "unrotation" workaround I had in place that would have made this feature kinda pointless :D
