### ISSUE TITLE
[Bug]: Framed Inner Prism Corner lighting issue

### ISSUE THREAD

**Issue by nilsdx** [XFactHD/FramedBlocks#410]
### Minecraft version

1.20

### Forge version

47.2.0

### FramedBlocks version

9.2.1

### Describe the bug

Lighting issues on Framed Inner Prism Corners, where the block on top is either divided in two different light levels, or darkened.
![2024-03-25_21 28 18](https://github.com/XFactHD/FramedBlocks/assets/146097395/e23fb35d-faf5-4eee-a8f4-9cc4f5852989)
![2024-03-25_21 32 19](https://github.com/XFactHD/FramedBlocks/assets/146097395/bb155865-f50b-4ee0-83ed-38f62b4ff2d8)

### How to reproduce the bug

Place any Framed Inner Prism Corner.

### Expected behavior

The surface of the block should be flat, and not divided in two different light levels/darkened.

**Comment by XFactHD** [comment]
Are you using OptiFine, Rubidium, Embeddium or a similar mod?
Do you have the `experimentalForgeLightPipelineEnabled` set to true in the `forge-client.toml` as mentioned on the CurseForge page?

**Comment by nilsdx** [comment]
It appears that I didn't set the experimentalForgeLightPipelineEnabled to true, hence why the lighting on those blocks looked weird.

My apologies !

**Comment by XFactHD** [comment]
No worries, glad that fixed it. Thank you for confirming.
