### ISSUE TITLE
Right Triangular Pyramid(3 dimension slope corner)

### ISSUE THREAD

**Issue by Cuttleguy** [XFactHD/FramedBlocks#411]
### Describe the feature

I was building a building, and while building this building, I came across a problem while building the building. You see, I had a diagonal wall(To make it interesting, and I also wanted a sloped roof. Where the two met, I had a problem. There is no right triangular pyramid, which would allow you to merge these together. 
Think of it like this image:
![pyramid](https://github.com/XFactHD/FramedBlocks/assets/123271904/e0c2f677-3df3-4aa2-b274-962788a98af2)
You could have a diagonal wall beneath, and could connect it to the rest of the roof, with out there being the part hanging off seen in this photo:
![hanging](https://github.com/XFactHD/FramedBlocks/assets/123271904/6e242bfa-3a73-4106-9695-74feb8fff9e6)
It would make building with slopes so much easier. Please consider this!

**Comment by XFactHD** [comment]
Unless I'm misunderstanding what you mean, this is already covered by the Framed Prism Corner and Framed Threeway Corner and their inner variants

**Comment by Cuttleguy** [comment]
Is this in 1.18.2? Are these planned blocks or have they already been added?

**Comment by XFactHD** [comment]
Those blocks exist since at least 1.16.5, maybe even since 1.15.2.

**Comment by Cuttleguy** [comment]
Just tried it out, the threeway doesn't work, but the prism corner does! Thank you very much!
