### ISSUE TITLE
[Bug]: Shift clicking blocks in Framing-saw causes instance to crash.

### ISSUE THREAD

**Issue by Devilaux** [XFactHD/FramedBlocks#412]
### Minecraft version

1.20

### Forge version

47.2.21

### FramedBlocks version

9.2.1

### Describe the bug

java.lang.NullPointerException: Cannot invoke "xfacthd.framedblocks.common.crafting.FramingSawRecipe.makeCraftingCalculation(net.minecraft.world.Container, boolean)" because "this.menu.selectedRecipe" is null

Results of trying to shift-click blocks from the framing saw, to my inventory. 

### How to reproduce the bug

Shift clicking blocks from the framing-saw to my inventory.

### Expected behavior

Blocks moves from framing-saw to my inventory without crashing the game.

### Additional details

This is a personal modpack (for now) I'm trying to put together.

### Crash log

https://gist.github.com/Devilaux/3abc1111af48ef9578409e23553e1e3a

**Comment by Devilaux** [comment]
I just wanted to say that I'm an amateur when it comes to javascript, so please be kind :)

**Comment by XFactHD** [comment]
I'm unable to reproduce the issue with a minimal set of additional mods which I would have suspected to be involved (I can't load a modpack of that size in a development environment). Can you reproduce this issue consistently or does it happen randomly?

Sidenote: there's no Javascript involved here, Java (which MC mods are written in) and Javascript are related like a car and a carpet ;)

**Comment by Devilaux** [comment]
> I'm unable to reproduce the issue with a minimal set of additional mods which I would have suspected to be involved (I can't load a modpack of that size in a development environment). Can you reproduce this issue consistently or does it happen randomly?
> 
> Sidenote: there's no Javascript involved here, Java (which MC mods are written in) and Javascript are related like a car and a carpet ;)

Thank you for the reply!

I will try and replicate it later today (I dissabled the mod whilst waiting for a reply).

Yeah, I meant to write "Java" and not "javascript" ( I do actually ponder with JS on websites a bit) :D

**Comment by Devilaux** [comment]
Hi again.

I've tried and tried and not been able to reproduce the issue, so it might have been a fluke. I'll close the issue and re-open/add new if I come over it again.
