### ISSUE TITLE
[Bug]: Framed Sloped Slab Can't Place Upside Down

### ISSUE THREAD

**Issue by Idefkftt** [XFactHD/FramedBlocks#415]
### Minecraft version

1.20

### Forge version

47.2.20

### FramedBlocks version

9.2.1

### Describe the bug

The Framed Sloped Slab can not be placed upside down even though the Framed _Elevated_ Sloped Slab can, which leads me to believe this constitutes a bug and not a feature request.

### How to reproduce the bug

Attempt to place one so that the elevated point sits in the middle of the block and the end or bottom of the slope sits at the top of the block.

### Expected behavior

Block should place upside down to fit with the cut off portion of the elevated counterpart.

**Comment by XFactHD** [comment]
The Framed Slope Slab can be placed upside-down, the way it works is unfortunately not intuitive though: you need to crouch to flip it. I can't think of a way to make this less cumbersome and documenting the various special behaviors is a slow and annoying process.
