### ISSUE TITLE
[Feature]: Framed Adjustable Divided Cube

### ISSUE THREAD

**Issue by AlisonHuang777** [XFactHD/FramedBlocks#417]
### Describe the feature

So basically, this block is just Framed Double Slabs or Framed Double Panels but you can adjust the partition's location (by Framed Hammer), so you can have, for example, 1/4 + 3/4 partitioning or 1/16 + 15/16 partitioning.
This concept can be applied to any rectangular (partitioned) block:
- Framed Adjustable Divided Slab/Panel
- Framed Adjustable Checkered Cube/Slab/Panel

Also, one may use Framed Screwdriver to toggle the rendering mode between normal mode and copycat mode.

**Comment by XFactHD** [comment]
I like the idea, but it would only be viable to do this for panels and slabs and the normal and copycat blocks would also be separate for simplicity. I'll add it to the list of planned blocks.

**Comment by migmolrod** [comment]
I'm a bit confused with this, since I'm not English native speaker. But I wanted to open a feature suggestion to be able to achieve this:
![image](https://github.com/XFactHD/FramedBlocks/assets/5715026/b8337a2c-1dcf-43c1-bdf9-c3135904b741)
(this is "photoshoped" by me to explain what I wanted to suggest)

And this issue left me wondering. Would this feature suggestion already cover what I've shown in the image above?

**Comment by XFactHD** [comment]
This suggestion is about a block like the Framed Double Panel where the position of the line between the two materials can be changed. What you are looking for is the Framed Double Threeway Corner Pillar which was introduced in FramedBlocks 9.2.0 for 1.20.1

**Comment by migmolrod** [comment]
> This suggestion is about a block like the Framed Double Panel where the position of the line between the two materials can be changed. What you are looking for is the Framed Double Threeway Corner Pillar which was introduced in FramedBlocks 9.2.0 for 1.20.1

Ah, I see. I won't be able to use it then :( I'm playing the Enigmatica 9 Expert modpack, which is for MC 1.19, not 1.20. Well, I'll try another way to "highlight" corners then.

Thanks for your response.
