### ISSUE TITLE
[Bug]: Half Frame Block Lava Crash

### ISSUE THREAD

**Issue by n3olink** [XFactHD/FramedBlocks#418]
### Minecraft version

1.20

### Forge version

1.20.1

### FramedBlocks version

9.2.1

### Describe the bug

Putting framed panels next to a lava column crashes the game.

### How to reproduce the bug

You can see the whole process in this video: [youtube](https://youtu.be/FS6ltG1SXdI)

### Expected behavior

I have the fireproof config set to true so it shouldn't be affected. But even without the config the bug is happening.

### Crash log

https://mclo.gs/KXYH4ZI

**Comment by XFactHD** [comment]
Rubidium's fluid block renderer is broken, you need to update Rubidium or preferably switch to Embeddium.
