### ISSUE TITLE
[Feature]: Corner Wall Panels 

### ISSUE THREAD

**Issue by ShaneCourtrille** [XFactHD/FramedBlocks#419]
### Describe the feature

Having a wall panel that can be used in the corner would be great unless there is some sort of secret for having two beside each other.

**Comment by XFactHD** [comment]
That's not possible at the moment. I was previously on the fence about this but considering this is requested pretty frequently, I'll add it to the list of planned blocks. I'm not quite sure yet how I'll handle adding an removing parts though.

**Comment by ShaneCourtrille** [comment]
@XFactHD Another option that I'm assuming would be simpler (though I'm a bit confused why it wouldn't already exist) would be a "Framed Divided Cube" which would really just be two panels side by side.  Basically I want to do an interior/exterior wall without having to use Framed Divided Slopes which can be a pain to work with (though I'd still have to use them for windows which I'm good with).  

Another benefit is that this avoids the whole Wall\Floor conflict issue that exists.

**Comment by XFactHD** [comment]
Double panels and double slabs exist, they just don't have their own item and instead work like vanilla double slabs where you just click the "inner" face of the slab/panel with a second one to make it a double variant. The placement preview also indicates this behavior.

**Comment by Marshall2439** [comment]
Hey would you guys add horizontal divided slopes and slope panels? Please reply i need those to make train locomotive

**Comment by XFactHD** [comment]
@Marshall2439 please make your own issue with more details about what you are requesting instead of hijacking someone else's unrelated issue.

**Comment by Marshall2439** [comment]
> @Marshall2439 please make your own issue with more details about what you are requesting instead of hijacking someone else's unrelated issue.

Ok

**Comment by XFactHD** [comment]
Closing in favor of #433
