### ISSUE TITLE
Crash when trying to break Slope with block from the Chisel mod in it

### ISSUE THREAD

**Issue by NielsPilgaard** [XFactHD/FramedBlocks#42]
I attempted to break a FramedBlocks Slope that had a Chisel block inside it, which resulted in a crash.

https://gist.github.com/NillerMedDild/2b5b959794351ad5c0027b5375df2660

### Versions
- Chisel-MC1.16.5-2.0.1-alpha.4
- FramedBlocks-2.9.2
- Forge-1.16.5-36.2.1

Also reported to Chisel here: https://github.com/Chisel-Team/Chisel/issues/887

**Comment by XFactHD** [comment]
Fixed, new release is on the horizon but I want to get a feature done before releasing.
