### ISSUE TITLE
Crash involving Rendering overlay [Bug]: 

### ISSUE THREAD

**Issue by MalakiteNebula** [XFactHD/FramedBlocks#421]
### Minecraft version

1.19

### Forge version

45.2.0

### FramedBlocks version

8.0.2.

### Describe the bug

Get the message while loading up the game, " The game crashed whilst rendering overlay
Error: net.minecraftforge.fml.ModLoadingException: FramedBlocks (framedblocks) encountered an error during the common_setup event phase " with Exit Code:-1. 
Was working fine a day ago but all of a sudden I can't load up the world. 

### How to reproduce the bug

I play on a custom modpack I made myself and whenever I load the game it'll load up till the red Mojang area and then crash and give me the error.
These are the mods involved in the modpack: 
![Modpack 1](https://github.com/XFactHD/FramedBlocks/assets/166937268/7becd5fa-e966-4772-8387-e323ad32f7c0)
![modpack 2](https://github.com/XFactHD/FramedBlocks/assets/166937268/07d33f70-8f52-4a3f-9f86-98d5c33e9905)
![modpack 3](https://github.com/XFactHD/FramedBlocks/assets/166937268/e7f07883-457e-4005-b255-585d43ff8ada)
![modpack 4](https://github.com/XFactHD/FramedBlocks/assets/166937268/1bb41d4d-60d3-41ee-872b-8573e5073171)
![modpack 5](https://github.com/XFactHD/FramedBlocks/assets/166937268/0e5bcee0-804c-4d31-b50c-96d2959ea7ec)
![modpack 6](https://github.com/XFactHD/FramedBlocks/assets/166937268/cc6737a4-b11e-4bee-b1e9-c6cdaca9a0a7)
![modpack 7](https://github.com/XFactHD/FramedBlocks/assets/166937268/0c332955-d1f9-408b-ab1a-726edb946fdb)
And waystones-forge-1.19.4-13.1.0.jar and worldedit-mod-7.2.14.jar

### Expected behavior

Expected the world to load normally and can enter it with no issue. 

### Additional details

The only solution I found was completely removing Framed Blocks but that of course deleted all blocks in the mod and ruined my build so I would like to see if there is a solution that involves keeping the mod since I'm trying to get back to the build as it originally was. 

### Crash log

https://gist.github.com/MalakiteNebula/10e76350e2b5ab925f4b1d003e45dcad#file-gistfile1-txt

**Comment by XFactHD** [comment]
This issue has been fixed in 1.19.2 and 1.20.1. Due to Mojang's new release policy, 1.19.4 was merely a stepping stone towards 1.20 and was dropped when 1.20 was released. As such it won't get any further updates. I would highly recommend updating to 1.20.1 as basically nobody supports 1.19.4 anymore.
