### ISSUE TITLE
[Bug]: Spectator placement preview

### ISSUE THREAD

**Issue by Rilivaine** [XFactHD/FramedBlocks#423]
### Minecraft version

1.19

### Forge version

43.3.8

### FramedBlocks version

6.8.6

### Describe the bug

When in spectator mode placement preview is still shown.

### How to reproduce the bug

Enter into spectator mode while holding block that will show placement preview.

### Expected behavior

Placement preview should have been hidden in spectator menu

### Additional details

![image](https://github.com/XFactHD/FramedBlocks/assets/152202287/57a6f462-5e16-47cc-9994-e5fd129a3a97)

**Comment by XFactHD** [comment]
I forgot that spectator mode is weird and doesn't "clear" the player's held items.
Since this is not a critical issue and support for 1.19 has been dropped a while ago, the fix for this will only be implemented in 1.20.1 and later versions.
