### ISSUE TITLE
[Feature]: Framed Tank

### ISSUE THREAD

**Issue by AlisonHuang777** [XFactHD/FramedBlocks#426]
### Describe the feature

Why not? We already have Framed Chest and Framed Secret Storage for storing items, but we don't have a counterpart for fluids.

**Comment by XFactHD** [comment]
I can see that being useful, though I'm not sure on what kind of shape would be better (i.e. more along the lines of ThermalExpansion's tanks or just a simple full-cube tank). I'll have to think about that some more.

**Comment by AlisonHuang777** [comment]
I prefer the shape being a full block, so I can hide it into a wall, like what a Framed Secret Storage does.

**Comment by XFactHD** [comment]
That sounds reasonable. Though, I'll make it so that tank windows can be toggled.

**Comment by wantedkeks** [comment]
As a reference.. The multiblock-furnace in Tinkers Construct can be made of different blocks (e.g. full blocks, window/glass ones). May this possible for a framed tank too, to decide if I want to have a window to see the fluid / tell the multiblock tank that i would like to see the fluid.

**Comment by XFactHD** [comment]
I have no plans for adding multiblocks, this tank will be a very simple single-block tank.
