### ISSUE TITLE
[Bug]: The hitbox of Framed Collapsible Copycat Block being part of a contraption is incorrect

### ISSUE THREAD

**Issue by AlisonHuang777** [XFactHD/FramedBlocks#427]
### Minecraft version

1.20

### Forge version

NeoForge 47.1.99

### FramedBlocks version

9.2.1

### Describe the bug

![2024-04-20_20 45 32](https://github.com/XFactHD/FramedBlocks/assets/51637996/428159e8-6403-4fa6-a683-09457b81be80)

### How to reproduce the bug

See above section.

### Expected behavior

The hitbox should be *collapsed* as well.

### Additional details

Create version: 0.5.1.f.
Playing Prominence II Classic modpack (modified instance).

**Comment by XFactHD** [comment]
This is an issue in Create, they are not providing the data that is necessary to create the collision shape of the Framed Collapsible Block and the Framed Collapsible Copycat Block and as such can only be fixed on their side.
