### ISSUE TITLE
[Feature]: Hollow Framed Block

### ISSUE THREAD

**Issue by Bonobo-Priest** [XFactHD/FramedBlocks#429]
### Describe the feature

A basic framed block, which is hollow in the middle with a 2 pixel border.

Akin to Quark or Twilight Forest hollow logs, as seen below.

![2024-04-24_18 56 20](https://github.com/XFactHD/FramedBlocks/assets/167982386/b67ad87e-9336-4e01-81fa-d6b6429fb3fa)

![2024-04-24_18 56 15](https://github.com/XFactHD/FramedBlocks/assets/167982386/59568025-346a-4da5-87cf-b46b36b53c83)

This is to make a block that is possible to crawl through, without using panels on the exterior, which doesn't work for corners.

![2024-04-24_19 09 59](https://github.com/XFactHD/FramedBlocks/assets/167982386/68ef5819-59c2-4af8-854a-1348993e0c11)

To prevent bloating the JEI, an idea could be to use the framed hammer on the block in-world, doing so would open the side, letting the block be using as simple dead ends, up to 6-sided intersections.

**Comment by Bonobo-Priest** [comment]
The crawling-through is just my use case, it could be used for various purposes such as chimneys you can see out of, or a fancy way to make windows without glass, or barrels with openable lids etc, whilst retaining the 1-block space instead of using 5 for 1 block length.

**Comment by XFactHD** [comment]
Sounds like a reasonable addition, though I'll have to check whether vanilla allows crawling through that by default or whether TF/Quark have any additional logic to make that possible. One thing that's worth noting though is that for camos like logs these blocks would use the bark texture even on the inside and not the stripped texture like TF's/Quark's blocks are doing.

**Comment by Bonobo-Priest** [comment]
Can't have everything! Quark definitely does have some special coding for it, as holding shift sends you straight into it, I don't think that would be a necessary feature as most people could hopefully intuit just using a trapdoor. (emphasis on hopefully!)
