### ISSUE TITLE
[Bug]: Magma blocks cause weird shadows in framed cubes

### ISSUE THREAD

**Issue by Lolothepro** [XFactHD/FramedBlocks#431]
### Minecraft version

1.20

### Forge version

NeoForge 47.1.105

### FramedBlocks version

9.2.2

### Describe the bug

Magma blocks cause weird shadows in framed cubes

Magma block in framed cube:
![2024-04-28_11 58 08](https://github.com/XFactHD/FramedBlocks/assets/68275908/31fbcb76-b668-42bc-a490-092435752ea0)

Normal magma block:
![2024-04-28_11 58 13](https://github.com/XFactHD/FramedBlocks/assets/68275908/a7534e88-f8a2-4ec4-a090-9e5c8c3c7ac6)

### How to reproduce the bug

Add a magma block in a framed cube

### Expected behavior

That the emissivity of the magma block is correctly rendered

**Comment by XFactHD** [comment]
This is unfortunately not fixable on 1.20.1, in part due to API limitations and in part due to how broken the experimental light pipeline is in that version in relation to emissive blocks like the magma block.
