### ISSUE TITLE
[Bug]: Some blocks are not visible in "Framed Prism Corner" with water

### ISSUE THREAD

**Issue by Lolothepro** [XFactHD/FramedBlocks#432]
### Minecraft version

1.20

### Forge version

NeoForge 47.1.105

### FramedBlocks version

9.2.2

### Describe the bug

Some block faces are not rendered like
when the angle of the camera is like this, the ice block is not visible:
![2024-04-28_12 08 42](https://github.com/XFactHD/FramedBlocks/assets/68275908/bd59f5e5-307b-4446-b5ba-8f091fc0cc55)

but it's visible on the other side:
![2024-04-28_12 08 49](https://github.com/XFactHD/FramedBlocks/assets/68275908/83613e8c-eca9-4d39-881f-966001214726)

https://github.com/XFactHD/FramedBlocks/assets/68275908/9cdc3c7b-360f-4b4e-bff3-8ff0caec7ff0

### How to reproduce the bug

Place two "Framed Prism Corners" (see screenshot and video), put ice in one and water in the other.
See

### Expected behavior

That ice be rendered through water

**Comment by XFactHD** [comment]
This is a vanilla issue, their translucency sorting seems to be failing when it tries to sort the triangle shape. There is nothing I can do about this, the only possible change I could do would just change in which cases this happens.

**Comment by Lolothepro** [comment]
Ah yes, it works with Sodium translucency sorting.
