### ISSUE TITLE
[Feature]: A block that can have different textures for each face of the block

### ISSUE THREAD

**Issue by AlisonHuang777** [XFactHD/FramedBlocks#435]
### Describe the feature

Like this:
![example](https://github.com/XFactHD/FramedBlocks/assets/51637996/ad9cec18-e91f-4195-a98c-08e7f503a1be)
(I done this with AE2's facades)

**Comment by XFactHD** [comment]
The limit of two camos per block is something I decided on a while ago for technical reasons (data size, resilience against things like chunk banning, relative simplicity) and it is deeply engrained in the whole mod. As such this is neither viable nor something I want to add.
