### ISSUE TITLE
[Bug]: 1.20 Failure to load with XK's Decor

### ISSUE THREAD

**Issue by Paulie820** [XFactHD/FramedBlocks#437]
### Minecraft version

1.20

### Forge version

47.2.29

### FramedBlocks version

9.2.2

### Describe the bug

Error during sided setup causes a failure to load the game.

### How to reproduce the bug

Load with XK's Decor and the partner mod to Supplementaries, Amendments. Note, removing Amendments allows the game to load, as will removing XK or removing FramedBlocks

### Expected behavior

The game loads to the main menu

### Additional details

This issue was brought to the github for XK's Deco but I was told to redirect to FramedBlocks. See the issue with other information here: https://github.com/teaconmc/XKDeco/issues/31

**Comment by XFactHD** [comment]
This is caused by an interaction between XKDeco and Moonlight/Amendments, see my response on the XKDeco issue
