### ISSUE TITLE
Seems to be crashing with oprifine

### ISSUE THREAD

**Issue by ShardUsers** [XFactHD/FramedBlocks#44]
When I go to break the blocks it seems to crash the game I have optfine installed.   [crash-2021-08-02_04.06.34-client.txt](https://github.com/XFactHD/FramedBlocks/files/6916419/crash-2021-08-02_04.06.34-client.txt)

**Comment by ShardUsers** [comment]
Never mind doesn't seem to have anything to do with optifine

**Comment by XFactHD** [comment]
Duplicate of #42
