### ISSUE TITLE
[Question]: vertical double frame

### ISSUE THREAD

**Issue by 9192jks** [XFactHD/FramedBlocks#440]
### Question

Hello, I'm a user who is using your mod to good use. First of all, thank you for making this mod from the bottom of my heart. I don't speak English, so I'll ask questions through Google Translator. Please understand that there may be mistranslation.
I'd like to have a double vertical block.
However, I downloaded the latest version mod from Cusforge, but I can't find the block I want. Is there something wrong with me.
Attached is the picture, I need the frame shown in the red circle.
![1](https://github.com/XFactHD/FramedBlocks/assets/158182629/2a55d0dc-b28f-4971-b500-dafc2ec3b321)
![2](https://github.com/XFactHD/FramedBlocks/assets/158182629/e7b7e5e8-c728-473f-b305-97720a9e3095)

**Comment by 9192jks** [comment]
I tried double searching where I search for JEI mod, but I couldn't find the corresponding frame I wanted.

**Comment by XFactHD** [comment]
The Framed Double Slab and the Framed Double Panel (the block you marked) are built the same way you would make double slabs in vanilla: place one slab or panel and the click it with a second one to make the double block. The placement preview indicates this as well.

**Comment by 9192jks** [comment]
thank you so much
