### ISSUE TITLE
[Feature]: Tag Reflection

### ISSUE THREAD

**Issue by Jophire** [XFactHD/FramedBlocks#445]
### Describe the feature

After looking through closed and open issues and not seeing this mentioned, I have a new request.
Could frame blocks take on the block tags of the blocks they are showing.

For example, with serene seasons installed, most glass blocks have the block tag #sereneseasons:greenhouse_glass. This allows crops within 12(?) blocks below to grow out of season. If I wanted to make a neat looking slanted greenhouse using sloped frames, I would need to make it 3 blocks thick to account for the bottom slope, full glass block, then top slope. However, if the framed blocks reflect the block tags of the camo block, then any framed block would be viable as a greenhouse block just by using a valid #sereneseasons:greenhouse_glass block.

No camo so you can see the framed slopes clearly(glass camo made them hard to see.)
![image](https://github.com/XFactHD/FramedBlocks/assets/36978900/4431d9cf-cd64-4846-bf0b-8d622f79c7b7)
Left: What you have to build currently if you want a valid greenhouse with sloped glass roof.
Right: What I would like to build instead if framed blocks reflect the block tags of the camo applied to them.

**Comment by XFactHD** [comment]
This is unfortunately not possible, the game does not provide any way to have a block pretend that it has a tag under certain conditions, especially not based on dynamic data like the camo applied to a framed block.

The only way to make this work would be for Serene Seasons to provide an API that allows me to tell them dynamically whether the block is a valid greenhouse block depending on its camo, though that would of course be mod-specific and not all-encompasing like your suggestion.
