### ISSUE TITLE
[Feature]:  more 1/4 blocks

### ISSUE THREAD

**Issue by Noctinae** [XFactHD/FramedBlocks#446]
### Describe the feature

Hi, I really like the mod, but I would like to ask for a few blocks. You see, the mod is almost perfect for making "circles," but it needs 1/4 blocks to really complete the circle aspect of the mod. There is already the slab corner, and the only one I'm asking for at the moment would be a slab slope, kind of like this:

<img width="825" alt="image" src="https://github.com/XFactHD/FramedBlocks/assets/80180703/3fe8cfc3-f2d4-47e4-960e-04b2dd745ce2">

thank you for making this great Mod :D

**Comment by Noctinae** [comment]
Sorry if the post is a duplicate i'm not a big Github user ^^'

**Comment by XFactHD** [comment]
This shape was added in FramedBlocks 9.2.0 for 1.20.1 and called "Framed Slope Edge".
