### ISSUE TITLE
[Feature]: Framed Sliced Stairs Corner Blocks

### ISSUE THREAD

**Issue by Eclipse4044** [XFactHD/FramedBlocks#457]
### Describe the feature

An issue I ran into was not being able to make corner stairs with either of the framed sliced stair blocks. I would think it would be great to be able to have this as a feature.
![2024-06-28_15 31 46](https://github.com/XFactHD/FramedBlocks/assets/174154515/dd4b0a98-502b-4467-801a-3ff8153900c3)
![2024-06-28_15 31 56](https://github.com/XFactHD/FramedBlocks/assets/174154515/9c7191e6-3a43-4780-ab19-0137611366d3)

**Comment by XFactHD** [comment]
This is possible in the 1.21 release of FramedBlocks due to all two-material stairs blocks now having vanilla stairs connection behavior. Back porting this to 1.20.1 is unfortunately not possible for technical reasons.
