### ISSUE TITLE
[Feature]: Support for XyCraft: World connected textures

### ISSUE THREAD

**Issue by adroslice** [XFactHD/FramedBlocks#459]
### Describe the feature

As of atm9sky, using these two mods together produces some odd behavior in which the "Trim" blocks from XyCraft correctly connect to framed blocks, but the same isn't true in reverse, leading to a rather jarring effect:
![image](https://github.com/XFactHD/FramedBlocks/assets/20285224/ce9479f0-f8de-4080-bd7e-4174dd90230e)

What I would like to see is an implementation that either disables the connectedness for these blocks or one that allows the connection to work properly. If this is something that needs to be implemented on Soaryns side, please let me know so I can relay the information through his issue tracker.

**Comment by XFactHD** [comment]
This is a known issue with XyCraft, their connected textures implementation has a bug in 1.20.1 which causes these connection issues. The underlying bug is fixed in the 1.21 release of XyCraft. You'd have to ask them whether they're interested in backporting the fix.
