### ISSUE TITLE
[Mod Compatibility] ColorUtility

### ISSUE THREAD

**Issue by Erysch** [XFactHD/FramedBlocks#46]
[ColorUtility](https://www.curseforge.com/minecraft/mc-mods/colorutility) by axeryok adds a Color GUI to sign editing, anvil renaming and book and quills.

But this GUI does not open when placing a Framed Sign.
It would be nice if it does.

I wrote another post on the other author's github since I don't know which author has to change something on their code.
[#3](https://github.com/Axeryok/ColorUtility/issues/3)

Greetings (=

**Comment by XFactHD** [comment]
Unfortunately there isn't anything I can do about this at the moment because their source code for any version newer than 1.12 is not public.

**Comment by Erysch** [comment]
> Unfortunately there isn't anything I can do about this at the moment because their source code for any version newer than 1.12 is not public.

Ah okay! Thanks for the info.
Maybe they react to my post on their github page.
