### ISSUE TITLE
[Bug]: Lighting on offset textures.

### ISSUE THREAD

**Issue by sybrenosinga** [XFactHD/FramedBlocks#465]
### Minecraft version

1.21

### (Neo)Forge version

47.2.20

### FramedBlocks version

9.3.0

### Describe the bug

In atm9 (framedblocks version 9.3.0) the blocks that are offset by half a block (prism blocks) display two different lighting shades. Toggling the offset removes the error, but the texture itself is better offset. The effect seems to differ dependent on the viewing angle.

A few screenshots of prism corners, both up and down, and their inner variants.
![2024-07-19_17 27 08](https://github.com/user-attachments/assets/ffc29dc7-06f8-4080-8642-33346f441314)
![2024-07-19_17 27 10](https://github.com/user-attachments/assets/a308c587-47e8-4d60-8b7f-6391bd4ce9a3)
![2024-07-19_17 18 00](https://github.com/user-attachments/assets/a9d33b21-5dee-493f-96b1-13caefabf909)

### How to reproduce the bug

Place prism block in all cardinal directions, and don't change the default offset.

### Expected behavior

lighting color is the same across the block

**Comment by XFactHD** [comment]
You need to enable the `experimentalForgeLightPipelineEnabled` setting in the `neoforge-client.toml` config file, the vanilla block lighting system is not capable of rendering these kinds of shapes properly

**Comment by sybrenosinga** [comment]
That fixed it, thank you! Was just forge-client.toml btw
