### ISSUE TITLE
[Feature]: Rotated Framed Masonry Corner

### ISSUE THREAD

**Issue by OlasHSW** [XFactHD/FramedBlocks#466]
### Describe the feature

in mod, we have Framed Masonry Corner:
![image](https://github.com/user-attachments/assets/a022dfd5-9897-497f-ba04-8f8ca0ee738e)
but i can't rotate it to looks like this:
![image](https://github.com/user-attachments/assets/a17fd5c5-4847-4dcc-a060-78b99423461e)
so it could be looks like this:
![image](https://github.com/user-attachments/assets/bbbac7b2-dafe-4851-a2e6-80389d5e7ddd)
could you add rotated version of Framed Masonry Corner (or edit rotate of normal version)? or maybe there is solution to my problem but i can't see it. Thank u for all work you do!

**Comment by XFactHD** [comment]
If I understand it correctly, all you need is to be able to mirror the block vertically, in which case, sure, that sounds reasonable, I'll add it to the list of planned features
