### ISSUE TITLE
[Bug]: Powered Framing Saw not displaying configured target

### ISSUE THREAD

**Issue by andriihorpenko** [XFactHD/FramedBlocks#467]
### Minecraft version

1.20

### (Neo)Forge version

47.1.106

### FramedBlocks version

9.3.0

### Describe the bug

When configuring a Powered Framing Saw with an item, the Target slot visually remains blank.

https://github.com/user-attachments/assets/ab7a9874-c43a-48da-b607-7fbaaa51e9e9

### How to reproduce the bug

Simply drag any FramedBlocks block into a Target slot (via JEI or from inventory). The recipe gets configured, but the slot remains blank.
Note that functionally, the saw works just fine.

### Expected behavior

Display configured recipe in the Target slot.

**Comment by XFactHD** [comment]
Looks like Embeddium and friends don't like the approach I used for those ghost items and I never backported the cleanup for that from 1.21. Simple fix :D
