### ISSUE TITLE
[Feature]: "half" version of Framed Slope Slab and Framed Compound Slope Slab

### ISSUE THREAD

**Issue by OlasHSW** [XFactHD/FramedBlocks#469]
### Describe the feature

We have Framed Slope Slab and Framed Compound Slope Slab:
![image](https://github.com/user-attachments/assets/80326012-061b-4958-bb03-eace8f7438fb)

but we don't have a "half" version of this blocks:
![image](https://github.com/user-attachments/assets/179cd3df-e7f3-4d5d-86f0-9b15640b2494)

It will be helpful with roof ends, becouse with normal size sometimes seems to be too long.
Thanks for accepting the previous idea!

**Comment by XFactHD** [comment]
Duplicate of #288.
These shapes are already planned.
