### ISSUE TITLE
Extended framed shapes [Feature]: 

### ISSUE THREAD

**Issue by Arch23-tech** [XFactHD/FramedBlocks#472]
### Describe the feature

Round frames ,  framed Round pillars, framed sphere, framed wall cornic and framed boat (if possible)

**Comment by XFactHD** [comment]
All of these are unfortunately not possible for technical reasons, any actually round shapes would kill performance and boats are entities while the entirety of FramedBlocks is based on working with blocks (which is for example the reason why the Framed Item Frame is a block and not an entity like the vanilla Item Frame).
