### ISSUE TITLE
Support with Create: TrainUtilities [Mod Support]: 

### ISSUE THREAD

**Issue by ProgrammerLP** [XFactHD/FramedBlocks#473]
### The mod to integrate with

Create: TrainUtilities

### Describe the feature

Hi,
i am the developer of the mod, create: trainutilities, and got some reports that blocks of my mod are not compatible with the blocks of FramedBlocks so i asked for supporting it!

thanks

**Comment by XFactHD** [comment]
Can you go into more detail how blocks from your mod are incompatible with FramedBlocks?

**Comment by ProgrammerLP** [comment]
Of course:
Some blocks cannot be placed in at all and some other makes the framedblock invisible.

Like this
![Screenshot_20240730_010108_Discord.png](https://github.com/user-attachments/assets/14cd95fe-0e3e-4175-bfaf-423d0e2cc9ee)

**Comment by ProgrammerLP** [comment]
Or what should I do to make them compatible? @XFactHD

**Comment by XFactHD** [comment]
There are two separate issues going on here:
1. For simplicity's sake, FramedBlocks only supports full cubes as camo blocks. If a given block is not see-through in any way, then I can trivially check that the block is a full cube. If the block is however see-through (vanilla glass for example), then I have no way to check that (collision shape does not suffice as the model may not fill the shape out entirely). To solve this, these blocks must be tagged with `framedblocks:frameable` block tag. By default this tag contains the glass tag (`forge:glass` on 1.20.1 and before, `c:glass` on 1.21), the `minecraft:leaves` and `minecraft:ice` tags and a few mod entries. If your blocks don't fit any of the included tags, then you need to tag your blocks with `framedblocks:frameable`
2. FramedBlocks only uses cullable quads to generate the models as there is usually no reason to not cull quads on a given side if the side is covered by a neighboring block and it prevents issues with full cube blocks having quads that don't touch the cube volume's edges (inner cube in a slime block for example). To fix this you need to correctly specify the `cullface` parameter in your block models (see https://minecraft.wiki/w/Model#Block_models for more details)

This should fix both issues you are encountering

**Comment by ProgrammerLP** [comment]
ok thanks, i will try that

**Comment by ProgrammerLP** [comment]
I run into one major problem. I have to blocks they are defined as shown in the image:
![grafik](https://github.com/user-attachments/assets/94feb2a5-b036-4b06-abde-c6697beca3b0)

i already tried to give them framedblocks:frameable tag but i doesnt work. They cannot be placed in the framedblocks.
The two blocks look like this:
![grafik](https://github.com/user-attachments/assets/bcebfcef-d174-4e10-a661-7c91d8b2420f)

**Comment by XFactHD** [comment]
Does it show any message above the hotbar when you attempt to use these specific blocks on a framed block? If these blocks have a `BlockEntity` (i.e. they implement `EntityBlock`, whether `EntityBlock#newBlockEntity()` returns a non-null value doesn't matter), then they cannot by default be used as a camo.

**Comment by ProgrammerLP** [comment]
no, theres now message, just nothing happens

**Comment by XFactHD** [comment]
If you place the affected blocks in the world, do they show the `framedblocks:frameable` tag in the F3 screen?

**Comment by ProgrammerLP** [comment]
yes they have 
![grafik](https://github.com/user-attachments/assets/65413d1c-c7a3-4d20-81a6-5f03a83e9e7a)

**Comment by ProgrammerLP** [comment]
ok nvm, for some reason it works now!

so thank you very much for your help! :smile:

**Comment by XFactHD** [comment]
Awesome. I'll close this as solved then.
