### ISSUE TITLE
[Bug]: Wrenches from other mods not compatible

### ISSUE THREAD

**Issue by Svetrikk** [XFactHD/FramedBlocks#476]
### Minecraft version

1.21

### (Neo)Forge version

21.0.150

### FramedBlocks version

10.1.3

### Describe the bug

Other wrenches (which have tag #c:tools/wrench, also tried adding #forge:tools/wrench. I have tried wrenches from AE2 and Modern Industrialization.) do not work with FramedBlocks

### How to reproduce the bug

-

### Expected behavior

Wrenches from other mods with the correct tag should work with FramedBlocks

**Comment by XFactHD** [comment]
The rotation currently checks a certain `ItemAbility` to properly support dynamic behaviour of multi-tools like Mekanism's Configurator (ignoring the fact that the Configurator currently doesn't expose that `ItemAbility`). Unfortunately it looks like almost no wrench item exposes the `wrench` ability I currently use nor the `wrench_rotate` ability I will be using going forward. I'll add a check for the `c:tools/wrench` tag as well as a check against `framedblocks:complex_wrench` to still be able to support multi-tools.
