### ISSUE TITLE
[Bug]: java.lang.IllegalArgumentException: Directions must be perpendicular

### ISSUE THREAD

**Issue by X-GMaster** [XFactHD/FramedBlocks#478]
### Minecraft version

1.18 - UNSUPPORTED

### (Neo)Forge version

40.2.21

### FramedBlocks version

5.11.5

### Describe the bug

Than you pick up framed slope panel in inventory, game just get crashed. However at start it didn't happened

### How to reproduce the bug

Than you pick up framed slope panel in inventory, game just get crashed.

### Expected behavior

Solutions to the problem?

### Crash log

https://gist.github.com/X-GMaster/fc4bfef5d387d51f9e7a419ff4dc02fc

**Comment by XFactHD** [comment]
1.18.2 is no longer supported and due to the age of the tools used in that version it can also no longer be built without significant effort. You can work around the issue by setting `showGhostBlocks` in the `framedblocks-client.toml` to `false`.

**Comment by X-GMaster** [comment]
Thank you!
