### ISSUE TITLE
Double 3-way corner and double prism corner appear identical

### ISSUE THREAD

**Issue by Syndaryl** [XFactHD/FramedBlocks#48]
I set up the corner blocks to look at so I could figure out which one I wanted, but the double 3-way corner and the double prism corner don't seem to have any differences.

I've arranged them with the same alignment, put up signs, and labeled the sides. The screenshots below show all 6 sides.

![2021-08-12_09 33 07](https://user-images.githubusercontent.com/8820565/129206878-a83651f2-f39f-4efb-8206-349a3fb7c220.png)
![2021-08-12_09 33 19](https://user-images.githubusercontent.com/8820565/129206880-52361c11-cfe1-4b7b-a24b-f87eb09c2b7e.png)
![2021-08-12_09 33 29](https://user-images.githubusercontent.com/8820565/129206881-149a27f1-1edb-401a-a04a-852c8ec0f71b.png)

**Comment by Syndaryl** [comment]
Here's a better shot of the tops

![2021-08-12_09 33 42](https://user-images.githubusercontent.com/8820565/129207630-67311d01-4ade-44aa-99c7-dd3ebdae1713.png)

**Comment by Syndaryl** [comment]
And here's the F3 screen confirming I haven't done a stupid and just placed the same one six times (which I initially thought I'd done and I've checked a bazillion times because they are so similar)
![2021-08-12_09 45 19](https://user-images.githubusercontent.com/8820565/129208232-def49a77-2202-4e1b-988e-8dad11ee0f02.png)
![2021-08-12_09 45 22](https://user-images.githubusercontent.com/8820565/129208236-689ba66b-666b-4b5a-bffe-48cbac66d37b.png)

**Comment by XFactHD** [comment]
That is intended. The double prism and double threeway corners are only noticeably different when at least one of the two parts has a transparent or semi-transparent block applied to it.
