### ISSUE TITLE
[Bug]: Framed Blocks is broken with "Arched Magenta Stained Glass Pillar" from Chipped

### ISSUE THREAD

**Issue by Lolothepro** [XFactHD/FramedBlocks#480]
### Minecraft version

1.21

### (Neo)Forge version

21.1.4

### FramedBlocks version

10.1.0

### Describe the bug

Framed Blocks is broken with "Arched Magenta Stained Glass Pillar" from Chipped
some faces are not rendered

### How to reproduce the bug

Use an "Arched Magenta Stained Glass Pillar" with a "Framed Inner Corner Slope".

### Expected behavior

Use an "Arched Magenta Stained Glass Pillar" with a "Framed Inner Corner Slope".

### Additional details

https://github.com/user-attachments/assets/283a93e5-5b6b-4a82-8575-63a9061438e0

**Comment by XFactHD** [comment]
I've narrowed this down to an issue in Athena, the connected textures implementation powering Chipped. I have let the Athena dev know about this.
