### ISSUE TITLE
[Bug]: Glowing framed  blocks don't stop mobs spawning on top of them.

### ISSUE THREAD

**Issue by radwadas** [XFactHD/FramedBlocks#483]
### Minecraft version

1.21

### (Neo)Forge version

21.1.8

### FramedBlocks version

FramedBlocks-10.1.3

### Describe the bug

I'm playing ATM10 (currently version 0.33). When adding glowstone to a framed block it emits light and prevents mob spawns around it as expected. However the mobs still can spawn directly on top of the framed block itself.
The light overlay mod doesn't mark the framed blocks as having sufficient or insufficient amount of light.
![2024-08-16_18 16 08](https://github.com/user-attachments/assets/3d719d4f-2634-4e6b-a252-52e0cf6cbc8a)

### How to reproduce the bug

Make a platform of framed blocks and add glowstone to them.
Set time to night and move far enough for mobs to spawn on the platform.

### Expected behavior

No mobs should spawn as all the blocks on the platform emit light.

**Comment by XFactHD** [comment]
I cannot reproduce this issue in both my dev environment as well as an ATM10 v0.33 world.
The fact that the light overlay is not shown on top of the light emitting framed blocks is expected: when a block says that it is not a valid spawn surface (which includes a check for light level of 14 or higher, glowing framed blocks emit level 15 by default), then the light overlay mod considers the position "blocked" and treats it the same way as if there were a solid block in the way. If you replace the light emitting framed blocks with vanilla glowstone blocks, then you will see the exact same behaviour.
As such I have to assume that these mobs either came from somewhere else (i.e. wandered in through the door) or another mod is breaking mob spawn checks in a way that my test in ATM10 did not trigger and there is nothing I can do about this.
