### ISSUE TITLE
[Question]: Adjustable Slabs/Panels

### ISSUE THREAD

**Issue by ashe-attacc** [XFactHD/FramedBlocks#487]
### Question

Hi! I saw in a recent update you added "framed adjustable double (copycat) slab/panel" and was wondering what they did? I didn't see anything on the Curseforge page clarifying anything. If I had to guess, they're probably just full-block variants of slabs and panels? But if that's the case, why two sets of each? What's the difference between normal adjustable double slabs/panels and double copycat slabs/panels? I tried right and left clicking with a hammer like I would with a normal Copycat block but nothing didn't seem to happen.
(Also unrelated and not really important but I'm still curious: What does reinforcing blocks do?)
Thanks in advance! Love the mod!!!

**Comment by XFactHD** [comment]
The adjustable double (copycat) slab and panel allow you to move the division between the two halves. To do so, you need to left click the full sides (i.e. top or bottom in the case of the slab) with a framed hammer. If you hit it without sneaking, the division will move away from you, if you hit it while sneaking, the division will move towards you.
As for the difference between copycat and non-copycat, that's a visual difference. The non-copycat variant just cuts the texture off at the division line while the copycat variant (which is inspired by Create's copycat blocks) takes the source texture and stitches it back together such that outer edge is retained on each of the two slabs/panels (on the left is the normal adjustable double slab and on the right is the adjustable double copycat slab):
![2024-08-24_01 28 15](https://github.com/user-attachments/assets/081a1713-0fcf-4ccf-be26-fadd30de6b6e)

Reinforcing a framed block gives it the explosion resistance of obsidian, that's all it does.

I hope that answers your questions.

**Comment by squigglezworth** [comment]
It might be a good idea to include these explanations in the mod's descriptions.

FramedBlocks <3

**Comment by XFactHD** [comment]
I have plans to include an in-game guidebook in the future which details these things but actually making this guidebook is very time-consuming which is why nothing on that front has happened yet.

**Comment by squigglezworth** [comment]
Out of curiosity, what sort of guidebook were you thinking? I've been slowly writing a Patchoulli guidebook for my server, which includes a FramedBlocks section, which I can share when finished if you'd like.

**Comment by XFactHD** [comment]
I'm personally not really a fan of Patchouli. My current plan is to use the new GuideME mod from the AE2 team.
