### ISSUE TITLE
[Question]: Wondering if there is a block that fills the space in the screenshot

### ISSUE THREAD

**Issue by EmmaRavens** [XFactHD/FramedBlocks#488]
### Question

Any block that can fill this space? Want to be sure I'm not missing anything
![image](https://github.com/user-attachments/assets/7ef09401-4881-4d76-a2aa-435ef37c4134)

On left side it is a Framed Slope and on the right side it is a Framed Extended Slope Panel
![image](https://github.com/user-attachments/assets/d1cc5fd7-6cea-4eb9-9edd-ccc5d7801ab6)

Possible solution, a way to lock the center of the Framed Collapsible Block and then move the corner to be able to fill the space in the screenshots above
![image](https://github.com/user-attachments/assets/d462971c-24b2-4caf-89c9-3db7a03a80cd)

**Comment by XFactHD** [comment]
There is no existing shape to fill that spot, but they've been planned for quite a while already, see #226.
Adapting the collapsible cube for this is not a good option, that block is already pretty complicated under the hood and would need to become significantly more complicated to accommodate a behaviour like this.
