### ISSUE TITLE
[Bug]: Can't add Glass blocks from Chisel Reborn mod to the framed blocks

### ISSUE THREAD

**Issue by EmmaRavens** [XFactHD/FramedBlocks#491]
### Minecraft version

1.21.1

### (Neo)Forge version

Neo - 21.1.23

### FramedBlocks version

10.1.4

### Describe the bug

[Chisel Reborn](https://www.curseforge.com/minecraft/mc-mods/chisel-reborn) version: 1.8.1

Can't place any glass type of block in the frames

### How to reproduce the bug

https://github.com/user-attachments/assets/8a372edc-27ec-4d18-80b9-e0267211a733

### Expected behavior

To be able to place glass type of blocks in the frames

### Additional details

Found out after posting this, that Quartz Glass from Applied Energistics 2 also doesn't work.
[AE2](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2) Version: 19.0.20-beta

**Comment by XFactHD** [comment]
For technical reasons, I cannot determine whether a non-solid[^1] block such as glass is actually a full cube. For that reason I require that these blocks have the `framedblocks:frameable` block tag. By default, this tag includes the `c:glass` convention tag which should catch glass blocks added by other mods unless they don't tag their glass blocks with that tag. Please report this to Chisel Reborn and AE2, they should either be tagging their glass blocks with the `c:glass` block tag or add it to `framedblocks:frameable` block tag directly if the glass tag is somehow unsuitable.

[^1]: Non-solid in this case means that the block is not guaranteed to be visually opaque. Stone and dirt are considered solid, glass and leaves are considered non-solid
