### ISSUE TITLE
[Bug]: Rain passes through Framed Horizontal Panels.

### ISSUE THREAD

**Issue by TheDragonOfFlame** [XFactHD/FramedBlocks#492]
### Minecraft version

1.21

### (Neo)Forge version

47.3.0

### FramedBlocks version

9.3.1

### Describe the bug

The framed horizontal panes I am using as a skylight do not block rain from falling into the base.

### How to reproduce the bug

Place horizontal panes and then do /weather rain.

### Expected behavior

I expected the rain to be blocked by the panes.

**Comment by XFactHD** [comment]
I did not expect rain to be so weirdly implemented, that's what I get for testing in a world where it never rains.
