### ISSUE TITLE
Blocklight issues

### ISSUE THREAD

**Issue by HipHopHuman** [XFactHD/FramedBlocks#5]
Hi! I tried using your mod recently and noticed the sloped blocks don't quite match the builds they are on when it comes to lighting. Is this something you are aware of / is there a workaround? 

Pic for reference: 
![image](https://user-images.githubusercontent.com/70091260/110220818-e2e6b580-7ed0-11eb-9711-288ff49ab6ae.png)

**Comment by XFactHD** [comment]
MC version?
Forge version?
FramedBlocks version?
Do you have Optifine installed?

**Comment by HipHopHuman** [comment]
MC: 1.16.5
Forge version: 36.0.46
FramedBlocks version: 2.3
Do I have Optifine: No, and no other mods that change rendering in any way

Sorry, I normally provide this information when I report issues, but I've tested your mod before and had this same issue, chalked it up to the mod just being new and decided to come back to it later

**Comment by XFactHD** [comment]
Found the problem. This is caused by limitations in the Minecraft render engine. To fix this, you need to make sure that the `forgeLightPipelineEnabled` and `experimentalForgeLightPipelineEnabled` settings in the forge-client.toml config file are set to true.

**Comment by HipHopHuman** [comment]
Thanks, it works wonderfully now

EDIT: Sorry, the lighting works wonderfully, but now there are rendering issues - here's a Framed Slope:

![image](https://user-images.githubusercontent.com/70091260/110258906-8a391a80-7fad-11eb-9ec4-fd41aba1b938.png)

**Comment by HipHopHuman** [comment]
Found more context here, I'll open a new issue
