### ISSUE TITLE
How do I fit two slopes together?

### ISSUE THREAD

**Issue by RubyFennex** [XFactHD/FramedBlocks#50]
It's on the picture on CurseForge, and I have been trying to figure it out for an hour. I need two slopes of different blocks to fit together. How do I do this?

**Comment by XFactHD** [comment]
The Framed Double Slope is a separate block and isn't built like the Double Slab and Double Panel. After placing the Double Slope you insert the two blocks in the same way as the Double Slab and Double Panel
