### ISSUE TITLE
[Feature]: Stack two vertical double half stairs in the same block

### ISSUE THREAD

**Issue by ron4821** [XFactHD/FramedBlocks#502]
### Describe the feature

Stack two framed vertical double half stairs in the same block (or a single framed vertical double half stair and a half slab).

Here is a screenshot describing the request!
![image](https://github.com/user-attachments/assets/2eb14a9f-01a4-4d14-a747-cc3a7b8386f0)

The left corner block in my build is the closest I can get to what I'm looking for (utilizing vertical double stairs).  The middle blocks are essentially what I would like (in full block form to show exactly where I would want each camo section).  I also included a photo shopped image as another example to help clarify the request.  

Also stacking a single framed vertical double half stair and a half slab would be nice as well.

Thanks for all you do, I love the mod! <3

**Comment by XFactHD** [comment]
Unfortunately neither of those are possible. The entire mod is based on blocks having at most two different camos, mainly for simplicity and performance, and these blocks would have three and four camos respectively.
