### ISSUE TITLE
[Bug]: Stuck on dirt screen when trying to load into 

### ISSUE THREAD

**Issue by Quacktus26** [XFactHD/FramedBlocks#503]
### Minecraft version

1.20

### (Neo)Forge version

Forge 47.3.10

### FramedBlocks version

9.3.0

### Describe the bug

Stuck on dirt screen when trying to load in, same when exiting and saving world, creating a new world causes no issues, only when either exiting newly created world or attempting to load into previous world, can only exit via task manager, alt+f4 would not work.

### How to reproduce the bug

Create new world, place frame blocks (I ussually placed adjustable double slabs), save and exit, it is then stuck on dirt screen, exit via task manager, try to enter world, same result.

### Expected behavior

World loads and unloads properly in a timely manner

### Additional details

It might be a mod incompatibility as I am using many mods, but it says nothing in the logs

Mods I use:
Enderman Overhaul
Presence Footsteps
Quark
[Let's Do] Candlelight - Farm&Charm compat
Immersive Snow
AmbientSounds
YUNG's Better Strongholds
[EMF] Entity Model Features
[Let's Do] BloomingNature
Entity Culling
[Let's Do] Meadow
Just Hammers
Cloth Config API
Curios API
[Let's Do] Furniture
Polymorph
Forgified Fabric API
ComplementaryReimagined_r5.2.2.zip.txt
YUNG's Better Jungle Temples
Not Enough Animations
Sinytra Connector
Immersive Paintings
Decorative Blocks
Moonlight Lib
Packed Up - A Farmer's Delight Addon
Just Enough Items
Creeper Overhaul
Small Ships
Vertical Slabs Compat
YUNG's Better Ocean Monuments
iChunUtil
Sound Physics Remastered
Geckolib
Resourceful Lib
fairylights-7.0.0-1.20.1.jar
[ETF] Entity Texture Features
Explorify
Farmer's Delight
RenderPearl
Jade 🔍
What Are They Up To (Watut)
YUNG's Better End Island
Immersive Melodies
FramedBlocks
YUNG's Better Nether Fortresses
[Let's Do] Bakery - Farm&Charm Compat
Embeddium
Fabric API
CreativeCore
[Let's Do Addon] Compat
Naturalist
Explosive Enhancement (Forge)
Caelus API
Puzzles Lib
Epic Knights: Shields Armor and Weapons
ChoiceTheorem's Overhauled Village
Vanilla Refresh
Oculus
Pehkui
YUNG's Extras
playerAnimator
Connectible Chains-forge-1.20.1-1.0.0.jar
ModernFix
Zeta
ComplementaryReimagined_r5.2.2 + EuphoriaPatches_1.3.2.txt
swem-1.20.1-1.4.0.jar
YUNG's Better Desert Temples
Supplementaries
born_in_chaos_[Forge]1.20.1_1.3.1.jar
Smarter Farmers (farmers replant)
First-person Model
YUNG's Better Witch Huts
Complementary Shaders - Reimagined
[Let's Do] WilderNature
[Let's Do] Vinery
[Let's Do] HerbalBrews
AppleSkin
You've Goat to be Kidding Me
[Let's Do] Farm & Charm
Make Bubbles Pop
YetAnotherConfigLib
YUNG's Better Dungeons
Memory Leak Fix
Geophilic Reforged
YUNG's Better Mineshafts
Jade Addons (Forge)
Better Combat
Quark Programmer Art.zip
[Let's Do] API
Amendments
Immersive Weathering
ImmediatelyFast
Continents
FerriteCore
CTOV - Farmer Delight Compat
Lithostitched
Let Sleeping Dogs Lie
Illager Invasion
LS RenderPearl v1.7.zip.txt
Every Compat (Wood Good)
YUNG's API
Patchouli
Resourceful Config
Antique Atlas 4
Exposure
CoroUtil
Villager Workers
Architectury API
[Let's Do] Camping
Via Romana: Infrastructure-Driven Fast Travel
YUNG's Bridges
Euphoria Patches
[Let's Do] Brewery - Farm&Charm Compat

**Comment by XFactHD** [comment]
Please try to reduce the list of mods to the minimum needed to reproduce this issue, debugging this with so many mods is impossible. I would recommend starting by removing Connector and the Fabric mods loaded through it and, if that doesn't fix it, continue by removing Sound Physics remastered. None of the other mods look problematic at a glance.

**Comment by Quacktus26** [comment]
It fixed itself :| How I don't know, but it did have something to do with the fabric mods specifically the fabric api not being up to date.

**Comment by XFactHD** [comment]
That's nice to hear and doesn't sound like an unreasonable cause. I'll close the issue as resolved for now, but don't hesitate to comment again if this issue should appear again.
