### ISSUE TITLE
[Bug]: Emissive textures are not emissive with Continuity (Sinytra + FFAPI)

### ISSUE THREAD

**Issue by Lolothepro** [XFactHD/FramedBlocks#504]
### Minecraft version

1.21

### (Neo)Forge version

21.1.52

### FramedBlocks version

10.1.4

### Describe the bug

Emissive textures are not emissive with Continuity (Sinytra + FFAPI)

![image](https://github.com/user-attachments/assets/51bd6f0f-948f-46a7-85ea-3ed6ae6c3675)

### How to reproduce the bug

https://modrinth.com/resourcepack/emissive-ores

Use this resource pack with Sinytra, Forgified Fabric API, Continuity and FramedBlocks

### Expected behavior

That emissive textures should be emissive with FramedBlocks

**Comment by XFactHD** [comment]
I've looked into it and it's unfortunately not possible to fix this at the moment. The code path FramedBlocks calls into does not reach Continuity's transformation code that applies these effects. It's not reasonable to expect this to be changed on Continuity's end and implementing support for FRAPI in FramedBlocks to make this work is also not realistic.

**Comment by Lolothepro** [comment]
Note: fixed in 26.1.2
