### ISSUE TITLE
[Bug]: Crash when placing a Framed Fence. (Invalid block entity framedblocks:framed_tile)

### ISSUE THREAD

**Issue by Gbergz** [XFactHD/FramedBlocks#509]
### Minecraft version

1.21.1

### (Neo)Forge version

21.1.61

### FramedBlocks version

10.1.4

### Describe the bug

Placing a Framed Fence crashes the game. (Invalid block entity framedblocks:framed_tile)

### How to reproduce the bug

Place a Framed Fence
Crash.

### Expected behavior

Placing a Framed Fence doesn't crash the game.

### Additional details

I am running my own modpack: [Modpack link](https://legacy.curseforge.com/minecraft/modpacks/tnp-limitless-8).

I am also suspecting this is an issue with Diagonal Fences. Reporting here first though to make sure, couldn't hurt.

Snippet of latest.log: https://gist.githubusercontent.com/Gbergz/6824cdbaf9bb9bc226ba7f5f36d036e3/raw/4f8d76cd9cdcd45f2d22f03c0bedc6569c7d7e8e/gistfile1.txt

### Crash log

https://gist.githubusercontent.com/Gbergz/d197bdb17d09ae4cf532621d85a6617a/raw/9475f39ab740f1ec9f9bfbe5b270f6cba4b1a593/gistfile1.txt

**Comment by XFactHD** [comment]
You are correct that Diagonal Fences is involved in the crash, it's entirely my fault though. I'll try to get a fix out within the next couple of days, the timing of this is very unfortunate because I'm currently in the middle of some feature development.

**Comment by XFactHD** [comment]
A new version with the fix for this was approved on CF a couple minutes ago

**Comment by Gbergz** [comment]
Thanks! 😄
