### ISSUE TITLE
[Bug]: Framed slope slab cannot be placed upside down unlike its normal, elevated, and panel variant

### ISSUE THREAD

**Issue by Flakxo** [XFactHD/FramedBlocks#510]
### Minecraft version

1.21

### (Neo)Forge version

21.1.61

### FramedBlocks version

10.1.4

### Describe the bug

![image](https://github.com/user-attachments/assets/346f1468-beba-4f43-8577-3bb4fd733791)

Hi, not sure if this is should actually be an issue opened as an enhancement and more of a suggestion, or if it should be opened as a bug, im very sorry if it should be the former.

As seen in the picture(sorry if its difficult to understand based on the image), the framed slope slab cannot be placed upside-down, or in other words, in an orientation where the flat side of the framed block is in contact with the block above it. As also seen in the picture, the elevated sloped slab, regular slope, and regular slab can all be placed in an upside down orientation, as can all of the slope panel variants, so this does not seem like intended behavior to me.

### How to reproduce the bug

try to place a slope slab in a way where the flat(bottom) side would touch the block above it

### Expected behavior

the slope slab would be in line with the elevated slope slab shown in the picture, with the sloped slabs "sloped" part gradually going into the block above it

![image](https://github.com/user-attachments/assets/e34f0eb6-f355-4538-9407-fa8e08886f7f)

### Additional details

Using a framed wrench also does not make the sloped slab display the expected orientation

**Comment by XFactHD** [comment]
The placement behaviour of the Framed Slope Slab and its corner variants is unfortunately a bit confusing at the moment: to place them upside down you need to sneak while placing them. I would like to make this less annoying but I haven't found a solution yet that isn't painful in a different way.

**Comment by squigglezworth** [comment]
Ahhh... took me a long time to find this while searching for this shape... Looking forward to having these little things documented at some point 😅 

Is there a reason wrenches can't be used to allow this rotation?

**Comment by XFactHD** [comment]
> Is there a reason wrenches can't be used to allow this rotation?

There is no good way to let them do that. Right-clicking the sides of the block (except the slope) already toggles whether the block is in the top or bottom half, so it can't be handled that way, abusing the inverted rotation behaviour of sneak-right-clicking is confusing in my opinion, and using another key combination sends people searching yet again just like the placement behaviour.

**Comment by squigglezworth** [comment]
That makes sense, although I think needing a tool to switch between top/bottom positions might be a bit redundant, since you can just place them there to begin with.

Is there a way (through a block property or something) to enable other mods' wrenches/tools that enable rotation to do so?

**Comment by XFactHD** [comment]
> needing a tool to switch between top/bottom positions might be a bit redundant, since you can just place them there to begin with

That could kinda be said about almost all of the orientation properties though. Sometimes it's just not possible to place it in the desired orientation.

> Is there a way (through a block property or something) to enable other mods' wrenches/tools that enable rotation to do so?

No, this has to be implemented in FramedBlocks itself as there is no way for another mod to know which properties are safe to cycle.
