### ISSUE TITLE
[Feature]: Second type of threeway corners?

### ISSUE THREAD

**Issue by Tinyme3-1415926** [XFactHD/FramedBlocks#517]
### Describe the feature

![image](https://github.com/user-attachments/assets/1b5e0eb0-46cf-4658-8967-56e93d78eeb6)

On the left of the image is the three-way corner but it has a raised point in the middle, so I tried to fix it with collapsible framed blocks but it left the sheet at the bottom, can you please add a flat three-way corner framed block to 1.20.1

**Comment by XFactHD** [comment]
If you mean the shape shown in the following screenshot, then that already exists as the Framed Prism Corner:
![2024-10-19_17 38 01](https://github.com/user-attachments/assets/b47a4718-0633-44eb-b12f-2b039c16d1d0)

**Comment by XFactHD** [comment]
Due to lack of response I'm going to assume that the block suggested above matches what you were looking for.
