### ISSUE TITLE
[suggestion] framed glass pane/bars

### ISSUE THREAD

**Issue by Deragonis** [XFactHD/FramedBlocks#52]
same as a glass pane and iron bars, thats it, if you want to decrease the opacity of the block placed in it or not, either or, but a block with the iron bars hitbox would be very nice would be good

**Comment by XFactHD** [comment]
See https://github.com/XFactHD/FramedBlocks/issues/43, a block like iron bars is already planned. I also really like the idea of a full pane block. Feel free to add additional feedback concerning the pane and bar blocks in that issue.
