### ISSUE TITLE
[Feature]: Framed trapdoor accepts trapdoors as camo

### ISSUE THREAD

**Issue by AlisonHuang777** [XFactHD/FramedBlocks#520]
### Describe the feature

For example, iron trapdoor (not interactable with players) with wooden trapdoor's texture.

**Comment by XFactHD** [comment]
This is not possible, the entire system making this mod work is based on camos being full cubes.
However, I have plans to add visual variations to trapdoors in the future that replicate some of the vanilla trapdoor shapes.
