### ISSUE TITLE
[Feature]: Bushy slab/stair (plus verticals)

### ISSUE THREAD

**Issue by WorldsOfRosefire** [XFactHD/FramedBlocks#522]
### Describe the feature

A block that has additional textures for bushy leaves. on default it supports only leaves blocks. to match leave blocks (for those like us who use bushy leave texturepacks)
![bushyleavestairs](https://github.com/user-attachments/assets/89b6057c-4743-4b1d-b766-ced75c52b9c0)
made some models to see how it would turn out, free to use for everyone.
https://cdn.discordapp.com/attachments/1089167214495666206/1301278739648479243/bushyleaveslab.zip?ex=6723e5c4&is=67229444&hm=b0ca7498b9f7ae13e8cba3945f43be57d61ae29913d871e7fe044431f0fc2670&

**Comment by XFactHD** [comment]
I've thought about this for quite a while. Unfortunately it's not viable to do this, there are too many block variants this would apply to and it would also cause issues on double blocks.
