### ISSUE TITLE
[Feature]: Data/Resource Pack to add custom models

### ISSUE THREAD

**Issue by WorldsOfRosefire** [XFactHD/FramedBlocks#524]
### Describe the feature

you got a ton of requests maybe you could make just one feature to let us add new blocks, my idea would look like this, maybe connect to wents a bit far, maybe we need preset potation types to use easy. not sure if something like that would work. if, this option would not only solve enhancement requests it also keeps the content less heavy. maybe also a place to share our packs.
idea example:
path=myframed_blocks:slabs/
model=fenced_slab
individual_block_per_cube=true
connects_to=[{minecraft:fences},{minecraft:walls}]
connect_stage=
rotation=

**Comment by XFactHD** [comment]
This is unfortunately not possible. There is simply far too much additional logic involved in making a block than just the states determining its orientation and the model. Without this additional logic neighbor occlusion, connected textures and a lot of other things wouldn't work.
