### ISSUE TITLE
[Feature]: Being able to turn the framed slope slab upside down

### ISSUE THREAD

**Issue by Lovatic123** [XFactHD/FramedBlocks#525]
### Describe the feature

I would love to be able to turn the slope slab ubside down like a stair. I dont seem to be able to do that (see picture)
![2024-11-08_18 35 26](https://github.com/user-attachments/assets/cffde877-778f-4e89-ade4-90e7a209976a)

Im on 1.19.2 forge, if that is of any importance :)

**Comment by XFactHD** [comment]
The slope slab and its corner variants can be placed upside down by crouching while placing the block. I'm aware that this is hard to discover but I haven't found an alternative solution yet that isn't just another kind of complete pain to use.
