### ISSUE TITLE
[Bug]: Framed pane is full Block

### ISSUE THREAD

**Issue by f0kx** [XFactHD/FramedBlocks#527]
### Minecraft version

1.21

### (Neo)Forge version

43.3.5

### FramedBlocks version

6.8.6

### Describe the bug

Framed Block is ful Block
![image](https://github.com/user-attachments/assets/3cb2f330-9719-46ba-96aa-106a5b2191a0)

### How to reproduce the bug

Take a Framed Block and cut it into Framed Pane ->place it

### Expected behavior

Should be a pane instead its a block

**Comment by XFactHD** [comment]
Please provide a mod list and don't try to lie about the Minecraft version.
This is very likely caused by an interaction with another mod.

**Comment by f0kx** [comment]
There was an drop down menu and this was my only option to choose from … sry don’t know about the subtopic of lying users giving wrong version and the trauma behind it. Will do better next time and I promise it was nt intentional 🐑
It’s the farming crossing5modpack where this happens.
https://www.curseforge.com/minecraft/modpacks/farming-crossing-5-made-to-order

**Comment by XFactHD** [comment]
The information you provided is completely incoherent:
- The Forge version you provided is for 1.19
- The FramedBlocks version you provided is for 1.19
- The modpack you linked is for 1.21
- The 1.19 variant of that modpack uses neither the provided Forge version nor the provided FramedBlocks version

I need useful information to be able to help you, so please be specific: which MC version, (Neo)Forge version and FramedBlocks version are you using (1.19 also has an entry in the dropdown menu)?

**Comment by f0kx** [comment]
okay sry again

NEOFORGE: 21.1.80
FRAMEBLOCKS: 10.2.1
[Farming Crossing NEW.zip](https://github.com/user-attachments/files/17962240/Farming.Crossing.NEW.zip)

This is my Exported Files of the Pack i use....its an updated version of farming crossing 5 to 1.21.1

But i tested it also on the original pack and there is also the mistake ---> picture is from pack directly
![image](https://github.com/user-attachments/assets/624b2967-ed87-45bd-a024-952202350a1a)

**Comment by XFactHD** [comment]
Thank you. I've narrowed it down to an issue with DiagonalWindows, I'm not sure yet whether the issue is on my end or on DiagonalWindows' end.

**Comment by f0kx** [comment]
[Diagonal Mods Config 1.21.1.zip](https://github.com/user-attachments/files/17990245/Diagonal.Mods.Config.1.21.1.zip)

i found a solutionen so handle this with an datapack

https://github.com/user-attachments/assets/5c48faf9-5064-4a14-8234-798a15231653

**Comment by f0kx** [comment]
it was the diagonal mod and when you activate this datapack into the world it will work again

**Comment by XFactHD** [comment]
That's only a workaround unfortunately. FramedBlocks has dedicated integration for DiagonalFences and DiagonalWindows, specifically to make this work properly.
