### ISSUE TITLE
[Bug]: Framed light sources do not emit light after re-enter the world

### ISSUE THREAD

**Issue by Fr44228571** [XFactHD/FramedBlocks#528]
### Minecraft version

1.20

### (Neo)Forge version

47.3.11

### FramedBlocks version

9.3.1

### Describe the bug

**Framed light sources do not emit light after re-enter the world**
When I use a light source block (for example: any kind of froglight) to interact with a frame block (for example: framedblock:framed_slab), the framed light source block emits light. The bug occurs when I save the world and exit, and then enter this world: the framed light source does not emit light, meanwhile the texture has on problem.

### How to reproduce the bug

Use a light source block to interact with a frame block, the block emits light; save the world and exit and then enter this world, that block does not emit light.

### Expected behavior

The framed light source block will always emit light after I re-enter the world again.

### Additional details

When I place a light source block adjacent to the framed light block which does not emit light, and then I break the light source block, causing block refresh involving light, then framed light block will emit light then.

**Comment by XFactHD** [comment]
If you are using Starlight, please try removing it. Due to significant changes in the vanilla light engine, Starlight provides little benefit in 1.20.1 and later and it breaks highly dynamic light sources due to unfortunate circumstances which are only partially to blame in Starlight.

**Comment by XFactHD** [comment]
Due to the lack of response I'm going to assume that the suggestion above resolved your issue.

**Comment by Fr44228571** [comment]
I shall apologise for that I failed to log in github for the past months. Removing Starlight does work, but I find incompatibility with shaders which changes the light engine (probably the same season as why Starlight is not compatible with this mod). Possible solution for this issue is add the id of these framedblocks in _block.200_ term in the _block.properties_ in the shader file.

**Comment by XFactHD** [comment]
Compatibility with shaders is a completely different issue and has nothing to do with the light engine. Adding framed blocks to the block.properties file is likely to cause other visual issues and is therefor not advisable. Shader compatibility is a far more broad issue and there is currently no way to fix this from my side, see #358 for a bit more detail and to keep track of any potential future work.

**Comment by Fr44228571** [comment]
Well, thanks
