### ISSUE TITLE
[Bug]: ghostly world infinite corruption 

### ISSUE THREAD

**Issue by Arch23-tech** [XFactHD/FramedBlocks#529]
### Minecraft version

1.20

### (Neo)Forge version

47.3.5

### FramedBlocks version

9.3.0

### Describe the bug

When the mod exists in modlist and being launched within game it does not have any side effects on worlds or gameplay .....

But when it comes to crafting the frame blocks in survival mode and placing them on builds and applying the materials, after relaunching the game after a short period of time, when opening the world there is no chunk rendering and loading also with no ground surface, a ghost empty world and the weirdest of all the character seems falling down in the void Infinitely.

### How to reproduce the bug

.....

### Expected behavior

.....

### Additional details

Using MC 1.20.1 
Forge 47.3.5
Embeduim

**Comment by XFactHD** [comment]
Are FramedBlocks and Embeddium the only mods you're using? If not, please provide a full mod list. Please also provide a log file after reproducing the issue as it may contain errors that would explain this behaviour.

**Comment by Arch23-tech** [comment]
im using modernfix alongside them....

i cannot provide any logs, because the game does not crash in order to produce error logs that world itself just corrupts

**Comment by XFactHD** [comment]
The game always creates a log, regardless of whether it crashes or not. Please provide the `lastest.log` (may just be called `latest` if you're using Windows on default settings) from the `logs` folder (can be found next to the `crash-reports` folder).
