### ISSUE TITLE
Can't dye signs anymore

### ISSUE THREAD

**Issue by omocho1** [XFactHD/FramedBlocks#53]
I'm not sure what update I was using previously (2.9.1 1.16.5 would be my best guess), but I could dye Framed Signs and it was awesome mixing concrete textures with dye colours.

When I updated to the latest version (2.9.3) I was no longer able to dye sign text. I've tested on the server I run as well as in singleplayer so i'm pretty certain it's the mod not the server. Can't dye the text before or after a block is placed onto the sign. My spawn signs remained dyed.

**Comment by XFactHD** [comment]
Fixed.

2.9.2 broke it because of a small change when I implemented the chest.
