### ISSUE TITLE
[Bug]: Breaking a framed block does not drop glowstone dust

### ISSUE THREAD

**Issue by desagas** [XFactHD/FramedBlocks#530]
### Minecraft version

1.20

### (Neo)Forge version

47.3.7

### FramedBlocks version

9.3.1

### Describe the bug

Blocks lit with glow stone do not drop glowstone dust when mined or broken. They only drop the frame and the block it was mimicking. 

### How to reproduce the bug

Make a framed block light up with glow stone, and break it.

### Expected behavior

When a block lit with glowstone is broken, the glowstone should drop along side of it, AND OR, using glowstone to light up blocks should be not use up glowstone.

### Additional details

Playing Monifactory 0.10.4.

**Comment by XFactHD** [comment]
The glowstone dust not being dropped is intentional behaviour.

**Comment by desagas** [comment]
I guess it’s your mod so it’s your rules. I’m curious if the logic behind it. Pretty silly one, but I concede. lol.

**Comment by XFactHD** [comment]
It's primarily a nod to the roots of this project: breaking an illuminated block in the original Carpenter's Blocks did not drop the glowstone dust either.
If you want to put lore onto it, then having spread the dust so thin you can't collect it again is probably the best explanation :D
