### ISSUE TITLE
[Question]: Framed Key

### ISSUE THREAD

**Issue by skinnypete07** [XFactHD/FramedBlocks#533]
### Question

I see what it is used for but cant figure out how to use it to save my life. right click, shift right click, left click, crafting.... etc. no idea how to actually use it.

**Comment by XFactHD** [comment]
The Framed Key allows you to lock certain blocks with variable shapes (i.e. walls, fences, stairs) in a particular shape to prevent them from changing shape when you break an adjacent block that forced the block into the desired shape.
To use it, you place the block which you want to lock into a certain shape, place neighboring blocks to force it into the desired shape, right-click the block with the Framed Key and then break the neighboring blocks again.

**Comment by XFactHD** [comment]
I'm going to assume my earlier response answered your question.
