### ISSUE TITLE
[Bug]: Unable to connect framed panels to framed vertically divided panels

### ISSUE THREAD

**Issue by michelle1574** [XFactHD/FramedBlocks#538]
### Minecraft version

1.19 - UNSUPPORTED

### (Neo)Forge version

43.4.5

### FramedBlocks version

6.8.6

### Describe the bug

You're unable to connect framed panels/framed vertically divided panels to vertically divided panels
![image](https://github.com/user-attachments/assets/34f9d7d9-9321-44e6-aeda-f183e6b010ea)

### How to reproduce the bug

Place a construction like on the picture, place a panel

### Expected behavior

The panel would connect to the framed panel that is filled

**Comment by XFactHD** [comment]
It's not entirely clear to me what the expected result is. Is this shape what you are expecting to happen:
![2024-12-14_00 26 26](https://github.com/user-attachments/assets/06451acb-f153-4fe9-a58d-243411ec0cfb)

**Comment by michelle1574** [comment]
Yup. It would be great if there would be a whole block with this part like this
Sent from my iPhone

On 14 Dec 2024, at 00:28, Dennis C ***@***.***> wrote:

﻿

It's not entirely clear to me what the expected result is. Is this shape what you are expecting to happen:
2024-12-14_00.26.26.png (view on web)<https://github.com/user-attachments/assets/06451acb-f153-4fe9-a58d-243411ec0cfb>

**Comment by XFactHD** [comment]
Thank you clarifying. This block already exists in 1.20.1 and later as the Framed Vertical Sliced Stairs. 1.19 however is out of support and will not receive any further updates.
