### ISSUE TITLE
[Feature]: Pressure plate functionality to regular framed blocks.

### ISSUE THREAD

**Issue by Sivok80** [XFactHD/FramedBlocks#540]
### Describe the feature

Would it be possible to right click a framed block with a pressure plate to add the functionality of the plate?     For instance if you add one to a framed stair,  when you step on the stair it would function as a pressure plate.

**Comment by XFactHD** [comment]
The way pressure plates work is more involved than it might seem and replicating that behavior onto other blocks is unfortuntely not viable.
