### ISSUE TITLE
[NeoForge 1.21.1] `LevelRenderer` being unconditionally exported by Mixin

### ISSUE THREAD

**Issue by EnderTurret** [XFactHD/FramedBlocks#542]
### Question

**NeoForge version**: 21.1.90
**Framed Blocks version**: 10.2.1

Hello. I noticed in my private modpack that for some reason `LevelRenderer` is being exported (in `.mixin.out/class`) even without `-Dmixin.debug.export=true`. I traced it back to this mod, specifically [`MixinLevelRenderer`](https://github.com/XFactHD/FramedBlocks/blob/1.21/src/main/java/xfacthd/framedblocks/mixin/client/MixinLevelRenderer.java#L15) having `@Debug(export = true)`. Could that annotation be removed so that mixin stops dumping `LevelRenderer`?

**Comment by XFactHD** [comment]
Yeah, I somehow missed that when I initially added the mixin. Will be removed in the next update.
