### ISSUE TITLE
[Feature]: Texture offset for Framed Corner Pillar

### ISSUE THREAD

**Issue by MegaCornflakes** [XFactHD/FramedBlocks#543]
### Describe the feature

In the image below, I have 3 corner pillars placed to create the effect of a log offset by a half block. Is it possible to make the textures of the pillars adjustable so that they match up across blocks, instead of looking like 3 separate log corners?
![image](https://github.com/user-attachments/assets/f446b32d-8f23-43f7-95b3-d44e88f5fd29)

**Comment by XFactHD** [comment]
This is unfortunately not viable, there are far too many cases where this could apply and it would very likely cause severe issues with connected textures support.
At the moment, the only way to make this look better is to use the Framed Collapsible Copycat Block which would allow you to make these three pillars look like full logs with a smaller diameter.
