### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Azigard** [XFactHD/FramedBlocks#55]
I translated with google translator, so I apologize in advance.

Hi. There was a problem on version 1.16.5. Mobs do not perceive vertical slabs as a block. I started building a village with many houses and most of the inhabitants just poke at the walls at nightfall. Golems also can't see and most likely other mobs too. I think they do not see other blocks either.

![Screenshot_1](https://user-images.githubusercontent.com/91206873/134369319-e24d7d07-59c2-46f2-aa59-c43fad1689de.png)

**Comment by XFactHD** [comment]
Can you reproduce this issue with only FramedBlocks?
Also, what version of Forge and FramedBlocks are you using?

**Comment by Azigard** [comment]
Wow, sorry, I didn't expect a quick response.
![image](https://user-images.githubusercontent.com/91206873/134478391-fa3b072e-37ba-4097-af6b-49ca694a4c4e.png)
![image](https://user-images.githubusercontent.com/91206873/134478413-9a3ee7de-15e6-4531-aced-60ee6c13e88a.png)
![image](https://user-images.githubusercontent.com/91206873/134478827-54a3ae81-5815-4eae-b878-c5a130c8c0cf.png)
I also noticed that if a resident is separated from the bed by a wall of vertical slabs, he can lie on it through this wall.

Version of Forge and FramedBlocks: FramedBlocks-2.10.0, Forge-1.16.5-36.1.61

**Comment by Azigard** [comment]
I also noticed that if a resident is separated from the bed by a wall of vertical slabs, he can lie on it through this wall.
*if the bed is close to the wall like here:
![image](https://user-images.githubusercontent.com/91206873/134479831-82f97c73-0930-4b0c-adf2-c85ac9215bfd.png)

**Comment by XFactHD** [comment]
Thanks for details, I will look into it. This might take some time to get fixed.

**Comment by XFactHD** [comment]
The fix was simpler than I expected.
A new version will be released in a few days.

**Comment by XFactHD** [comment]
New version with the fix has been approved on CurseForge
