### ISSUE TITLE
Plants tinted only if flower pot is tinted

### ISSUE THREAD

**Issue by WenXin20** [XFactHD/FramedBlocks#56]
`Minecraft v1.16.5`
`Forge v36.2.4`
`Framed Blocks v2.11.0`

I've noticed that plants are not tinted unless the flower pot itself uses a block with tint. I also have [Halogen](https://www.curseforge.com/minecraft/mc-mods/halogen) (previously called Sodium Reforged) installed if this isn't reproduceable on its own.

![2021-10-08_12 35 59](https://user-images.githubusercontent.com/12000593/136600073-30e9fff4-bda9-4036-92b3-7b1017ae5755.png)

**Comment by XFactHD** [comment]
Can you reproduce this without Halogen?

**Comment by XFactHD** [comment]
Scratch that, was a minor oversight in the model and color handler
