### ISSUE TITLE
Dynamic tree seeds can't be placed in pots

### ISSUE THREAD

**Issue by WenXin20** [XFactHD/FramedBlocks#57]
`Minecraft v1.16.5`
`Forge v36.2.4`
`Framed Blocks v2.11.0`
[`Dynamic Trees v0.10.0-beta25`](https://www.curseforge.com/minecraft/mc-mods/dynamictrees)

Is compat with Dynamic Trees possible? Currently seeds from dynamic trees cannot be placed in framed flower pots. The mod has some sort of system where if a new sapling is added using a tree pack (similar to datapacks), it auto generates a flower pot model for it.

**Comment by XFactHD** [comment]
That is unfortunately not possible because they are using a completely custom flower pot block. There is as far as I can see no way for either mod to fix this. I am using the vanilla flower pot to get the data and their custom flower pot completely circumvents that to make the tree packs work.

**Comment by WenXin20** [comment]
Ah, I see, thanks for looking into it.
