### ISSUE TITLE
Crafting Menu Crash

### ISSUE THREAD

**Issue by Rakiden** [XFactHD/FramedBlocks#59]
Hi! Sometimes while going through the crafting menus it crash. I said sometimes becouse it always happend in there but i cant simulate it. Sometimes crash while the cursor is on the search, other times while clicking framed blocks. 

Maincraft 1.17.1
I only have this mod plus 
-Forge 37.0.97, last one
-OptiFine HD U H1 pre6
-OptiForge 0.1.1

And i let you the crash error message
![1](https://user-images.githubusercontent.com/38255909/138109653-eebc7e40-8e3f-428e-9f3d-39eb6b070159.PNG)

Actually i can play calmly and even use the mod, but i go very carefully through the crafting menus XD because i dont really know what trigger the crash.
Thanks!

**Comment by XFactHD** [comment]
That doesn't tell me anything useful. Please include the version of FramedBlocks as well as the actual crash report.
Also, please try reproducing this without OptiFine and OptiForge as they are known to cause all kinds of random issues.

**Comment by Rakiden** [comment]
Sorry for the lack of information. The mod version is 3.1.0
Without Optifine and OptiForge the crash remains whit the same error. Here is the report.
[crash-2021-10-20_18.20.44-client.txt](https://github.com/XFactHD/FramedBlocks/files/7382843/crash-2021-10-20_18.20.44-client.txt)

**Comment by Rakiden** [comment]
Hey man, so sorry, I was thinking it was about the mod and its happend even without the mod, and with any recipe i look :,( it should be forge or idk. So sorry for waste your time.

**Comment by XFactHD** [comment]
This issue is fixed in Forge 37.0.97 but the crash-report says you are running Forge 37.0.95, you should update to .97.

**Comment by Rakiden** [comment]
Yeah, i made it and everything is ok now, thanks!
