### ISSUE TITLE
Weird rendering issues on south-facing blocks

### ISSUE THREAD

**Issue by HipHopHuman** [XFactHD/FramedBlocks#6]
MC: 1.16.5
Forge version: 36.0.46
FramedBlocks version: 2.3
Do I have Optifine: No, and no other mods that change rendering in any way

Blocks that are facing South have inconsistent rendering with the other blocks.

Here are 4 slopes - the same issue happens even when blocks are added to texture them.
![image](https://user-images.githubusercontent.com/70091260/110259813-4eed1a80-7fb2-11eb-8681-71a76d079aee.png)

Here are a handful of blocks, all facing South:
![image](https://user-images.githubusercontent.com/70091260/110259910-adb29400-7fb2-11eb-9c2b-6f3b2f40aaf1.png)

**Comment by XFactHD** [comment]
Do you have FerriteCore installed?
If you do, please disable the `bakedQuadDeduplication` option in the ferritecore-mixin.toml config file.

**Comment by HipHopHuman** [comment]
😅 I had installed FerriteCore between opening my last issue and this one and forgot that I did. That fixed it. Sorry for the inconvenience (and the late response, been a bit busy)

**Comment by XFactHD** [comment]
No problem, thanks for comfirming
