### ISSUE TITLE
Framed Chest Duplication Bug

### ISSUE THREAD

**Issue by Darkosto** [XFactHD/FramedBlocks#61]
Hello!

Using the Framed Chest allows any item inserted to be duplicated at a rapid pace:

1. Place framed chest
2. Insert items
3. Close Chest GUI
4. Items will shoot out while the original items inside the chest remain

https://clips.twitch.tv/MushyInventiveConsoleYouWHY-6DBnM29prEO3f7Fx

MC: 1.16.5
Forge 36.2.8
Framed Blocks: 2.11.1

**Comment by XFactHD** [comment]
Fixed version is approved on CurseForge.
