### ISSUE TITLE
[Feature] "microblock" / mob-head-sized block

### ISSUE THREAD

**Issue by Syndaryl** [XFactHD/FramedBlocks#62]
An 8x8x8 pixel microblock that is centered on the face it is applied to (rather than corner aligned like the framed slab corner) would be useful for refined decoration. There are whole databases of player-heads with "microblock" textures representing miniature blocks for detailing; obviously *miniature* blocks aren't in scope for this mod, but being able to add small "lumps" of cobblestone, branch stumps, making leaves more lumpy-textured etc would be very useful for decor. I'm using buttons for this at the moment, but a second, larger, and cubic block would be really great.

**Comment by Syndaryl** [comment]
A full size center aligned 8x8x16 post that doesn't sprout attatchments (unlike a wall) would also be helpful for branches, and while I'm wishing a 4x4x16 "twiglet" or "stake" wouldn't hurt either.

A related concept is a horizontal framed-lattice, which could be used to make forking branches.

**Comment by XFactHD** [comment]
To summarize your ideas:
- Framed Pillar (like the Framed Wall but no connections and can be placed in all three axis)
- Framed Post (same as above but like the Framed Fence)
- Framed Half Pillar (half height of the Framed Pillar and can be placed on all six faces)

Is my understanding correct?
All of those are easily doable and very straightforward.

**Comment by Syndaryl** [comment]
Yes, that's exactly! Thank you for your attention :)
