### ISSUE TITLE
Question about fabric.

### ISSUE THREAD

**Issue by Waterpicker** [XFactHD/FramedBlocks#64]
I have read your response in this issue here. https://github.com/XFactHD/FramedBlocks/issues/10#issuecomment-812558467

What is your stance on people porting the mod themselves?

**Comment by XFactHD** [comment]
I can't stop you from doing it due to the license. Therefore if you want to do it, go for it.
The only thing I would request is that you rebrand the Fabric version to make it obvious to the user that these are different mods developed by different people.

**Comment by Waterpicker** [comment]
Your current mod name provides a perfect one. FabricatedBlocks
