### ISSUE TITLE
Framed Blueprints

### ISSUE THREAD

**Issue by ChyanneM** [XFactHD/FramedBlocks#65]
How do you use Framed blueprints? I can't find anything about it.

**Comment by XFactHD** [comment]
To copy a Framed Block, you sneak and right-click the block.
To place the copied block, right click without sneaking and make sure you have all necessary materials in your inventory if you are not in creative mode.
To clear the blueprint, you sneak and right click in the air.

I will add some details about the blueprint to the CF page.
