### ISSUE TITLE
Framed chest not working

### ISSUE THREAD

**Issue by therealfak** [XFactHD/FramedBlocks#68]
Can you fix the issue cause when I open a framed chest, my game crashes.

**Comment by XFactHD** [comment]
Please put the crashreport on gist.github.com or pastebin.com and post the link here. Without that info I can't fix anything.

**Comment by XFactHD** [comment]
Closing due to lack of feedback.
If you decide to provide the necessary information at a later time, feel free to comment on this issue and I will reopen it if needed.
