### ISSUE TITLE
framed double chests?

### ISSUE THREAD

**Issue by esotericist** [XFactHD/FramedBlocks#72]
i love being able to use arbitrary materials for chests, but the tradeoff with being unable to use double-size chests is a slight hamper for my storage habits. how implausible would it be to add support double chests?

or do i just need to relearn how to store things? :grin:

**Comment by XFactHD** [comment]
The code that manages the double chest behavior is a huge maze and really awkward to work with.
I will look into it again in the next few days but it's unlikely this will be added.

**Comment by esotericist** [comment]
that's fair enough. i know chest support has been pretty rocky over the years because of that, but i didn't see a previous request, figured, no harm in asking, right? :grin:

**Comment by XFactHD** [comment]
This is unfortunately not going to happen. The existing system used for connecting vanilla chests is completely unsuitable for custom chests using the Forge capability system for the inventory and I really don't want to write a completely custom system for this and risk introducing item duplication and/or deletion bugs.
