### ISSUE TITLE
Suggestion: half-width stairs

### ISSUE THREAD

**Issue by lolkje** [XFactHD/FramedBlocks#74]
This mod is really nifty! It opens up so many possibilities for building.

I have a project where half-width stairs are the perfect shape. Take normal stairs, and just slice them in half. Both right side up and upside down. It's like a corner pillar and a corner slab occupying the same space.

Would this be possible in a future enhancement?

**Comment by XFactHD** [comment]
Seems like a sensible addition. Will be added for the next version.

**Comment by lolkje** [comment]
Brilliant. Thank you!
