### ISSUE TITLE
Crash on SP world generating/entering.

### ISSUE THREAD

**Issue by Fundryi** [XFactHD/FramedBlocks#76]
Hi,

Game crashes once I create a world with the new 4.1.0 version and Forge 39.0.45
Once I remove the mod, it works just fine.

Crash report Links:
https://crashy.net/fE6l7INPTtGutzTpXGxO

https://bytebin.lucko.me/B0GOSzLaZy

Regards

**Comment by XFactHD** [comment]
This has nothing to do with FramedBlocks. The crash is happening in a Mixin from the Bigger Stacks mod, please report this crash to them.
