### ISSUE TITLE
Inventory Block Feature Request

### ISSUE THREAD

**Issue by Graywaren** [XFactHD/FramedBlocks#77]
I just found this mod and started trying it out and I'm delighted! It makes my decoration driven play a joy. I'm looking forward to all the things I can build with it. I did have one, well two sorta, feature requests. I would love if it were possible to hide the latch on the chest with the wrench and to add a framed barrel. Sometimes the latch clashes with the texture I add and I'd really like a full block with an inventory that just looks like the framed cube, so for example I can put it under a botany pot and look like a table or put it in a wall as a secret safe type thing.
Thanks so much for such a cool mod!

**Comment by XFactHD** [comment]
Hiding the chest latch wouldn't be enough to transform the Framed Chest into an inconspicuous storage block. I think a separate block that just looks like the Framed Cube would be better for this purpose.

I don't see the point in a Framed Barrel in addition to the hidden storage as it would just look like a Framed Cube as well, but maybe I am missunderstanding you. What would you intend this to look like?

**Comment by Graywaren** [comment]
Hi!
Okay, hopefully this is more clear. It would be great to have:
- The separate full block inventory that looks just like a framed cube and could be hidden in a wall/accessed when other solid blocks are on top of it, like a barrel.

Then separately, it would also be nice to have:
- The ability to customize the latch on the chest block. Ideas for that would be; hiding it, adding a second block as the latch texture, rotating through the vanilla metal & gem textures (iron, gold, diamond, etc.) via the wrench. (This might also be neat for adding a doorknob to the door)

Hopefully that makes sense, sorry for the confusion! Thanks for considering!

**Comment by XFactHD** [comment]
This makes a lot more sense, thanks for clarifying.

The secret storage is a fairly simple addition.

Hiding the chest latch is also fairly simple to do.
Customising the chest latch is a neat idea but considerably more complicated, I'll think about how to implement that. Same goes for the door knob.

**Comment by XFactHD** [comment]
- Added the Framed Secret Storage block which looks identical to the Framed Cube when a camo is applied.
- Made it possible to switch the chest latch between three modes (decided against finer customization for simplicity):
    - Default -> The normal chest latch
    - Camo -> The chest latch is generated from the camo texture
    - None -> The chest latch is completely hidden
- Decided against the door knob for now, might revisit this in the future

**Comment by Graywaren** [comment]
Awesome!!! I look forward to using it on my server when it's available on curseforge. Thanks so much!
