### ISSUE TITLE
Feature Suggestion: Extra Block Functionality

### ISSUE THREAD

**Issue by Idefkftt** [XFactHD/FramedBlocks#78]
This will include a few things so:

1. Could we get the option to use redstone dust on blocks to make them act as conduits, allowing us to run full redstone wires without needing an extra block width to hide
2. Using slimeballs on blocks to make them bouncy
3. I'm not sure what item would best reflect this, but something to remove block collision so that they're only visually present and requires sneak clicking with the wrench to remove allowing for secret doors/passageways/traps

Either way mod is amazingly helpful, thank you for your hard work!

**Comment by XFactHD** [comment]
1. Not sure... Redstone is a confusing mess and really easy to trip over, so no guarantees on that
2. That's easily doable though I have two concerns about this:
    1. I don't know how well this would work with blocks you can step up on (stairs, slopes, slabs, etc.)
    2. I don't see a point in this for any block that does not fill the full block face, therefore I would rather make this a separate block (basically the Framed Cube but bouncy)
3. This is also easily doable, though as you said: not sure what item to use for this (maybe Amethyst?). I'll think about it. If you have another idea for an item, please tell me.

**Comment by Idefkftt** [comment]
Can't say I have any knowledge on the functions behind redstone, so no worries if it's a mess to do. I agree on the bouncy block topic.  And for the intangible blocks maybe phantom membranes?

**Comment by XFactHD** [comment]
I agree that Phantom Membranes would fit perfectly but they are really hard to get and I think a lot of people (including me) disable them completely because the phantoms are annoying as hell.
A config option or a datapack tag to allow customization could be an option though.

**Comment by Idefkftt** [comment]
Whatever you decide works best I'm sure it will be great.  I'm just happy you were willing to hear out my suggestions :)

**Comment by XFactHD** [comment]
1. Decided against adding redstone functionality for two reasons:
    1. Redstone is a mess as mentioned before
    2. I would like these blocks to be marked somehow but that would conflict with the intention of completely hiding the redstone
2. Added the Framed Bouncy Cube.
3. Added the feature to allow making certain blocks passable by clicking them with a configurable item. The default item for this is the Phantom Membrane. Setting the item to the Barrier item effectively disables this feature. This feature is disabled on the following blocks:
    - Wall
    - Fence
    - Gate
    - Door
    - Trapdoor
    - Pressure Plate
    - Button
    - Lever
    - Sign and Wall Sign
    - All Torches
    - Rail Slope
    - Flower Pot
    - Bouncy Cube

**Comment by XFactHD** [comment]
Decided to gate the intangibility feature behind a server config setting which defaults to false due to possible concerns with balance and glitch issues.
