### ISSUE TITLE
Framed Chest Lid Crash

### ISSUE THREAD

**Issue by WenXin20** [XFactHD/FramedBlocks#79]
```
Minecraft v1.18.1
Forge v39.0.59
Framed Blocks v4.1.0
```

The game crashed while opening the Framed Chest. The framed chest was using a grass block.
[Crash Report](https://gist.github.com/WenXin20/f80e992c94eb002140fee0f4291e12e8)

**Comment by XFactHD** [comment]
Can you reproduce this without OptiFine?

**Comment by WenXin20** [comment]
Looks like it does not crash without optifine.

**Comment by XFactHD** [comment]
As I expected. OptiFine replaces a method I am using with their own crap which breaks the chest renderer. Unfortunately there is absolutely nothing I can do about this.
The only workaround I can think of is to have the chest not open up when OptiFine is installed.

You could try reporting this to OptiFine to convince them to not overwrite one of the most useful block rendering methods but I don't have high hopes for that.

**Comment by WenXin20** [comment]
Yeah, probably won't work. I reported an issue with modded liquids getting a blue tint over 2 years ago but still no reply (https://github.com/sp614x/optifine/issues/3226). I wouldn't mind the lid not opening if it prevents a crash.

**Comment by XFactHD** [comment]
I'll get a new build out towards the end of next week when the other open issue is done as well.

**Comment by WenXin20** [comment]
Sounds good, thanks
