### ISSUE TITLE
Mixin Crash with Rubidium

### ISSUE THREAD

**Issue by WenXin20** [XFactHD/FramedBlocks#80]
`Minecraft v1.18.1`
`Forge v39.0.59`
`Framed Blocks v4.1.0`
[`Rubidium v0.4.0c`](https://www.curseforge.com/minecraft/mc-mods/rubidium)

I was testing if I could switch from Optifine to a sodium forge mod, Rubidium, but it crashes at launch with mixins.
[Crash Report](https://gist.github.com/WenXin20/1fba5de51ffebad4a45d6082b3d97a2f)

**Comment by XFactHD** [comment]
This should be fixed by https://github.com/XFactHD/FramedBlocks/commit/196c95f5d5d5636221892f405d57fe32deee2006, which will be included in the next version of FramedBlocks. I'll leave this open until the new release is out.

**Comment by WenXin20** [comment]
Nice, thanks :)

**Comment by Asek3** [comment]
> This should be fixed

Honestly, this is not a solution to the crash. Rubidium ports new Sodium branch and after class name
refactoring me.jellysquid.mods.sodium.common.config.Option became me.jellysquid.mods.sodium.config.mixin.MixinOption

**Comment by XFactHD** [comment]
Thanks for the heads up, I am going to take another look to make sure the class names are correct.

**Comment by XFactHD** [comment]
I've added the necessary check for Rubidium, thanks again for notifying me.
New version will come out tomorrow. While it works in dev, I would appreciate your feedback whether it works properly in the wild.

**Comment by XFactHD** [comment]
Quick heads up: The new version was released yesterday.

**Comment by WenXin20** [comment]
It's working for me :)

**Comment by XFactHD** [comment]
Perfect, thanks for the feedback
