### ISSUE TITLE
Incorrect render underwater

### ISSUE THREAD

**Issue by WenXin20** [XFactHD/FramedBlocks#82]
`Minecraft v1.18.1`
`Forge v39.0.59`
`Framed Blocks v4.2.0`

The framed block, collapsible block, double slope, double corner, double prism corner, double threeway corner, & secret storage all display the water overlay on their sides when placed underwater, giving away their location.

![2022-02-05_11 40 27](https://user-images.githubusercontent.com/12000593/152652580-2c2b9832-6cc4-4bc3-a36d-b358415d7a66.png)

**Comment by XFactHD** [comment]
Decided to fix this properly, which also has a few other benefits (such as proper light occlusion). I didn't like the lazy fix of making everything waterloggable :D

**Comment by WenXin20** [comment]
Oh no worries. 
I was wondering why you decided on waterlogging. :D
