### ISSUE TITLE
[Suggestion] 26.57° Slopes

### ISSUE THREAD

**Issue by isaaclepes** [XFactHD/FramedBlocks#83]
It would be amazing if there could be a slope that would work out to about a slab-size and could be placed in 'top' or 'bottom' position of a block as needed.  Mostly thinking of roofs here, but it would also make for nice streets and walkways.

Where I got the number from:
https://myrooff.com/wp-content/uploads/2015/08/Roof-Pitch-In-Degrees.jpg

Edit:  Also, double slopes of this angle.

**Comment by XFactHD** [comment]
I'll think about it. I am not opposed to the idea but I am always happy when I don't have to touch the triangle code for slopes :D.
This may be a better fit for the upcoming FramedArchitecture mod though as the suggestion is specifically geared towards roofs as an architectural component.

Also, the slope angle is wrong, to get to the height of a slab you need an angle of 22.5 degree.

What are you referring to with the double slopes? Something like the existing double slope or a prism shape for the top of a roof with an uneven width?

**Comment by isaaclepes** [comment]
Just like the double slopes, but half-height.. so a slab bisected into 2 triangles where a texture can be applied to each.

As for the angle, I also thought 22.5° because it's half of 45°, but with slopes you are not dividing the angle, you are dividing the rise over a given run.  That's why I used the roofing image to demonstrate, but really this applies to sloped hills, roads, sidewalks, etc.

So a 6 in 12 slope will rise 6 units for every 12 units of run length.  Since a slab is 1.5 feet, this would mean the angle that bisects a 1.5ft X 3ft rectangle.

Anyway, I do appreciate the consideration for adding this, whether it ends up in this mod or the other you mentioned.. it would really help with, well, anything that you would like a shallower slope on.


Edit: This might help explain what I am saying with the angles:  https://www.inchcalculator.com/rise-run-degrees-calculator/

Enter a rise of 0.5 and a run of 1 to see what the angle for a slab-sized slope would be.  You can also think about it like this:  If you wanted to go twice as high as a 45° slope, it wouldn't be 90° unless the run-length was made 0 (it would be 63.43°).  the formula is degrees = tan^-1(rise/run).

**Comment by isaaclepes** [comment]
You are amazing!  I wasn't expecting to see this anytime soon.  Thank you!

**Comment by XFactHD** [comment]
The release may still take a few days, I am still hunting a tricky bug (unrelated to this feature though).
