### ISSUE TITLE
Secret storage deletes contents when broken

### ISSUE THREAD

**Issue by Graywaren** [XFactHD/FramedBlocks#85]
I love the secret storage block, it's perfect, except for that it appears to delete all contents if you break it, rather than the expected behavior of dropping its contents like when you break a chest.  I'm using 1.16.5 with the latest version, playing in a Seaopolis modpack. Hopefully this isn't too difficult a fix!
Thanks!

**Comment by XFactHD** [comment]
Not a difficult fix, just a simple copy-paste mistake :D
I still have to fix another issue before I can release a new version though.
