### ISSUE TITLE
Unable to put more than 1 Framed Corner Pillar or Framed Slab Edge in a single block space

### ISSUE THREAD

**Issue by Periwinking** [XFactHD/FramedBlocks#86]
Hello,

It does not appear possible to put more than one of these (in the post title) frames in a single block space, even though you can fit two Framed Panels and two Framed Slabs per space. Technically wouldn't four of the Framed Corner Pillars be able to fit in a space, or two Framed Corner Pillars next to each other and Framed Panel? A similar placement of two Framed Slab Edges and one on top of the other, and a Framed Panel, or two Framed Slab Edges next to each other sharing a space with a Framed Slab

Is this not a feature that has been added, but you may add it in the future, or is there something I am doing wrong that allows these multiple pieces to fit together in the same block space?

Thanks for the wonderful mod!

**Comment by XFactHD** [comment]
Combining completely different types of blocks will never be a thing, this is not a multipart mod and implementing all possible combinations of blocks would lead to a combinatorial explosion.

The existing double blocks (double slab, double panel, double slope, different double corners) are a very deliberate decision and adding new double blocks will be done on a case-by-case basis. Slab edges, corner pillars and slab corners will not get double variants at this time.
Combining more than two blocks in one space (i.e. four slab edges, four corner pillars, eight slab corners) will not be a thing. The complexity of implementing double blocks as well as their performance impact (they essentially have double the performance impact of normal blocks) is already high enough and certain existing systems would need major changes to support blocks with more than two parts.
