### ISSUE TITLE
FramedBlocks (framedblocks) has failed to load correctly

### ISSUE THREAD

**Issue by MickeyMouseYT** [XFactHD/FramedBlocks#87]
### mod version : FramedBlocks-2.14.0

-------------------------------------------------------------------------------

### **__logs :__**
[latest.log](https://github.com/XFactHD/FramedBlocks/files/8188290/latest.log)

### **__crash report :__**
[crash-2022-03-04_20.20.44-fml.txt](https://github.com/XFactHD/FramedBlocks/files/8188294/crash-2022-03-04_20.20.44-fml.txt)

**Comment by XFactHD** [comment]
Hotfix incoming.

EDIT: New file has been approved on CurseForge.
