### ISSUE TITLE
Update makes blocks with solid camo unable to provide light

### ISSUE THREAD

**Issue by Graywaren** [XFactHD/FramedBlocks#89]
Hi! 
I just updated for the secret storage hot fix, and discovered, much to my dismay, that suddenly my base was full of spawns because the framed blocks were no longer providing light. I figured out that a framed block with glow stone applied, but given a solid block camo no longer provides lighting. It still works as expected if it has a transparent camo such as glass, but no longer works if it contains something like a log. I'm really hoping this is not intended (and that I managed to track down all the dark spots this left) since the ability to make fake lights with whatever texture was one of my favorite things about this mod!

**Comment by XFactHD** [comment]
This is not an intentional change. 
I know which change causes this but I have no idea why. I'll have to investigate when I have access to a computer again.
