### ISSUE TITLE
Tesselating block Model

### ISSUE THREAD

**Issue by Xaikii** [XFactHD/FramedBlocks#9]
https://pastebin.com/Aj0gA7sv

MC: 1.16.5
Forge: 36.0.42
Mod Version: 2.5

Edit:
OptiFine and FerriteCore are installed.
OptiFine: 1.16.5_HD_U_G7
FerriteCore: 2.0.3-forge

**Comment by XFactHD** [comment]
Can you reproduce this without OptiFine?

**Comment by Xaikii** [comment]
No, I cant reproduce this Issue without OptiFine.

**Comment by XFactHD** [comment]
Then this a classic case of "OptiFine is not supported". Nothing I can do about that.

**Comment by No3371** [comment]
That turned out to be a shader level issue, I had this bug with Sildurs, works fine with BSL.
Sildurs is really performant but it's indeed weird.
