### ISSUE TITLE
Framed Corner Slopes Render with broken shadows at some angles in Optifine

### ISSUE THREAD

**Issue by Swedz** [XFactHD/FramedBlocks#91]
Forge 36.2.31

Optifine 1.16.5 HD U G8

Framed Blocks 2.14.2

Framed Corner Slopes when placed in certain directions will render much darker than other blocks when running Optifine. Confirmed this only happens when Optifine is installed.

The variation I seem to be having the issue with is `horizontal_bottom_left`.

![2022-03-28_23 32 10](https://user-images.githubusercontent.com/6707125/160531871-c57d2159-b966-47b9-be64-1a5f7def2aa4.png)

**Comment by XFactHD** [comment]
There is unfortunately nothing I can do about that. OptiFine forces the `enableExperimentalLightPipeline` config setting to be disabled while presumably not providing a comparable replacement for the light pipeline that is able to light these blocks properly.
