### ISSUE TITLE
Crash when the Collabsible Block is picked by by the Carry On mod

### ISSUE THREAD

**Issue by KevinGliniecki** [XFactHD/FramedBlocks#92]
Crash when the Collabsible Block is picked by by the Carry On mod https://www.curseforge.com/minecraft/mc-mods/carry-on

**Comment by KevinGliniecki** [comment]
Nevermind, we will blacklist the mod from the list

**Comment by XFactHD** [comment]
Please provide the crash report via https://gist.github.com so I can look into fixing this.

**Comment by XFactHD** [comment]
Closing due to lack of feedback.
If you decide to provide the necessary information at a later time, feel free to comment on this issue and I will reopen it if needed.
