### ISSUE TITLE
1.16.5 mod server crash

### ISSUE THREAD

**Issue by MapleSugar365** [XFactHD/FramedBlocks#93]
Hello, I'm very optimistic about your mod, but my server will crash if I use it.

How to reproduce the problem:
Placing or mining any item in this module in the server will cause a crash.

Crash log:
https://paste.loliidc.cn/?face9b758ff3ab03#GYEykeVqejmmFVe7TY4yG8kWimkSRmsyWXvegSosRJJc

Additional information:
Minecraft version: 1.16.5
Forge version:
                      Server: forge-1.16.5-36.2.31
                      Client: forge-1.16.5-36.2.29
Mod version: framedblocks: 2.14.2
LoliServer version: 1.16.5-1e51f20

At present, the server test only found this problem.
I hope this problem will be solved.
thank!

**Comment by MapleSugar365** [comment]
Mod can work normally in single player games, but use [Carry on mod](https://www.curseforge.com/minecraft/mc-mods/carry-on) Lift and then put it down. The nature of the box remains unchanged, but the material will be lost and displayed as the original frame structure.

：d- But I don't think it matters.

**Comment by XFactHD** [comment]
Please put your crash report on https://gist.github.com, I can't access the link you posted.

**Comment by FinnT730** [comment]
This is an issue with using an Forge+Bukkit Hybrid
Try to use an Forge server by itself, and see if you can replicate the issue.
(Can't speak for XFactHD, but I could access the log, and I know mods are not quite made for Forge+Bukkit Hybrids)

**Comment by XFactHD** [comment]
As Finn mentioned, this is an issue with Bukkit breaking contract with the normal implementation of the Minecraft server. This is something that I can't support or fix without risking to break things for people using a normal Minecraft server installation with Forge.

As for the issue with Carry On, please open a separate issue for that, including the versions of both mods. At a glance this seems to be an issue with the way Carry On places carried blocks which erases part for the data.
