### ISSUE TITLE
1.16.5 Crash Bug With FTB_Quest

### ISSUE THREAD

**Issue by OcrSu** [XFactHD/FramedBlocks#94]
ModPack:https://www.curseforge.com/minecraft/modpacks/lcw/files/all
Version:3.5.2[1.16.5]
Please Use Java11 To Start Game.
CrashLog:https://paste.loliidc.cn/?b86670e0af98b78e#GGKEY3XPBWC9xgFZbd6pfkHG23xiSkwmj4qa7WiiPn35

**Comment by XFactHD** [comment]
Please try reproducing this without Krypton, Rubidium, Better FPS, NotEnoughCrashes and Obfuscate as well as with any combination of those removed to find out if one of those causes this.

**Comment by XFactHD** [comment]
Scratch that, found the issue. This crash is caused by Oculus. I'll publish a new version that should fix this in a few hours

**Comment by XFactHD** [comment]
New version has been approved on CurseForge.
