### ISSUE TITLE
Blocks don't glow.

### ISSUE THREAD

**Issue by ghost** [XFactHD/FramedBlocks#95]
I have changed the configuration file according to the method in the instructions, but the block still can't light up (but the torch in the mod can light up normally). How to solve it?

Game version: 1.16.5
Forge version: 36.2.31
Mod version: 2.14.3

**Comment by XFactHD** [comment]
Which specific block or blocks are you having problems with? Framed Blocks only light up after you right-clicked them with glowstone dust.

Please provide a full list, preferably through a debug crash (hold F3 + C until the game closes, then put the crash-report on https://gist.github.com).

**Comment by ghost** [comment]
It didn't light up after I right-clicked with glowstone dust. In fact none of the blocks except the torches light up.
I tried using F3+C and the log file is "minecraft-exported-crash-info-2022-04-07T21-46-12.zip".

[minecraft-exported-crash-info-2022-04-07T21-46-12.zip](https://github.com/XFactHD/FramedBlocks/files/8443715/minecraft-exported-crash-info-2022-04-07T21-46-12.zip)

I found another problem: After crashing with debug, when I start the game again, the game crashes when entering the world. I'm not sure if this has something to do with my debug crash. If you can, please let me know what the reason is. The log file after this crash is "minecraft-exported-crash-info-2022-04-07T21-55-20.zip".

[minecraft-exported-crash-info-2022-04-07T21-55-20.zip](https://github.com/XFactHD/FramedBlocks/files/8443726/minecraft-exported-crash-info-2022-04-07T21-55-20.zip)

**Comment by XFactHD** [comment]
Please try removing OptiFine as it causes a bunch of issues with FramedBlocks.
If that doesn't help with the crash when entering the world, then please set the `showGhostBlocks` setting in the framedblocks-client.toml config to false to see if that fixes it.

**Comment by ghost** [comment]
Problem solved, thanks for your help.
