### ISSUE TITLE
1.16.5 Mohist Server crash when placing a block on framed slope

### ISSUE THREAD

**Issue by JLSkyzer** [XFactHD/FramedBlocks#96]
Hello, when i place a block on a framed block, the server close

Crash report: [https://haste.mohistmc.com/ewuvefavir](https://haste.mohistmc.com/ewuvefavir)
The debug : [https://haste.mohistmc.com/emecasuges](https://haste.mohistmc.com/emecasuges)

**Comment by XFactHD** [comment]
There is unfortunately nothing I can do about this. Mohist/Bukkit handle TileEntity placement vastly different in comparison to vanilla MC and Forge.

If you switch to 1.18, then the system that is crashing here works completely differently, which avoids this issue.
If that's not an option for you, then the best you can do is to report this to them and tell them to fix their implementation to be on par with vanilla MC. I don't have high hopes though.
