### ISSUE TITLE
Crash when harvesting framed blocks 1.16.5

### ISSUE THREAD

**Issue by Gunner76th** [XFactHD/FramedBlocks#99]
Issue: When harvesting a framed block back up that has been placed in the world, the server crashes with the following crash report: 
[crash-2022-04-13_16.53.11-server.txt](https://github.com/XFactHD/FramedBlocks/files/8484914/crash-2022-04-13_16.53.11-server.txt)

The block in the case of this crash was the Framed Ladder and it did not have a texture block applied to it yet. 

The modpack this is happening in is Engineer's Life 2 for MC [1.16.5] https://www.curseforge.com/minecraft/modpacks/engineers-life-2

I have tested this in a vanilla server and single player game with only Framed Blocks present, as well as with Carry On present, and I am not able to repeat the crash. This tells me there is a mod compatibility issue within the modpack, however looking at the crash report the only thing I am seeing reported is Framed Blocks.

This is the log file from the server at the time of the crash. Perhaps you might be able to find the reason for the crash so that I can report back to Dreams and we can get the issue resolved. 
[2022-04-13-1.log](https://github.com/XFactHD/FramedBlocks/files/8485027/2022-04-13-1.log)

Any information you might be able to provide to help us identify why this is happening so that we can resolve it would be appriciated. Thank you.

**Comment by XFactHD** [comment]
FramedBlocks is currently incompatible with ProjectMMO. This needs to be fixed on their side and AFAIK from speaking with their devs, they are working on a fix. See #90 for more details.

**Comment by Gunner76th** [comment]
Thank you for the quick response
